---
sidebar: sidebar
permalink: support/additional_resources.html
keywords: netapp, support, cloud, services
summary: 'There are additional resources you can access to get help and find more information about NetApp cloud services and support, ONTAP 9, and general REST and cloud concepts.'
---

= Additional resources
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are additional resources you can access to get help and find more information about NetApp cloud services and support, ONTAP 9, and general REST and cloud concepts.

== BlueXP 

* https://docs.netapp.com/us-en/bluexp-family/[BlueXP family documentation^]
+
Central location for accessing all the BlueXP documentation for both on-premises and public cloud deployments.

== NetApp cloud resources


* https://services.cloud.netapp.com/redirect-to-login?startOnSignup=false[NetApp BlueXP website console^]
+
NetApp BlueXP website service console with sign in.

* https://mysupport.netapp.com/[NetApp Support^]
+
Access troubleshooting tools, documentation, and technical support assistance.


== REST concepts and cloud technology

* PhD https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm[dissertation^] by Roy Fielding
+
This publication introduced and established the REST application development model.

* https://auth0.com/[Auth0^]
+
This is the authentication platform service used by BlueXP.

* https://www.rfc-editor.org/[RFC editor^]
+
Authoritative source for web and Internet standards as a collection of uniquely numbered RFC documents.
