---
settings:
  name: API
  harmony_integration: maestro
  platform: cloud
  internal:
    pdf_enabled: false
    api_enabled: true
  prod:
    pdf_enabled: false
    api_enabled: true
    harmony_enabled: false
sidebar:
  entries:
    - title: BlueXP API docs
      url: /index.html
    - section: platform
    - section: workflows
    - section: api-cm
    - section: audit
    - section: cbs
    - section: copysync
    - section: credential
    - section: dw
    - section: fsx
    - section: ipa
    - section: mr
    - section: tenancy
    - section: tenancyv4
    - section: automate
    - section: support
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
  
