sidebar:
  entries:
    - title: Cloud Manager API docs
      url: /index.html
    - section: rn
    - section: intro
    - section: cm
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
