---
settings:
  name: Cloud Manager Automation
  platform: cloud
  internal:
    pdf_enabled: false
    api_enabled: true
  prod:
    pdf_enabled: false
    api_enabled: true
    harmony_enabled: false
sidebar:
  entries:
    - title: BlueXP API docs
      url: /index.html
    - section: platform
    - section: workflows
    - section: api-cm
    - section: audit
    - section: cbs
    - section: credential
    - section: dw
    - section: fsx
    - section: ipa
    - section: persistence
    - section: tenancy
    - section: automate
    - section: support
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Platform overview
          url: /platform/overview.html
        - title: Common REST implementation
          url: /platform/concepts.html
        - title: Workflow processes and tasks
          url: /platform/workflows_tasks.html
        - title: Authentication and authorization
          url: /platform/aa_concepts.html
        - title: Common workflows and tasks
          url: /platform/get_identifiers.html
    - title: Cloud Volumes ONTAP API
      links:
        - title: Overview of the API
          url: /cm/overview.html
        - title: Typical deployment
          url: /cm/cloud_manager_deployment.html
        - title: REST implementation details
          url: /cm/rest_implementation.html
        - title: API reference
          url: /cm/api_ref_resources.html
    - title: Cloud Volumes ONTAP workflows
      links:
        - title: Organization and format
          url: /cm/workflow_processes.html
        - title: AWS workflows
          url: /cm/wf_aws_before.html
        - title: Azure workflows
          url: /cm/wf_azure_before.html
        - title: GCP workflows
          url: /cm/wf_gcp_before.html
        - title: Common workflows
          url: /cm/wf_common_before.html
    - title: More resources
      links:
        - title: NetApp Cloud Solutions
          url: https://cloud.netapp.com/
        - title: NetApp Support
          url: https://mysupport.netapp.com/
        - title: ONTAP 9 documentation
          url: https://docs.netapp.com/us-en/ontap/
        - title: Additional resources
          url: /support/additional_resources.html
