---
settings:
  name: Cloud Manager Automation
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Cloud Manager API docs
      url: /index.html
    - section: platform
    - section: workflows
    - section: api-cm
    - section: support
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: Platform overview
          url: /platform/overview.html
        - title: Common REST implementation
          url: /platform/concepts.html
        - title: Workflow processes and tasks
          url: /platform/workflows_tasks.html
    - title: Cloud Volumes ONTAP API
      links:
        - title: Overview
          url: /cm/overview.html
        - title: Get started
          url: /cm/cloud_manager_deployment.html
        - title: REST details
          url: /cm/rest_implementation.html
        - title: API reference
          url: /cm/api_ref_resources.html
    - title: Cloud Volumes ONTAP workflows
      links:
        - title: AWS workflows
          url: /cm/wf_aws.html
        - title: Azure workflows
          url: /cm/wf_azure_before.html
        - title: GCP workflows
          url: /cm/wf_gcp_before.html
        - title: Common workflows
          url: /cm/wf_common.html
    - title: More resources
      links:
        - title: NetApp Cloud Solutions
          url: https://cloud.netapp.com/
        - title: NetApp Support
          url: https://mysupport.netapp.com/
        - title: ONTAP 9 documentation
          url: https://docs.netapp.com/us-en/ontap/
        - title: Auth0
          url: https://auth0.com/
