---
settings:
  name: Cloud Manager Automation
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Cloud Manager API docs
      url: /index.html
    - section: platform
    - section: api-cm
    - section: support
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
