---
sidebar: sidebar
permalink: cm/overview.html
keywords: bluexp, rest, api, credentials, cloud, volumes, ONTAP, API
summary: 'There are several things you should do to prepare to use the BlueXP REST API and associated workflows.'
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP management service is composed of multiple related REST APIs that enable you to administer your cloud-based and on-premises ONTAP storage resources. The service combines multiple API calls to execute specific tasks.

Using the REST APIs, you can perform different operations, including managing Cloud Volumes ONTAP single-node and HA resources (ONTAP instances running at the public cloud providers), on-premises ONTAP cluster resources (including AFF/FAS systems), configure cloud provider, support BlueXP account resources, and more. 

The different types of resources supporting these operations can be managed through the ONTAP management service. They can be broadly categorized as follows:

* Administrative resources
  These resources are used to set up and configure BlueXP

* Auditing resources
  Used to view details about BlueXP operations

* Authentication resources
  Used to authenticate with BlueXP  so you can run API operations

* Working environment resources
  Used to deploy and manage working environments: single Cloud Volumes ONTAP systems, Cloud Volumes ONTAP HA configurations, and ONTAP clusters

Each resource is accessible through a set of API endpoints.

.Cloud Volumes ONTAP operations

Cloud Volumes ONTAP API is widely used by developers to create and administer Cloud Volumes ONTAP working environment resources, add aggregates, volumes to Cloud Volumes ONTAP instances. The Cloud Volumes ONTAP REST API calls vary depending on the different cloud providers. Also, there are slight variations among the Cloud Volume ONTAP API calls used for single-node versus HA configurations.

.On-premises ONTAP operations

You can discover and manage the on-premises ONTAP resources by using the on-premises REST API calls. You can issue a REST API call to discover an on-premises ONTAP cluster and add it as a working environment resource. You can add volumes and perform several other activities using the REST calls.

.API workflows
The ONTAP management service supports many different workflows. Each workflow is focused on performing a specific administrative task. There are three major sets of workflows: 

* Cloud Volumes ONTAP workflows
* On-premises ONTAP workflows
* Common workflows

See link:workflow_processes.html[Workflows processes] to familiarize yourself with their common characteristics before using the workflows.

.API reference 

The link:api_reference.html[API reference] provides a single guide that you can use when working with the ONTAP management service. It includes specific reference information for each of the available operations.

