---
sidebar: sidebar
permalink: cm/overview.html
keywords: overview, introduction rest api
summary: 'The NetApp Cloud Manager service includes a REST API that you can access programmatically to administer your cloud-based resources. '
---

= Overview of the Cloud Volumes ONTAP REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The NetApp Cloud Manager service includes a REST API, Cloud Volumes ONTAP API, you can use programmatically to administer your cloud-based resources. The Cloud Volumes ONTAP REST API provides access to a subset of the functionality available in the Cloud Manager platform with a focus on Cloud Volumes ONTAP deployments.

There are several benefits to using the Cloud Volumes ONTAP REST API.

=== Built on REST technology and design principles

The Cloud Volumes ONTAP API has been designed based on REST technology and current best practices. The core technologies include Hypertext Transfer Protocol (HTTP) and JavaScript Object Notation (JSON).

=== Anchors the Cloud Manager development platform

The Cloud Volumes ONTAP REST API provides the primary external interface to the Cloud Manager platform. There are additional REST APIs which support the various platform services.

=== Access to NetApp cloud token-based security

Cloud Manager authentication and authorization is based on the _OAuth2_ standard. NetApp relies on the _Auth0_ service implementation.

=== Alignment with the Cloud Manager web UI

The Cloud Manager web user interface uses the same core REST API and therefore there is consistency between the two access paths.
