---
sidebar: sidebar
permalink: cm/prepare.html
keywords: cloud, manager, rest, api, credentials, cloud, volumes, ONTAP, API
summary: 'There are several things you should do to prepare to use the BlueXP REST API and associated workflows.'
---

= Prepare to use the API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can prepare quickly before using the ONTAP management service core REST API and the associated workflows. The core REST API contains multiple APIs to manage the Cloud Volumes ONTAP instances, discover and manage ONTAP AFF/FAS clusters that reside on your premises, and perform other functionalities such as Replication operations and more.

.Have BlueXP credentials
You'll need a NetApp account login to acquire an access token required for the workflow processes. See Signing up to NetApp BlueXP website for more information.

.Review REST concepts and implementation
Make sure to review REST implementation details for information about REST concepts and the details of how the REST API is designed.

.Be familiar with Cloud Volumes ONTAP and ONTAP on-premises concepts
If you intend to perform Cloud Volumes ONTAP and on-prem ONTAP administration tasks, you should be familiar with concepts, terminology, and procedures. See Learn about Cloud Volumes ONTAP and Learn about ONTAP on-premises for more information.

.Decide on the cloud provider and have credentials for Cloud Volumes ONTAP
Cloud Volumes ONTAP can be deployed in Amazon Web Services, Microsoft Azure, and Google Cloud Platform. You need to decide which of these providers you'll use and have the appropriate credentials.

.Decide on the licensing model for Cloud Volumes ONTAP
You can create and manage Cloud Volumes ONTAP instances using a subscription PAYGO ("pay as you go") model or apply your own licenses with BYOL ("bring your own license"). You need to decide which licensing model you'll use and adjust the workflows as needed.

.Prepare to use the workflow processes
Review Workflow processes for more information about the organization and content of the workflows. 
 	This documentation does not describe or use the Local UI.

.Locate the identifiers
You'll need the identifier values for several of the workflows. For more information see Get required identifiers.

.Related information
You should be aware of the additional resources available as suggested in Additional resources.
