---
sidebar: sidebar
permalink: cm/wf_azure_before.html
keywords: azure, workflows, cloud, manager, rest, api
summary: There are several workflows you can use with the Azure public cloud.
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several workflows you can use with the Azure public cloud.

[NOTE]
Review the link:getting_started.html[Get started] section before using any of the Cloud Manager REST API workflows.

== Workflow categories
The Azure workflows are organized into the following categories:

* Working environments
* Aggregates
* Volumes
* Metadata
* Miscellaneous

See link:workflow_processes.html[Understanding the workflow processes] for more information on these categories.

== Azure credentials
Before beginning to use the Azure workflows, you will need to create an Azure account through the Microsoft Azure portal and obtain the Azure credentials and the  subscription ID.

== Connector setup

You must have a *Connector* for the cloud environment before creating a working environment and performing other activities using the workflows. You can create a Connector using the Cloud Manager web UI. When you create a Connector, Cloud Manager adds the Azure cloud provider account that you deployed the Connector in to your list of available accounts. Your Azure account needs to have the right permissions in order to create a Connector.

Review https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html[Learn about Azure Connectors] to know how to create and deploy an Azure Connector.
