---
sidebar: sidebar
permalink: cm/wf_aws_cloud_create_we_capacity.html
keywords: paygo, cloud, volumes, ontap, connector, cloud manager, region, workspace
summary: 'You can use this workflow to create a new Cloud Volumes ONTAP working environment using PAYGO ("pay as you go") licensing. A new volume is also created with the working environment.'
---

= Create a working environment with a capacity-based license
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a new Cloud Volumes ONTAP working environment using capacity-based licensing.

You can add new volumes when creating the working environment.

[NOTE]
.When using capacity-based license:
====
* A marketplace subscription is required.
* If you purchase a license from NetApp (BYOL), a NetApp Support Site (NSS) key is required to register the system for support.
* You can add more volumes after creating the working environment. You can choose to create a volume using either link:wf_aws_ontap_create_vol_nfs.html[NFS], link:wf_aws_ontap_create_vol_cifs.html[CIFS], or link:wf_aws_ontap_create_vol_iscsi.html[iSCSI] protocol.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing[Learn more about capacity-based licensing^].
====

Choose the workflow to use based on the type of the Cloud Volumes ONTAP deployment:

* <<Create working environment for single node, Single Node>>
* <<Create working environment for high availability pair, HA pair>>

== Create working environment for single node

You can use this workflow to create a single node Cloud Volumes ONTAP working environment.

=== Step 1. Select the region

Perform the workflow link:wf_aws_cloud_md_get_regions.html#get-regions-for-single-node[Get regions] and choose the `code` value for the `region` parameter in step 11.

=== Step 2. Select the workspace

Perform the workflow link:wf_common_identity_get_tenants.html[Get tenants] and choose the `workspacePublicId` value for the `tenantId` parameter in step 11.

=== Step 3. Select the permutations configuration

Perform the workflow link:wf_aws_cloud_md_get_permutations.html#get-permutations-for-single-node[Get permutations] and choose the `ontapVersion` and `license: type` and `instanceType` values for the `vsaMetadata` parameter in step 11.

=== Step 4. Select the capacity package name

Choose the package name for the `vsaMetadata:capacityPackageName` parameter in step 11. There are three licensing options available: `Professional`, `Essentials`, and `Freemium`. Review the link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html[Cloud Volumes ONTAP licensing] types offered to new customers to know more about the available options.

=== Step 5. Select the VPC

Perform the workflow link:wf_aws_cloud_md_get_vpcs.html#get-vpcs-for-single-node[Get VPCs] and do the following:

* Choose the `vpcId` value for the `vpcId` parameter in step 11.
* Choose the `cidrBlock` values for the `ips` value of the volume parameter in step 11.

=== Step 6. Select the EBS volume configuration

Perform the workflow link:wf_aws_cloud_md_get_ebs_vol_types.html#get-ebs-volume-types-for-single-node[Get EBS volume types] and choose the `size` and `supportedVolumeTypes` values for the `ebsVolumeSize` and `ebsVolumeType` parameters in step 11.

NOTE: You need to choose one of the allowed values for the required `ebsVolumeType` parameter. We have used `gp2` value for this parameter in step 11.

=== Step 7. Attach a marketplace subscription

Perform the workflow link:wf_common_occm_attach_subscription.html[Attach SaaS subscription] and choose the `subscriptionId` value for the `saasSubscriptionId` parameter in step 11.


=== Step 8. (Optional) Obtain an NSS key

An NSS key is *optional* when using a marketplace subscription. When using BYOL, you can create a key or select an existing key, and include the NSS key in the `nssAccount` parameter in step 11.

* To create a new NSS key using the Cloud Manager user interface, perform the task link:../platform/get_nss_key.html[Generate NSS user ID] and choose the NSS ID.

* To select an existing NSS key, perform the workflow link:wf_common_identity_get_nss_keys.html[Get NSS keys] and choose the `id` of the required NSS user.

=== Step 9. (Optional) Add a BYOL license

If you purchase a license from NetApp (BYOL), make sure that the purchased license is available in the Digital Wallet. The license gets automatically added to your account if you have associated the NSS account with Cloud Manager. To add the license manually, refer to link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html#add-purchased-licenses-to-your-account[Add purchased licenses to your account^].

=== Step 10. (Optional) Create a new volume

You can optionally add a new volume while creating a working environment.

* Choose the `name` and `size` values for the corresponding `name` and `size:size` input parameters in step 11. The `size:unit` must be one of the following: TB, GB, MB, KB, or Byte.

* Choose the `policyType`, `ips`, and the `nfsVersion` parameters in the `exportPolicyInfo` input parameter in step 11 if you choose to create a volume using the NFS protocol. The `ips` parameter signifies the client IP address (could be multiple addresses) that can access the volume over the network. The `nfsVersion` parameter signifies the version of the NFS protocol that a client will use for data transmission over a network.
+
NOTE: If you choose to create a volume using CIFS protocol, you will need to set the `shareInfo` parameter. If you choose to create a volume using iSCSI protocol, you will need to set the `iscsiInfo` parameter accordingly.


=== Step 11. Create the working environment
You can issue a REST API call to create the working environment.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/vsa/working-environments
|===

.Curl example
[source,curl]
curl --request POST \
--location "https://api.bluexp.netapp.com/occm/api/vsa/working-environments" \
--header "x-agent-id: <AGENT_ID>" \ 
--header "Authorization: Bearer <ACCESS_TOKEN>" \
--header "Content-Type: application/json" \
--d @JSONinput

.JSON input example

[role="tabbed-block"]
====
.Enable Elastic Volumes
--
The `ebsVolumeType` parameter must be `gp3` or `io1`. 

`disableEv`: boolean, default value is `false`. By default, new Cloud Volumes ONTAP instances are created with Elastic Volumes enabled on aggregates.

[source,json]
{
  "name": "bycapacitycvo",
  "tenantId": "workspace-ksJa8vEY",
  "region": "us-east-1",
  "packageName": "aws_custom",
  "dataEncryptionType": "AWS",
  "capacityTier": "S3",
  "tierLevel": "normal",
  "vsaMetadata": {
    "ontapVersion": "ONTAP-9.11.1RC1.T1",
    "licenseType": "capacity-paygo",
    "instanceType": "m5.2xlarge",
    "capacityPackageName": "Professional"
  },
  "nssAccount": "b247b000-d0b3-4e05-bdca-f5e26a7xxb9",
  "writingSpeedState": "NORMAL",
  "subnetId": "subnet-xxx55de",
  "svmPassword": "password",
  "vpcId": "vpc-a762xx00",
  "ontapEncryptionParameters": null,
  "ebsVolumeType": "gp3",
  "ebsVolumeSize": {
    "size": 1,
    "unit": "TB",
    "_identifier": "1 TB"
  },
  "disableEv": "false",
  "awsTags": [],
  "optimizedNetworkUtilization": true,
  "instanceTenancy": "default",
  "iops": null,
  "throughput": null,
  "instanceProfileName": null,
  "cloudProviderAccount": "InstanceProfile",
  "saasSubscriptionId": "aws-a0s9zvu5ghepz0j9yamr2wsjk-FJsUvVHffi9",
  "backupVolumesToCbs": false,
  "enableCompliance": false,
  "enableMonitoring": false
}
--

.Disable Elastic Volumes
--
You can set `"disableEv": "true"` if you choose to create a Cloud Volumes ONTAP instance with an aggregate where Elastic Volumes is disabled.

[source,json]
{
  "name": "bycapacitycvo",
  "tenantId": "workspace-ksJa8vEY",
  "region": "us-east-1",
  "packageName": "aws_custom",
  "dataEncryptionType": "AWS",
  "capacityTier": "S3",
  "tierLevel": "normal",
  "vsaMetadata": {
    "ontapVersion": "ONTAP-9.11.1RC1.T1",
    "licenseType": "capacity-paygo",
    "instanceType": "m5.2xlarge",
    "capacityPackageName": "Professional"
  },
  "nssAccount": "b247b000-d0b3-4e05-bdca-f5e26a7xxb9",
  "writingSpeedState": "NORMAL",
  "subnetId": "subnet-xxx55de",
  "svmPassword": "password",
  "vpcId": "vpc-a762xx00",
  "ontapEncryptionParameters": null,
  "ebsVolumeType": "gp2",
  "disableEv": "true",
  "ebsVolumeSize": {
    "size": 1,
    "unit": "TB",
    "_identifier": "1 TB"
  },
  "awsTags": [],
  "optimizedNetworkUtilization": true,
  "instanceTenancy": "default",
  "iops": null,
  "throughput": null,
  "instanceProfileName": null,
  "cloudProviderAccount": "InstanceProfile",
  "saasSubscriptionId": "aws-a0s9zvu5ghepz0j9yamr2wsjk-FJsUvVHffi9",
  "backupVolumesToCbs": false,
  "enableCompliance": false,
  "enableMonitoring": false
}

--
====

This API request uses the hourly pay-as-you-go (PAYGO) subscription as indicated in the `licenseType` parameter.

.JSON output example

The JSON output example includes an example of the `VsaWorkingEnvironmentresponse`.

----
{
    "publicId": "VsaWorkingEnvironment-0NWsb1aX",
    "name": "ziv01we02",
    "tenantId": "tenantIDgoeshere",
    "svmName": "svm_ziv01we02",
    "creatorUserEmail": "user_email",
    "status": null,
    "awsProperties": null,
    "reservedSize": null,
    "encryptionProperties": null,
    "clusterProperties": null,
    "ontapClusterProperties": null,
    "actionsRequired": null,
    "interClusterLifs": null,
    "cronJobSchedules": null,
    "snapshotPolicies": null,
    "svms": null,
    "activeActions": null,
    "replicationProperties": null,
    "schedules": null,
    "cloudProviderName": "Amazon",
    "isHA": false,
    "workingEnvironmentType": "VSA",
    "supportRegistrationProperties": null,
    "supportRegistrationInformation": null,
    "haProperties": null,
    "capacityFeatures": null,
    "cloudSyncProperties": null,
    "supportedFeatures": null,
    "k8sProperties": null,
    "fpolicyProperties": null,
    "saasProperties": null,
    "cbsProperties": null,
    "complianceProperties": null,
    "monitoringProperties": null
}
----

== Create working environment for high availability pair

You can use this workflow to create an HA Cloud Volumes ONTAP working environment.

=== Step 1. Select the region

Perform the workflow link:wf_aws_cloud_md_get_regions.html#get-regions-for-single-node[Get regions] and choose the `code` value for the `region` parameter in step 13.

=== Step 2. Select the cloud provider account

Perform the workflow link:wf_common_identity_get_provider_accounts.html[Get cloud provider accounts] and choose the `publicId` value of the required account for the `cloudProviderAccount` parameter.

=== Step 3. Select the workspace

Perform the workflow link:wf_common_identity_get_tenants.html[Get tenants] and choose the `workspacePublicId` value for the `tenantId` parameter in step 13.

=== Step 4. Select the permutations configuration

Perform the workflow link:wf_aws_cloud_md_get_permutations.html#get-permutations-for-single-node[Get permutations] and choose the `ontapVersion` and `license: type` and `instanceType` values for the `vsaMetadata` parameter in step 13.

=== Step 5. Select the capacity package name

Choose the package name for the `vsaMetadata:capacityPackageName` parameter in step 13. There are three options available: `Professional`, `Essentials`, and `Freemium`.
Review the link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html[Cloud Volumes ONTAP licensing] types offered to new customers to know more about the available options.

=== Step 6. Select the packages configuration
Perform the link:wf_aws_cloud_md_get_packages.html[Get Packages] and choose the `packageName`, `instanceTenancy` and `writingSpeedState` values for the corresponding parameters in step 13.

=== Step 7. Select the VPC

Perform the workflow link:wf_aws_cloud_md_get_vpcs.html#get-vpcs-for-high-availability-pair[Get VPCs] and do the following:

* Choose the `vpcId` value for the `vpcId` parameter in step 13.
* Choose three subnets and choose the `subnetId` value for the `haParams:mediatorSubnetId`, `haParams:node1SubnetId`, `haParams:node2SubnetId` in step 13.
* Select the IPs for the `clusterFloatingIP`, `dataFloatingIP`, `dataFloatingIP2` values for the corresponding parameters in step 13.

=== Step 8. Select route table

Perform the workflow link:wf_aws_cloud_md_get_route_tables.html[Get route tables] and choose the `id` value of the required route table for `haParams:routeTableIds` parameter is step 13.

=== Step 9. Select the EBS volume configuration

Perform the workflow link:wf_aws_cloud_md_get_ebs_vol_types.html#get-ebs-volume-types-for-single-node[Get EBS volume types] and choose the `size` and `supportedVolumeTypes` values for the `ebsVolumeSize` and `ebsVolumeType` parameters in step 13.

NOTE: You need to choose one of the allowed values for the required `ebsVolumeType` parameter. We have used `gp2` value for this parameter in step 13.

=== Step 10. Attach a marketplace subscription

Perform the workflow link:wf_common_occm_attach_subscription.html[Attach SaaS subscription] and choose the `subscriptionId` value for the `saasSubscriptionId` parameter in step 13.


=== Step 11. (Optional) Obtain an NSS key

An NSS key is optional when using a marketplace subscription. When using BYOL, you can create a key or select an existing key, and include the NSS key in the `nssAccount` parameter in step 13.

* To create a new NSS key using the Cloud Manager web user interface, perform the task link:../platform/get_nss_key.html[Generate NSS user ID] and choose the NSS ID.

* To select an existing NSS key, perform the workflow link:wf_common_identity_get_nss_keys.html[Get NSS keys] and choose the `id` of the required NSS user.

=== Step 12. (Optional) Add a BYOL license

If you purchase a license from NetApp (BYOL), ensure that the purchased license is available in the Digital Wallet. The license gets automatically added to your account if you have associated the NSS account with Cloud Manager. To add the license manually, refer to link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html#add-purchased-licenses-to-your-account[Add purchased licenses to your account^].

=== Step 13. (Optional) Create a new volume

You can optionally add a new volume while creating a working environment.

* Choose the `name` and `size` values for the corresponding `name` and `size:size` input parameters in step 13. The `size:unit` must be one of the following: TB, GB, MB, KB, or Byte.

* Choose the `policyType`, `ips`, and the `nfsVersion` parameters in the `exportPolicyInfo` input parameter in step 10 if you choose to create a volume using the NFS protocol. The `ips` parameter signifies the client IP address (could be multiple addresses) that can access the volume over the network. The `nfsVersion` parameter signifies the version of the NFS protocol that a client will use for data transmission over a network.
+
[NOTE] If you choose to create a volume using CIFS protocol, you will need to set the `shareInfo` parameter. If you choose to create a volume using iSCSI protocol, you will need to set the `iscsiInfo` parameter accordingly.


=== Step 14. Create the working environment

You can issue a REST API call to create a working environment.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.


[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/aws/ha/working-environments
|===

.Curl example
[source,curl]
curl --request POST \
--location "https://api.bluexp.netapp.com/occm/api/aws/ha/working-environments" \
--header "x-agent-id: <AGENT_ID>" \ 
--header "Authorization: Bearer <ACCESS_TOKEN>" \
--header "Content-Type: application/json" \
--d @JSONinput


.JSON input example
[role="tabbed-block"]
====
.Enable Elastic Volumes
--
The `ebsVolumeType` parameter must be `gp3` or `io1`. 

`disableEv`: boolean, default value is `false`. By default, new Cloud Volumes ONTAP instances are created with Elastic Volumes enabled on aggregates.

[source,json]
{
  "name": "bycapacitycvo",
  "tenantId": "workspace-ksJa8vEY",
  "region": "us-east-1",
  "packageName": "aws_custom",
  "dataEncryptionType": "AWS",
  "capacityTier": "S3",
  "tierLevel": "normal",
  "vsaMetadata": {
    "ontapVersion": "ONTAP-9.11.1RC1.T1",
    "licenseType": "capacity-paygo",
    "instanceType": "m5.2xlarge",
    "capacityPackageName": "Professional"
  },
  "nssAccount": "b247b000-d0b3-4e05-bdca-f5e26a7xxb9",
  "writingSpeedState": "NORMAL",
  "subnetId": "subnet-xxx55de",
  "svmPassword": "password",
  "vpcId": "vpc-a762xx00",
  "ontapEncryptionParameters": null,
  "ebsVolumeType": "gp2",
  "disableEv": "true",
  "ebsVolumeSize": {
    "size": 1,
    "unit": "TB",
    "_identifier": "1 TB"
  },
  "awsTags": [],
  "optimizedNetworkUtilization": true,
  "instanceTenancy": "default",
  "iops": null,
  "throughput": null,
  "instanceProfileName": null,
  "cloudProviderAccount": "InstanceProfile",
  "saasSubscriptionId": "aws-a0s9zvu5ghepz0j9yamr2wsjk-FJsUvVHffi9",
  "backupVolumesToCbs": false,
  "enableCompliance": false,
  "enableMonitoring": false
}
--
.Disable Elastic Volumes
--

You can set `"disableEv": "true"` if you choose to create a Cloud Volumes ONTAP instance with an aggregate where Elastic Volumes is disabled.

[source,json]
{
  "name": "bycapacitycvo",
  "tenantId": "workspace-ksJa8vEY",
  "region": "us-east-1",
  "packageName": "aws_custom",
  "dataEncryptionType": "AWS",
  "capacityTier": "S3",
  "tierLevel": "normal",
  "vsaMetadata": {
    "ontapVersion": "ONTAP-9.11.1RC1.T1",
    "licenseType": "capacity-paygo",
    "instanceType": "m5.2xlarge",
    "capacityPackageName": "Professional"
  },
  "nssAccount": "b247b000-d0b3-4e05-bdca-f5e26a7xxb9",
  "writingSpeedState": "NORMAL",
  "subnetId": "subnet-xxx55de",
  "svmPassword": "password",
  "vpcId": "vpc-a762xx00",
  "ontapEncryptionParameters": null,
  "ebsVolumeType": "gp3",
  "ebsVolumeSize": {
    "size": 1,
    "unit": "TB",
    "_identifier": "1 TB"
  },
  "disableEv": "false",
  "awsTags": [],
  "optimizedNetworkUtilization": true,
  "instanceTenancy": "default",
  "iops": null,
  "throughput": null,
  "instanceProfileName": null,
  "cloudProviderAccount": "InstanceProfile",
  "saasSubscriptionId": "aws-a0s9zvu5ghepz0j9yamr2wsjk-FJsUvVHffi9",
  "backupVolumesToCbs": false,
  "enableCompliance": false,
  "enableMonitoring": false
}

--
====

This API request uses the hourly pay-as-you-go (PAYGO) subscription as indicated in the `licenseType` parameter.


.JSON output example

The JSON output includes an example of the HA working environment details.

----
{
    "publicId": "VsaWorkingEnvironment-sQ9AELDS",
    "name": "ziv04we02ha",
    "tenantId": "tenantIDshownhere",
    "svmName": "svm_ziv04we02ha",
    "creatorUserEmail": "user_email",
    "status": null,
    "awsProperties": null,
    "reservedSize": null,
    "encryptionProperties": null,
    "clusterProperties": null,
    "ontapClusterProperties": null,
    "actionsRequired": null,
    "interClusterLifs": null,
    "cronJobSchedules": null,
    "snapshotPolicies": null,
    "svms": null,
    "activeActions": null,
    "replicationProperties": null,
    "schedules": null,
    "cloudProviderName": "Amazon",
    "isHA": true,
    "workingEnvironmentType": "VSA",
    "supportRegistrationProperties": null,
    "supportRegistrationInformation": null,
    "haProperties": null,
    "capacityFeatures": null,
    "cloudSyncProperties": null,
    "supportedFeatures": null,
    "k8sProperties": null,
    "fpolicyProperties": null,
    "saasProperties": null,
    "cbsProperties": null,
    "complianceProperties": null,
    "monitoringProperties": null
}
----
