---
sidebar: sidebar
permalink: cm/wf_aws_cloud_delete_we.html
keywords: cloud, manager, rest, api, working, environment, cloud, volumes, ontap, occm
summary: 'You can delete an existing Cloud Volumes ONTAP working environment.'
---

= Delete a working environment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can delete an existing Cloud Volumes ONTAP working environment.

Choose the correct workflow depending on the type of the Cloud Volumes ONTAP deployment:

* <<Delete working environment for single node, Single Node>>
* <<Delete working environment for high availability pair, HA pair>>


== Delete working environment for single node

You can use this workflow to delete a working environment for a single node system.

=== 1. Select the working environment to use

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environment-for-single-node[Get working environments] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

=== 2. Delete the working environment

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/vsa/working-environments/{workingEnvironmentId}
|===

curl example::
[source,curl]
curl --location --request DELETE 'https://cloudmanager.cloud.netapp.com/occm/api/vsa/working-environments/<WORKING_ENV_ID>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameter <WORKING_ENV_ID> `workingEnvironmentId`

Optional query parameters:

* `localDelete`
+
If `true` the Cloud Volumes ONTAP instance in the cloud is not terminated, but Cloud Manager no longer manages it (default is `false`).

* `forceDelete`
+
If `true` the working environment is deleted even if it is part of one or more SnapMirror relationships (default is `false`).

Output::

None

== Delete working environment for high availability pair

You can use this workflow to delete a working environment for an HA pair.

=== 1. Select the working environment to use

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environments] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

=== 2. Delete the working environment

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/aws/ha/working-environments/{workingEnvironmentId}
|===

curl example::
[source,curl]
curl --location --request DELETE 'https://cloudmanager.cloud.netapp.com/occm/api/aws/ha/working-environments/<WORKING_ENV_ID>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameter <WORKING_ENV_ID> `workingEnvironmentId`

Optional query parameters:

* `localDelete`
+
If `true` the Cloud Volumes ONTAP instance in the cloud is not terminated, but Cloud Manager no longer manages it (default is `false`).

* `forceDelete`
+
If `true` the working environment is deleted even if it is part of one or more SnapMirror relationships (default is `false`).

Output::

None
