---
sidebar: sidebar
permalink: cm/wf_aws_ontap_create_vol_cifs.html
keywords: vcloud, manager, rest, api
summary: 'You can use this workflow to create a volume accessed through CIFS.'
---

= Create volume using CIFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to create a volume accessed through CIFS.

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Create volume using CIFS for single node, Single Node>>
* <<Create volume using CIFS for high availability pair, HA pair>>

== Create volume using CIFS for single node
You can use this workflow to create volume using CIFS protocol for a single node system.

=== Step 1. Choose the CIFS configuration

A CIFS server configuration must be defined for your working environment. You can do one of the following:

* If a CIFS configuration already exists, perform the workflow link:wf_aws_ontap_get_cifs.html#get-cifs-server-configuration-for-single-node[Get CIFS server configurations] to access the configuration parameters.
* If a CIFS configuration does not exist, perform the workflow link:wf_aws_ontap_create_cifs.html#create-cifs-server-configuration-for-single-node[Create CIFS server configuration] to create one.

=== Step 2. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environments-for-single-node[Get working environments] and choose the `publicId` and the `svmName` values for the `workingEnvironmentId` (working environment) and the `svmName` (SVM name) parameters. From the `capacityFeatures` field in the response, choose the value of `s3` for the `capacityTier` parameter. 

=== Step 3. Select the aggregate

Perform the workflow link:wf_aws_ontap_get_aggrs.html#get-aggregates-for-single-node[Get aggregates] and choose the `name` for the `aggregateName` value. From the `providerVolumes` field in the response, you must also choose the value of `diskType` for the `providerVolumeType` parameter, the value of `iops` for the `iops` parameter, and the value of `throughput` for the `throughput` parameter.

[NOTE]
If aggregate name does not exist and the `createAggregateIfNotFound` query parameter is set `true`, the create volume request is allowed if the named aggregate is not found.

=== Step 4. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.

=== Step 5. Create the quote

Perform the workflow link:wf_aws_ontap_create_quote.html#create-quote-for-single-node[Create quote]. This is a recommended step but is not mandatory.

=== Step 6. Create the volume

You can issue the REST API call to create a volume.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/vsa/volumes
|===

.Curl example
[source,curl]
curl --request POST
--location "https://api.bluexp.netapp.com/occm/api/vsa/volumes?createAggregateIfNotFound=false" 
--header "Content-Type: application/json" 
--header "x-agent-id: <AGENT_ID>" 
--header "Authorization: Bearer <ACCESS_TOKEN>" 
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> `(svmName)` |Query |Yes |Identifies the SVM
|`workingEnvironmentId` <WORKING_ENV_ID> |Query |Yes |Identifies the working environment ID
|<AGGR_NAME> `(aggregateName)` |Query |Yes |Identifies the aggregate
| `providerVolumeType`  | Query |Yes | Specifies the provider volume type.
| `iops` | Query | Yes| Specifies the input/output operations per second.
| `throughput` | Query| Yes | Specifies the throughput.
|===

If an aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

.JSON input example
[source,json]
{ 
    "workingEnvironmentId": "VsaWorkingEnvironment-Z1bEUQE6", 
    "svmName": "svm_testcvosn", 
    "aggregateName": "aggr1", 
    "name": "mysql_data_volume", 
    "size": { 
        "size": "1", 
        "unit": "GB" 
    }, 
    "snapshotPolicyName": "default", 
     "shareInfo": { 
        "shareName": "volume_cifs_share", 
        "accessControl": { 
            "permission": "full_control", 
            "users": [ 
                "Everyone" 
            ] 
        } 
    }, 
    "enableThinProvisioning": true, 
    "enableCompression": true, 
    "enableDeduplication": true, 
    "maxNumOfDisksApprovedToAdd": 0, 
    "evCapacityApprovedToAdd": null, 
    "verifyNameUniqueness": true, 
    "providerVolumeType": "gp3", 
    "iops": 3000, 
    "throughput": 250, 
    "capacityTier": "S3", 
    "tieringPolicy": "auto", 
    "minimumCoolingDays": 31 
} 

.Output

None

== Create volume using CIFS for high availability pair
You can use this workflow to create volume using CIFS for an HA working environment.

=== Step 1. Choose the CIFS configuration

A CIFS server configuration must be defined for your working environment. You can do one of the following:

* If a CIFS configuration already exists, perform the workflow link:wf_aws_ontap_get_cifs.html#get-cifs-server-configuration-for-high-availability-pair[Get CIFS server configurations] to access the configuration parameters.
* If a CIFS configuration does not exist, perform the workflow link:wf_aws_ontap_create_cifs.html#create-cifs-server-configuration-for-high-availability-pair[Create CIFS server configuration] to create one.

=== Step 2. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environments] and choose the `publicId` and the `svmName` values for the `workingEnvironmentId` (working environment) and the `svmName` (SVM name) parameters. From the `capacityFeatures` field in the response, choose the value of `s3` for the `capacityTier` parameter. 

=== Step 3. Select the aggregate

Perform the workflow link:wf_aws_ontap_get_aggrs.html#get-aggregates-for-high-availability-pair[Get aggregates] and choose the `name` for the `aggregateName` value. From the `providerVolumes` field in the response, you must also choose the value of `diskType` for the `providerVolumeType` parameter, the value of `iops` for the `iops` parameter, and the value of `throughput` for the `throughput` parameter.

[NOTE]
If aggregate name does not exist and the `createAggregateIfNotFound` query parameter is set `true`, the create volume request is allowed if the named aggregate is not found.

=== Step 4. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.

=== Step 5. Create the quote

Perform the workflow link:wf_aws_ontap_create_quote.html#create-quote-for-high-availability-pair[Create quote]. This is a recommended step but is not mandatory.

=== Step 6. Create the volume

You can issue the REST API call to create a volume.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/aws/ha/volumes
|===

.Curl example
[source,curl]
curl --request POST
--location "https://api.bluexp.netapp.com/occm/api/aws/ha/volumes?createAggregateIfNotFound=false" 
--header "Content-Type: application/json" 
--header "x-agent-id: <AGENT_ID>" 
--header "Authorization: Bearer <ACCESS_TOKEN>" 
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> `(svmName)` |Query |Yes |Identifies the SVM
|`workingEnvironmentId` <WORKING_ENV_ID> |Query |Yes |Identifies the working environment ID
|<AGGR_NAME> `(aggregateName)` |Query |Yes |Identifies the aggregate
| `providerVolumeType`  | Query |Yes | Specifies the provider volume type.
| `iops` | Query | Yes| Specifies the input/output operations per second.
| `throughput` | Query| Yes | Specifies the throughput.
|===

If an aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

.JSON input example
[source,json]
{ 
    "workingEnvironmentId": "VsaWorkingEnvironment-ogAu9i3S", 
    "svmName": "svm_testcvoha", 
    "aggregateName": "aggr1", 
    "name": "volume_cifs", 
    "size": { 
        "size": "1", 
        "unit": "GB" 
    }, 
    "snapshotPolicyName": "default", 
    "shareInfo": { 
        "shareName": "volume_cifs_share", 
        "accessControl": { 
            "permission": "full_control", 
            "users": [ 
                "Everyone" 
            ] 
        } 
    }, 
    "enableThinProvisioning": true, 
    "enableCompression": true, 
    "enableDeduplication": true, 
    "maxNumOfDisksApprovedToAdd": 0, 
    "evCapacityApprovedToAdd": null, 
    "verifyNameUniqueness": true, 
    "providerVolumeType": "gp3", 
    "iops": 3000, 
    "throughput": 250, 
    "capacityTier": "S3", 
    "tieringPolicy": "auto", 
    "minimumCoolingDays": 31 
} 

.Output

None
