---
sidebar: sidebar
permalink: cm/wf_azure_cloud_md_get_permutations.html
keywords: permutations, cloud, volumes, ontap, working, environment, occm
summary: You can use the permutations endpoint to retrieve the Cloud Volumes ONTAP configuration information.
---

= Get Azure permutations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the permutations endpoint to retrieve the Cloud Volumes ONTAP configuration information.

=== 1. Get the permutations

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/azure/vsa/metadata/permutations
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/azure/vsa/metadata/permutations' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --header 'Content-Type: application/json'

Input::

There are several optional query parameters you can use:

* `region` string
* `version` string
* `license` string
* `instance_type` string
* `default_instance_type` string
* `feature` string
* `latest_only` string
* `marketplace_version` string
* `marketplace_sku` string

Output::

The JSON output example includes the list of Cloud Volumes ONTAP configurations.

JSON output example::
[source,json]
[
    {
        "ontapVersion": "ONTAP-9.9.0X5.T1.azure",
        "license": {
            "type": "azure-cot-explore-paygo",
            "name": "Cloud Volumes ONTAP Explore",
            "description": "Suitable for smaller capacity applications. Supports up to 2 TB of underlying Azure storage.",
            "subName": "",
            "subDescription": "Support of tiering to object storage is not included.",
            "capacity_limit": "2TB",
            "platformLicenseRequired": false,
            "default": false,
            "capacityLimit": {
                "size": 2.0,
                "unit": "TB"
            }
        },
        "instanceType": "Standard_DS3_v2",
        "region": {
            "name": "East US 2",
            "code": "eastus2",
            "location": "Virginia",
            "s3Region": null
        },
        "defaultInstance": true,
        "features": [
            "four-nics",
            "no-sidl"
        ],
        "upgradeableFrom": [
            "9.8",
            "9.9"
        ]
    },
    {
        "ontapVersion": "ONTAP-9.9.0X5.T1.azure",
        "license": {
            "type": "azure-cot-explore-paygo",
            "name": "Cloud Volumes ONTAP Explore",
            "description": "Suitable for smaller capacity applications. Supports up to 2 TB of underlying Azure storage.",
            "subName": "",
            "subDescription": "Support of tiering to object storage is not included.",
            "capacity_limit": "2TB",
            "platformLicenseRequired": false,
            "default": false,
            "capacityLimit": {
                "size": 2.0,
                "unit": "TB"
            }
        },
        "instanceType": "Standard_DS3_v2",
        "region": {
            "name": "East US 2",
            "code": "eastus2",
            "location": "Virginia",
            "s3Region": null
        },
        "defaultInstance": true,
        "features": [
            "four-nics",
            "no-sidl"
        ],
        "upgradeableFrom": [
            "9.8",
            "9.9"
        ]
    }
]
