---
sidebar: sidebar
permalink: cm/wf_aws.html
keywords: aws, workflows, cloud, manager, rest, api
summary: There are several workflows you can use with the Amazon Web Services public cloud.
---

= Workflows for Amazon Web Services
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several workflows you can use with the Amazon Web Services public cloud.

[NOTE]
Review the link:getting_started.html[Get started] section before using any of the Cloud Manager REST API workflows.

== Workflow categories
The AWS workflows are organized into the following functional categories:

* Working environments
* Aggregates
* Volumes
* Metadata
* Miscellaneous

See link:workflow_processes.html[Understanding the workflow processes] for more information on these categories.

== Connector setup

You must have a *Connector* for the cloud environment before creating a working environment and performing other activities using the workflows. You can create a Connector using the Cloud Manager web UI. When you create a Connector, Cloud Manager adds the AWS cloud provider account that you deployed the Connector in to your list of available accounts. Your AWS account needs to have the right permissions in order to create a Connector.

Review https://docs.netapp.com/us-en/occm/task_creating_connectors_aws.html[Learn about AWS Connectors] to know how to create and deploy an AWS Connector.
