---
sidebar: sidebar
permalink: cm/wf_azure_cloud_get_wes.html
keywords: cloud, manager, rest, api, list, working, environment, occm
summary: "You can retrieve the Cloud Volumes ONTAP working environments that are visible to the user currently signed in."
---

= Get working environment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can retrieve the public identifier, working environment ID, the storage virtual machine name for Cloud Volumes ONTAP working environments and other Cloud Volumes ONTAP related details (visible to currently logged in user) which would be used in other workflows.

=== 1. Create the working environment
Perform the link:wf_azure_cloud_create_we_paygo.html[Create Azure single node working environment] workflow and select the `publicId` from the output for the `workingEnvironmentId` path parameter.

=== 2. Get the working environment

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/azure/vsa/working-environments/{workingEnvironmentId}
|===

curl::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/azure/vsa/working-environments/<WORKING_ENV_ID>?fields=status,ontapClusterProperties.fields(upgradeVersions,nodes),reservedSize,saasProperties,complianceProperties,monitoringProperties,providerProperties' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameters:

* <WORKING_ENV_ID> `workingEnvironmentId` string
* (Optional) `fields` string


Output::
The JSON output example includes details of a single node Azure working environment.

JSON output example::
[source,json]
{
    "publicId": "VsaWorkingEnvironment-zGQWVOyo",
    "name": "pradipm",
    "tenantId": "tenantID",
    "svmName": "svm_pradipm",
    "creatorUserEmail": "user_email",
    "status": {
        "status": "OFF",
        "message": "",
        "failureCauses": {
            "invalidOntapCredentials": false,
            "noCloudProviderConnection": false,
            "invalidCloudProviderCredentials": false
        },
        "extendedFailureReason": null
    },
    "providerProperties": {
        "regionName": "westeurope",
        "resourceGroup": {
            "name": "occm_group_westeurope",
            "location": "westeurope",
            "tags": {
                "KeepMe": "true"
            }
        },
        "vnetCidr": "10.0.0.0/16",
        "tags": {
            "KeepMe": "true"
        },
        "subscriptionId": "d333af45-0d07-4154-943d-c25fbbce1b18",
        "deploymentId": "",
        "creationTime": 1631783479373,
        "instanceType": "Standard_DS3_v2",
        "numOfNics": 3,
        "singleNetworkInterface": true,
        "subscriptionName": "OCCM Dev",
        "cloudProviderAccountId": null,
        "availabilityZone": null,
        "dataDisks": [
            {
                "name": "pradipm-disk-root",
                "diskSizeGB": 0,
                "lun": 0,
                "id": "/subscriptions/d333af45-0d07-4154-943d-c25fbbce1b18/resourceGroups/OCCM_GROUP_WESTEUROPE/providers/Microsoft.Compute/disks/pradipm-disk-root",
                "caching": "ReadOnly",
                "accountType": "NA",
                "managed": true,
                "encryptionSet": null
            },
            {
                "name": "pradipm-disk-nvram",
                "diskSizeGB": 0,
                "lun": 1,
                "id": "/subscriptions/d333af45-0d07-4154-943d-c25fbbce1b18/resourceGroups/occm_group_westeurope/providers/Microsoft.Compute/disks/pradipm-disk-nvram",
                "caching": "None",
                "accountType": "NA",
                "managed": true,
                "encryptionSet": null
            },
            {
                "name": "pradipm-disk-core",
                "diskSizeGB": 0,
                "lun": 2,
                "id": "/subscriptions/d333af45-0d07-4154-943d-c25fbbce1b18/resourceGroups/occm_group_westeurope/providers/Microsoft.Compute/disks/pradipm-disk-core",
                "caching": "ReadOnly",
                "accountType": "NA",
                "managed": true,
                "encryptionSet": null
            },
            {
                "name": "pradipmdatadisk3",
                "diskSizeGB": 0,
                "lun": 3,
                "id": "/subscriptions/d333af45-0d07-4154-943d-c25fbbce1b18/resourceGroups/OCCM_GROUP_WESTEUROPE/providers/Microsoft.Compute/disks/pradipmdatadisk3",
                "caching": "None",
                "accountType": "NA",
                "managed": true,
                "encryptionSet": null
            }
        ]
    },
    "reservedSize": {
        "size": 0.0,
        "unit": "GB"
    },
    "clusterProperties": null,
    "ontapClusterProperties": {
        "nodes": [],
        "clusterName": "",
        "clusterUuid": "335d50a9-16ce-11ec-b1c5-6045bd885d07",
        "ontapVersion": "",
        "systemManagerUrl": "https://10.0.1.5/sysmgr/SysMgr.html",
        "creationTime": 1631783479373,
        "licenseType": {
            "name": "Cloud Volumes ONTAP Capacity Based Charging",
            "capacityLimit": {
                "size": 500.0,
                "unit": "GB"
            }
        },
        "licensePackageName": null,
        "lastModifiedOffbox": 1632392140549,
        "offboxTarget": false,
        "upgradeVersions": null,
        "writingSpeedState": null,
        "broadcastDomainInfos": [],
        "evaluation": false,
        "capacityTierInfo": null,
        "canConfigureCapacityTier": false,
        "usedCapacity": {
            "size": 0.0,
            "unit": "GB"
        },
        "userName": "admin",
        "wormEnabled": false,
        "isSpaceReportingLogical": false
    },
    "cloudProviderName": "Azure",
    "snapshotPolicies": null,
    "actionsRequired": null,
    "activeActions": null,
    "replicationProperties": null,
    "schedules": null,
    "svms": null,
    "workingEnvironmentType": "VSA",
    "supportRegistrationProperties": null,
    "supportRegistrationInformation": [],
    "capacityFeatures": null,
    "encryptionProperties": null,
    "supportedFeatures": null,
    "isHA": false,
    "haProperties": null,
    "fpolicyProperties": null,
    "saasProperties": {
        "subscription": null,
        "freeTrialExpiry": null,
        "saasEnabled": null,
        "capacityLicensePackage": null
    },
    "cbsProperties": null,
    "complianceProperties": {
        "scanStatus": "SCAN_DISABLED",
        "complianceStatus": null,
        "lastDeploymentError": null,
        "complianceBackupStatus": null
    },
    "monitoringProperties": {
        "monitoringStatus": "MONITORING_DISABLED",
        "monitoringInfo": null,
        "tenantUrl": null
    },
    "licensesInformation": null
}
