---
sidebar: sidebar
permalink: cm/wf_aws_cloud_md_get_permutations.html
keywords: permutations, cloud, volumes, ontap, working, environment, occm
summary: You can use the permutations endpoint to retrieve the Cloud Volumes ONTAP configuration information.
---

= Get permutations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the permutations endpoint to retrieve the Cloud Volumes ONTAP configuration information.

Choose the correct workflow depending on the type of Cloud Volumes ONTAP deployment:

* <<Get permutations for single node, Single Node>>
* <<Get permutations for high availability pair, HA pair>>

== Get permutations for single node
You can use this workflow to retrieve the configuration information for a single node working environment.

=== 1. Get the permutations

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/vsa/metadata/permutations
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/vsa/metadata/permutations' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --header 'Content-Type: application/json'

Input::

There are several optional query parameters you can use:

* region
* version
* license
* instance_type
* default_instance_type
* feature
* latest_only
* ami

Output::

The JSON output example includes the list of Cloud Volumes ONTAP configurations.

JSON output example::
[source,json]
[
   {
       "ontapVersion": "ONTAP-9.9.0X4.T1",
       "license": {
           "type": "cot-explore-paygo",
           "name": "Cloud Volumes ONTAP Explore",
           "description": "Suitable for smaller capacity applications. Supports up to 2 TB of underlying AWS storage.",
           "subName": "",
           "subDescription":"Support of tiering to object storage is not included.",
           "capacity_limit": "2TB",
           "platformLicenseRequired": false,
           "default":false,
           "capacityLimit": {"size":2.0, "unit": "TB"}
       },
      "instanceType": "m5.xlarge",
      "region": {
         "name": "EU",
         "code": "eu-central-1",
         "location": "Frankfurt",
         "s3Region": "eu-central-1"
      },
      "defaultInstance":true,
      "features": ["ena","kvm","network-utilization"],
      "upgradeableFrom": ["9.8","9.9.0"]
   }
]

== Get permutations for high availability pair
You can use this workflow to retrieve the configuration information for an HA working environment.

=== 1. Get the permutations

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/aws/ha/metadata/permutations
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/aws/ha/metadata/permutations?latest_only=true' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --header 'Content-Type: application/json'

Input::

There are several optional query parameters you can use:

* region
* version
* license
* instance_type
* default_instance_type
* feature
* latest_only
* ami

Output::

The JSON output example includes the list of Cloud Volumes ONTAP configurations.

JSON output example::
[source,json]
[
    {
        "ontapVersion": "ONTAP-9.9.0X6.T1.ha",
        "license": {
            "type": "ha-cot-explore-paygo",
            "name": "Cloud Volumes ONTAP Explore",
            "description": "Suitable for smaller capacity applications. Supports up to 2 TB of underlying AWS storage.",
            "subName": "",
            "subDescription": "Support of tiering to object storage is not included.",
            "capacity_limit": "2TB",
            "platformLicenseRequired": false,
            "default": false,
            "capacityLimit": {
                "size": 2.0,
                "unit": "TB"
            }
        },
        "instanceType": "m5.xlarge",
        "region": {
            "name": "EU",
            "code": "eu-central-1",
            "location": "Frankfurt",
            "s3Region": "eu-central-1"
        },
        "defaultInstance": true,
        "features": [
            "ena",
            "kvm",
            "network-utilization"
        ],
        "upgradeableFrom": [
            "9.8",
            "9.9.0"
        ]
    },
    {
        "ontapVersion": "ONTAP-9.9.0X6.T1.ha",
        "license": {
            "type": "ha-cot-explore-paygo",
            "name": "Cloud Volumes ONTAP Explore",
            "description": "Suitable for smaller capacity applications. Supports up to 2 TB of underlying AWS storage.",
            "subName": "",
            "subDescription": "Support of tiering to object storage is not included.",
            "capacity_limit": "2TB",
            "platformLicenseRequired": false,
            "default": false,
            "capacityLimit": {
                "size": 2.0,
                "unit": "TB"
            }
        },
        "instanceType": "m5.xlarge",
        "region": {
            "name": "EU",
            "code": "eu-west-1",
            "location": "Ireland",
            "s3Region": "eu-west-1"
        },
        "defaultInstance": true,
        "features": [
            "ena",
            "kvm",
            "network-utilization"
        ],
        "upgradeableFrom": [
            "9.8",
            "9.9.0"
        ]
    }
]
