---
sidebar: sidebar
permalink: cm/wf_aws_ontap_create_vol_iscsi.html
keywords: cloud, manager, rest, api
summary: 'You can use this workflow to create a volume accessed through iSCSI. There are two workflows available depending on whether a new or existing iGroup is used'
---

= Create volume using iSCSI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to create a volume accessed through iSCSI protocol.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Create volume using iSCSI for single node, Single Node>>
* <<Create volume using iSCSI for high availability pair, HA pair>>

== Create volume using iSCSI for single node
You can use this workflow to create volume using iSCSI for a single node system.

There are two workflows available depending on whether a new or existing iGroup is used. You need to select the correct workflow:

* <<Create volume using iSCSI with a new iGroup>>
* <<Create volume using iSCSI with an existing iGroup>>

=== Create volume using iSCSI with a new iGroup

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.

==== Step 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environments-for-single-node[Get working environments] and choose the `publicId` value for the `workingEnvironmentId` parameter and the `svmName` value for the `svmName` parameter. From the `capacityFeatures` field in the response, choose the value of `s3` for the `capacityTier` parameter. 

==== Step 2. Select the aggregate

Perform the workflow link:wf_aws_ontap_get_aggrs.html#get-aggregates-for-single-node[Get aggregates] and choose the `name` for the `aggregateName` value. From the `providerVolumes` field in the response, you must also choose the value of `diskType` for the `providerVolumeType` parameter, the value of `iops` for the `iops` parameter, and the value of `throughput` for the `throughput` parameter.

==== Step 3. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.

==== Step 4. Choose the iscasiInfo parameters

You must choose the following values for the REST API call:

* A unique igroup name for `igroupCreationRequest` -> `igroupName` parameter
* The required iqn’s to `igroupCreationRequest` -> `initiators` parameter.
* The required operating system for the `osName` parameter from one of the following:
** windows
** linux
** vmware
** windows_2008
** windows_gpt

==== Step 5. Create the quote

Perform the workflow link:wf_aws_ontap_create_quote.html#create-quote-for-single-node[Create quote]. This is a recommended step but is not mandatory.

==== Step 6. Create the volume

You can issue the REST API call to create a volume.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/vsa/volumes
|===

.Curl example
[source,curl]
curl --request POST \
--location "https://api.bluexp.netapp.com/occm/api/vsa/volumes?createAggregateIfNotFound=false" \
--header 'Content-Type: application/json' \
--header 'x-agent-id: <AGENT_ID>' \
--header 'Authorization: Bearer <ACCESS_TOKEN>' \
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> `(svmName)` |Query |Yes |Identifies the SVM
|`workingEnvironmentId` <WORKING_ENV_ID> |Query |Yes |Identifies the working environment ID
|<AGGR_NAME> `(aggregateName)` |Query |Yes |Identifies the aggregate
| `providerVolumeType`  | Query |Yes | Specifies the provider volume type.
| `iops` | Query | Yes| Specifies the input/output operations per second.
| `throughput` | Query| Yes | Specifies the throughput.
|===


If aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

.JSON input example
[source,json]
{
    "workingEnvironmentId": "VsaWorkingEnvironment-Z1bEUQE6", 
    "svmName": "svm_testcvosn", 
    "aggregateName": "aggr1", 
    "name": "mysql_data_volume", 
    "size": { 
        "size": "1", 
        "unit": "GB" 
    }, 
    "snapshotPolicyName": "default", 
    "iscsiInfo": { 
          "igroupCreationRequest": { 
               "igroupName": "myIgroup", 
                "initiators": [ 
                       "iqn.1994-05.com.redhat:96de86825216", 
                        "iqn.1994-05.com.redhat:96de86823426" 
                  ] 
          }, 
         "osName": "linux" 
    }, 
    "enableThinProvisioning": true, 
    "enableCompression": true, 
    "enableDeduplication": true, 
    "maxNumOfDisksApprovedToAdd": 0, 
    "evCapacityApprovedToAdd": null, 
    "verifyNameUniqueness": true, 
    "providerVolumeType": "gp3", 
    "iops": 3000, 
    "throughput": 250, 
    "capacityTier": "S3", 
    "tieringPolicy": "auto", 
    "minimumCoolingDays": 31 
} 

.Output

None

=== Create volume using iSCSI with an existing iGroup

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.

==== Step 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environments-for-single-node[Get working environments] and choose the `publicId` value for the `workingEnvironmentId` parameter and the `svmName` value for the `svmName` parameter.

==== Step 2. Select the aggregate

Perform the workflow link:wf_aws_ontap_get_aggrs.html#get-aggregates-for-single-node[Get aggregates] and choose the `name` for the `aggregateName` parameter.

==== Step 3. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.

==== Step 4. Choose the iGroup

Perform the workflow link:wf_aws_ontap_get_igroups.html#get-igroups-for-single-node[Get iGroups] and choose the igroups for the `iscasiInfo` -> `igroups` value. Also select the `osType` value for the `iscasiInfo` -> `osName`.

==== Step 5. Create the quote

Perform the workflow link:wf_aws_ontap_create_quote.html#create-quote-for-single-node[Create quote]. This is a recommended step but is not mandatory.

==== Step 6. Create the volume

You can issue the REST API call to create a volume.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.


[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/vsa/volumes
|===

.Curl example
[source,curl]
curl --request POST \
--location "https://api.bluexp.netapp.com/occm/api/vsa/volumes?createAggregateIfNotFound=false" \
--header "Content-Type: application/json" \
--header "x-agent-id: <AGENT_ID>" \
--header "Authorization: Bearer <ACCESS_TOKEN>" \
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> `(svmName)` |Query |Yes |Identifies the SVM
|`workingEnvironmentId` <WORKING_ENV_ID> |Query |Yes |Identifies the working environment ID
|<AGGR_NAME> `(aggregateName)` |Query |Yes |Identifies the aggregate
|===


If an aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

.JSON input example
[source,json]
{
  "workingEnvironmentId": "VsaWorkingEnvironment-UvFmWXoD",
  "svmName": "svm_zivaws01we01",
  "aggregateName": "aggr1",
  "name": "zivaws01we01vol05Iscsi",
  "size": {
    "size": 100,
    "unit": "GB"
  },
  "iscsiInfo": {
    "igroups": ["zivIgroup1"],
    "osName": "linux"
  },
  "snapshotPolicyName": "default",
  "enableThinProvisioning": true,
  "enableCompression": true,
  "enableDeduplication": true,
  "maxNumOfDisksApprovedToAdd": 0
}

.Output

None

== Create volume using iSCSI for high availability pair
You can use this workflow to create volume using iSCSI for an HA working environment.

There are two workflows available depending on whether a new or existing iGroup is used. You need to select the correct workflow:

* <<Create volume using iSCSI with a new iGroup>>
* <<Create volume using iSCSI with an existing iGroup>>

=== Create volume using iSCSI with a new iGroup

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.

==== Step 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environments-for-high-availability-pair[Get working environments] and choose the `publicId` value for the `workingEnvironmentId` parameter and the `svmName` value for the `svmName` parameter. From the `capacityFeatures` field in the response, choose the value of `s3` for the `capacityTier` parameter. 

==== Step 2. Select the aggregate

Perform the workflow link:wf_aws_ontap_get_aggrs.html#get-aggregates-for-high-availability-pair[Get aggregates] and choose the `name` for the `aggregateName` parameter. From the `providerVolumes` field in the response, you must also choose the value of `diskType` for the `providerVolumeType` parameter, the value of `iops` for the `iops` parameter, and the value of `throughput` for the `throughput` parameter.

==== Step 3. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.

==== Step 4. Choose the iscasiInfo parameters

You must choose the following values for the REST API call:

* A unique igroup name for `igroupCreationRequest` -> `igroupName` parameter
* The required iqn’s to `igroupCreationRequest` -> `initiators` parameter.
* The required operating system for the `osName` parameter from one of the following:
** windows
** linux
** vmware
** windows_2008
** windows_gpt

==== Step 5. Create the quote

Perform the workflow link:wf_aws_ontap_create_quote.html#create-quote-for-high-availability-pair[Create quote].This is a recommended step but is not mandatory.

==== Step 6. Create the volume

You can issue the REST API call to create a volume.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/aws/ha/volumes
|===

.Curl example
[source,curl]
curl --request POST \
--location "https://api.bluexp.netapp.com/occm/api/aws/ha/volumes?createAggregateIfNotFound=false" \
--header "Content-Type: application/json" \
--header "x-agent-id: <AGENT_ID>" \
--header "Authorization: Bearer <ACCESS_TOKEN>" \
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> `(svmName)` |Query |Yes |Identifies the SVM
|`workingEnvironmentId` <WORKING_ENV_ID> |Query |Yes |Identifies the working environment ID
|<AGGR_NAME> `(aggregateName)` |Query |Yes |Identifies the aggregate
|===


If aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

.JSON input example
[source,json]
{ 
    "workingEnvironmentId": "VsaWorkingEnvironment-ogAu9i3S", 
    "svmName": "svm_testcvoha", 
    "aggregateName": "aggr1", 
    "name": "volume_iscsi", 
    "size": { 
        "size": "1", 
        "unit": "GB" 
    }, 
    "snapshotPolicyName": "default", 
    "iscsiInfo": { 
    "igroupCreationRequest": { 
        "igroupName": "myIgroup", 
        "initiators": [ 
            "iqn.1994-05.com.redhat:96de86825216", 
            "iqn.1994-05.com.redhat:96de86823426" 
        ] 
    }, 
    "osName": "linux" 
    }, 
    "enableThinProvisioning": true, 
    "enableCompression": true, 
    "enableDeduplication": true, 
    "maxNumOfDisksApprovedToAdd": 0, 
    "evCapacityApprovedToAdd": null, 
    "verifyNameUniqueness": true, 
    "providerVolumeType": "gp3", 
    "iops": 3000, 
    "throughput": 250, 
    "capacityTier": "S3", 
    "tieringPolicy": "auto", 
    "minimumCoolingDays": 31 
} 

.Output

None

=== Create volume using iSCSI with an existing iGroup

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.

==== Step 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environments-for-high-availability-pair[Get working environments] and choose the `publicId` value for the `workingEnvironmentId` parameter and the `svmName` value for the `svmName` parameter.

==== Step 2. Select the aggregate

Perform the workflow link:wf_aws_ontap_get_aggrs.html#get-aggregates-for-high-availability-pair[Get aggregates] and choose the `name` for the `aggregateName` parameter.

==== Step 3. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.

==== Step 4. Choose the iGroup

Perform the workflow link:wf_aws_ontap_get_igroups.html#get-igroups-for-high-availability-pair[Get iGroups] and choose the igroups for the `iscasiInfo` -> `igroups` value. Also select the `osType` value for the `iscasiInfo` -> `osName`.

==== Step 5. Create the quote

Perform the workflow link:wf_aws_ontap_create_quote.html#create-quote-for-high-availability-pair[Create quote]. This is a recommended step but is not mandatory.

==== Step 6. Create the volume

You can issue the REST API call to create a volume.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/vsa/volumes
|===

.Curl example
[source,curl]
curl --request POST \
--location "https://api.bluexp.netapp.com/occm/api/aws/ha/volumes?createAggregateIfNotFound=false" \
--header "Content-Type: application/json" \
--header "x-agent-id: <AGENT_ID>" \
--header "Authorization: Bearer <ACCESS_TOKEN>" \
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> `(svmName)` |Query |Yes |Identifies the SVM
|`workingEnvironmentId` <WORKING_ENV_ID> |Query |Yes |Identifies the working environment ID
|<AGGR_NAME> `(aggregateName)` |Query |Yes |Identifies the aggregate
|===


If an aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

.JSON input example
[source,json]
{
  "workingEnvironmentId": "VsaWorkingEnvironment-UvFmWXoD",
  "svmName": "svm_zivaws01we01",
  "aggregateName": "aggr1",
  "name": "zivaws01we01vol05Iscsi",
  "size": {
    "size": 100,
    "unit": "GB"
  },
  "iscsiInfo": {
    "igroups": ["zivIgroup1"],
    "osName": "linux"
  },
  "snapshotPolicyName": "default",
  "enableThinProvisioning": true,
  "enableCompression": true,
  "enableDeduplication": true,
  "maxNumOfDisksApprovedToAdd": 0
}

.Output

None
