---
sidebar: sidebar
permalink: cm/wf_azure_ontap_get_igroups.html
keywords: cloud, manager, rest, api, igroups, cifs, server, configuration
summary: "You can use this workflow to retrieve all the iGroups."
---

= Get iGroups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to retrieve all the initiator groups (iGroups).

Choose the correct workflow depending on the type of Cloud Volumes ONTAP deployment:

* <<Get iGroups for single node, Single Node>>
* <<Get iGroups for high availability pair, HA pair>>

== Get iGroups for single node
You can use this workflow to retrieve iGroups for a single node working environment.

=== 1. Select the working environment

Perform the workflow link:wf_azure_cloud_create_we_paygo.html#create-working-environment-for-single-node[Create Azure single node working environment] and choose the `publicId` and `svmName` values for the working environment `workingEnvironmentId` and `svmName` path parameters.

=== 2. Get the CIFS configurations

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/azure/vsa/volumes/igroups/{workingEnvironmentId}/{svmName}
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/azure/vsa/volumes/igroups/<WORKING_ENV_ID>/<SVM_NAME>' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --header 'Content-Type: application/json'

Input::

* Path parameter <WORKING_ENV_ID> `workingEnvironmentId` string
* Path parameter <SVM_NAME> `svmName` string

Output::

The JSON output example includes a list of iGroups.

JSON output example::
[source,json]
[
    {
        "igroupName": "zivIgroup1",
        "osType": "linux",
        "portsetName": "",
        "igroupType": "iscsi",
        "initiators": [
            "iqn.1994-05.com.redhat:0x0xx000000x"
        ]
    },
    {
        "igroupName": "zivIgroup2",
        "osType": "linux",
        "portsetName": "",
        "igroupType": "iscsi",
        "initiators": [
            "iqn.1994-05.com.redhat:0x0xx000000x"
        ]
    }
]

== Get iGroups for high availability pair
You can use this workflow to retrieve iGroups for an HA working environment.

=== 1. Select the working environment

Perform the workflow link:wf_azure_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Create Azure single node working environment] and choose the `publicId` and `svmName` values for the working environment `workingEnvironmentId` and `svmName` path parameters.

=== 2. Get the CIFS configurations

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/azure/ha/volumes/igroups/{workingEnvironmentId}/{svmName}
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/azure/ha/volumes/igroups/<WORKING_ENV_ID>/<SVM_NAME>' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --header 'Content-Type: application/json'

Input::

* Path parameter <WORKING_ENV_ID> `workingEnvironmentId` string
* Path parameter <SVM_NAME> `svmName` string

Output::

The JSON output example includes a list of iGroups.

JSON output example::
[source,json]
[
    {
        "igroupName": "zivIgroup1",
        "osType": "linux",
        "portsetName": "",
        "igroupType": "iscsi",
        "initiators": [
            "iqn.1994-05.com.redhat:0x0xx000000x"
        ]
    },
    {
        "igroupName": "zivIgroup2",
        "osType": "linux",
        "portsetName": "",
        "igroupType": "iscsi",
        "initiators": [
            "iqn.1994-05.com.redhat:0x0xx000000x"
        ]
    }
]
