---
sidebar: sidebar
permalink: cm/wf_aws_ontap_delete_volume.html
keywords: delete, volume, cloud, manager, rest, api, existing, volume, aws, workflows
summary: "You can delete an existing volume."
---

= Delete volume
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can delete an existing volume.

Choose the correct workflow depending on the type of Cloud Volumes ONTAP deployment:

* <<Delete volume for single node, Single Node>>
* <<Delete volume for high availability pair, HA pair>>

== Delete volume for single node
You can use this workflow to delete a volume for a single node working environment.

=== 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environment-for-single-node[Get working environments] and choose the `publicId` and `svmName` values of the working environment  for the `workingEnvironmentId` and `svmName` path parameters.

=== 2. Select the volume

Perform the workflow link:wf_aws_ontap_get_volumes.html#get-volumes-for-a-single-node[Get volumes] and choose the `name` of the required volume for the `volumeName` path parameter.

=== 3. Delete the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/vsa/volumes/{workingEnvironmentId}/{svmName}/{volumeName}
|===


curl example::
[source,curl]
curl --location --request DELETE 'https://cloudmanager.cloud.netapp.com/occm/api/vsa/volumes/<WORKING_ENV_ID>/<SVM_NAME>/<VOLUME_NAME>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameters:

* <WORKING_ENV_ID> `(workingEnvironmentId)`
* <SVM_NAME> `(svmName)`
* <VOLUME_NAME> `(volumeName)`

Output::

None

== Delete volume for high availability pair
You can use this workflow to delete a volume for an HA working environment.

=== 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environments] and choose the `publicId` and `svmName` values of the working environment for the `workingEnvironmentId` and `svmName` path parameters.

=== 2. Select the volume

Perform the workflow link:wf_aws_ontap_get_volumes.html#get-volumes-for-high-availability-pair[Get volumes] and choose the `name` of teh required volume for `volumeName` path parameter.

=== 3. Delete the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/aws/ha/volumes/{workingEnvironmentId}/{svmName}/{volumeName}
|===


curl example::
[source,curl]
curl --location --request DELETE 'https://cloudmanager.cloud.netapp.com/occm/api/aws/ha/volumes/<WORKING_ENV_ID>/<SVM_NAME>/<VOLUME_NAME>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameters:

* <WORKING_ENV_ID> `(workingEnvironmentId)`
* <SVM_NAME> `(svmName)`
* <VOLUME_NAME> `(volumeName)`

Output::

None
