---
sidebar: sidebar
permalink: cm/wf_azure_cloud_get_wes.html
keywords: cloud, manager, rest, api, list, working, environment, occm
summary: "You can retrieve the Cloud Volumes ONTAP working environments that are visible to the user currently signed in."
---

= Get working environment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can retrieve the public identifier, working environment ID, the storage virtual machine name for Cloud Volumes ONTAP working environments and other Cloud Volumes ONTAP related details (visible to currently logged in user) which would be used in other workflows.


Choose the correct workflow depending on the type of Cloud Volumes ONTAP deployment:

* <<Get working environment for single node, Single Node>>
* <<Get working environment for high availability pair, HA pair>>

== Get working environment for single node
You can use this workflow to retrieve the working environments' details of a single node system.

=== 1. Create the working environment
Perform the link:wf_azure_cloud_create_we_paygo.html#create-working-environment-for-single-node[Create Azure single node working environment] workflow and select the `publicId` from the output for the `workingEnvironmentId` path parameter.

=== 2. Get the working environment

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/azure/vsa/working-environments/{workingEnvironmentId}
|===

curl::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/azure/vsa/working-environments/<WORKING_ENV_ID>?fields=status,ontapClusterProperties.fields(upgradeVersions,nodes),reservedSize,saasProperties,complianceProperties,monitoringProperties,providerProperties' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameters:

* <WORKING_ENV_ID> `workingEnvironmentId` string
* (Optional) `fields` string


Output::
The JSON output example includes details of a single node Azure working environment.

JSON output example::
[source,json]
{
    "publicId": "VsaWorkingEnvironment-zGQWVOyo",
    "name": "pradipm",
    "tenantId": "tenantID",
    "svmName": "svm_pradipm",
    "creatorUserEmail": "user_email",
    "status": {
        "status": "OFF",
        "message": "",
        "failureCauses": {
            "invalidOntapCredentials": false,
            "noCloudProviderConnection": false,
            "invalidCloudProviderCredentials": false
        },
        "extendedFailureReason": null
    },
    "providerProperties": {
        "regionName": "westeurope",
        "resourceGroup": {
            "name": "occm_group_westeurope",
            "location": "westeurope",
            "tags": {
                "KeepMe": "true"
            }
        },
        "vnetCidr": "10.0.0.0/16",
        "tags": {
            "KeepMe": "true"
        },
        "subscriptionId": "x000xx00-0x00-0000-000x",
        "deploymentId": "",
        "creationTime": 1631783479373,
        "instanceType": "Standard_DS3_v2",
        "numOfNics": 3,
        "singleNetworkInterface": true,
        "subscriptionName": "OCCM Dev",
        "cloudProviderAccountId": null,
        "availabilityZone": null,
        "dataDisks": [
            {
                "name": "pradipm-disk-root",
                "diskSizeGB": 0,
                "lun": 0,
                "id": "/subscriptions/x000xx00-0x00-0000-000x/resourceGroups/OCCM_GROUP_WESTEUROPE/providers/Microsoft.Compute/disks/pradipm-disk-root",
                "caching": "ReadOnly",
                "accountType": "NA",
                "managed": true,
                "encryptionSet": null
            },
            {
                "name": "pradipm-disk-nvram",
                "diskSizeGB": 0,
                "lun": 1,
                "id": "/subscriptions/dx000xx00-0x00-0000-000x/resourceGroups/occm_group_westeurope/providers/Microsoft.Compute/disks/pradipm-disk-nvram",
                "caching": "None",
                "accountType": "NA",
                "managed": true,
                "encryptionSet": null
            },
            {
                "name": "pradipm-disk-core",
                "diskSizeGB": 0,
                "lun": 2,
                "id": "/subscriptions/x000xx00-0x00-0000-000x/resourceGroups/occm_group_westeurope/providers/Microsoft.Compute/disks/pradipm-disk-core",
                "caching": "ReadOnly",
                "accountType": "NA",
                "managed": true,
                "encryptionSet": null
            },
            {
                "name": "pradipmdatadisk3",
                "diskSizeGB": 0,
                "lun": 3,
                "id": "/subscriptions/x000xx00-0x00-0000-000xfbbce1b18/resourceGroups/OCCM_GROUP_WESTEUROPE/providers/Microsoft.Compute/disks/pradipmdatadisk3",
                "caching": "None",
                "accountType": "NA",
                "managed": true,
                "encryptionSet": null
            }
        ]
    },
    "reservedSize": {
        "size": 0.0,
        "unit": "GB"
    },
    "clusterProperties": null,
    "ontapClusterProperties": {
        "nodes": [],
        "clusterName": "",
        "clusterUuid": "xxxxx0000000000x00x0x00x0x0x0",
        "ontapVersion": "",
        "systemManagerUrl": "https://10.0.1.5/sysmgr/SysMgr.html",
        "creationTime": 1631783479373,
        "licenseType": {
            "name": "Cloud Volumes ONTAP Capacity Based Charging",
            "capacityLimit": {
                "size": 500.0,
                "unit": "GB"
            }
        },
        "licensePackageName": null,
        "lastModifiedOffbox": 1632392140549,
        "offboxTarget": false,
        "upgradeVersions": null,
        "writingSpeedState": null,
        "broadcastDomainInfos": [],
        "evaluation": false,
        "capacityTierInfo": null,
        "canConfigureCapacityTier": false,
        "usedCapacity": {
            "size": 0.0,
            "unit": "GB"
        },
        "userName": "admin",
        "wormEnabled": false,
        "isSpaceReportingLogical": false
    },
    "cloudProviderName": "Azure",
    "snapshotPolicies": null,
    "actionsRequired": null,
    "activeActions": null,
    "replicationProperties": null,
    "schedules": null,
    "svms": null,
    "workingEnvironmentType": "VSA",
    "supportRegistrationProperties": null,
    "supportRegistrationInformation": [],
    "capacityFeatures": null,
    "encryptionProperties": null,
    "supportedFeatures": null,
    "isHA": false,
    "haProperties": null,
    "fpolicyProperties": null,
    "saasProperties": {
        "subscription": null,
        "freeTrialExpiry": null,
        "saasEnabled": null,
        "capacityLicensePackage": null
    },
    "cbsProperties": null,
    "complianceProperties": {
        "scanStatus": "SCAN_DISABLED",
        "complianceStatus": null,
        "lastDeploymentError": null,
        "complianceBackupStatus": null
    },
    "monitoringProperties": {
        "monitoringStatus": "MONITORING_DISABLED",
        "monitoringInfo": null,
        "tenantUrl": null
    },
    "licensesInformation": null
}


== Get working environment for high availability pair
You can use this workflow to retrieve the working environments' details of an HA working environment.

=== 1. Create an Azure HA working environment
Perform the link:wf_azure_cloud_create_we_paygo.html#create-working-environment-for-high-availability-pair[Create Azure dual node working environment] workflow and select the `publicId` from the output for the `workingEnvironmentId` path parameter.

=== 2. Get the working environment

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/azure/ha/working-environments/{workingEnvironmentId}
|===

curl::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/azure/ha/working-environments/<WORKING_ENV_ID>?fields=status,ontapClusterProperties.fields(upgradeVersions,nodes),reservedSize,saasProperties,complianceProperties,monitoringProperties,providerProperties' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameters:

* <WORKING_ENV_ID> `workingEnvironmentId` string
* (Optional) `fields` string


Output::
The JSON output example includes details of a single node Azure working environment.

JSON output example::
[source,json]
{
    "publicId": "VsaWorkingEnvironment-Kms14Nkv",
    "name": "ShirleyHa2701",
    "tenantId": "Tenant-c6wmZaze",
    "svmName": "svm_ShirleyHa2701",
    "creatorUserEmail": "useremail",
    "status": {
        "status": "ON",
        "message": "",
        "failureCauses": {
            "invalidOntapCredentials": false,
            "noCloudProviderConnection": false,
            "invalidCloudProviderCredentials": false
        },
        "extendedFailureReason": null
    },
    "providerProperties": {
        "regionName": "eastus2",
        "resourceGroup": {
            "name": "ShirleyHa2701-rg",
            "location": "eastus2",
            "tags": {}
        },
        "vnetCidr": "10.0.0.0/16",
        "tags": {},
        "subscriptionId": "x000xx00-0x00-0000-000x",
        "deploymentId": "",
        "creationTime": 1611698774849,
        "instanceType": "Standard_DS4_v2",
        "numOfNics": 8,
        "singleNetworkInterface": false,
        "subscriptionName": "OCCM Dev",
        "cloudProviderAccountId": null,
        "availabilityZone": null,
        "dataDisks": [
            {
                "name": "ShirleyHa2701-vm1-disk-nvram",
                "diskSizeGB": 128,
                "lun": 1,
                "id": "/subscriptions/x000xx00-0x00-0000-000x/resourceGroups/ShirleyHa2701-rg/providers/Microsoft.Compute/disks/ShirleyHa2701-vm1-disk-nvram",
                "caching": "None",
                "accountType": "Premium_LRS",
                "managed": true,
                "encryptionSet": null
            },
            {
                "name": "ShirleyHa2701-vm1-disk-core",
                "diskSizeGB": 1024,
                "lun": 2,
                "id": "/subscriptions/x000xx00-0x00-0000-000x/resourceGroups/ShirleyHa2701-rg/providers/Microsoft.Compute/disks/ShirleyHa2701-vm1-disk-core",
                "caching": "ReadOnly",
                "accountType": "Standard_LRS",
                "managed": true,
                "encryptionSet": null
            },
            {
                "name": "ShirleyHa2701-vm2-disk-nvram",
                "diskSizeGB": 128,
                "lun": 1,
                "id": "/subscriptions/x000xx00-0x00-0000-000x/resourceGroups/ShirleyHa2701-rg/providers/Microsoft.Compute/disks/ShirleyHa2701-vm2-disk-nvram",
                "caching": "None",
                "accountType": "Premium_LRS",
                "managed": true,
                "encryptionSet": null
            },
            {
                "name": "ShirleyHa2701-vm2-disk-core",
                "diskSizeGB": 1024,
                "lun": 2,
                "id": "/subscriptions/x000xx00-0x00-0000-000x/resourceGroups/ShirleyHa2701-rg/providers/Microsoft.Compute/disks/ShirleyHa2701-vm2-disk-core",
                "caching": "ReadOnly",
                "accountType": "Standard_LRS",
                "managed": true,
                "encryptionSet": null
            }
        ]
    },
    "reservedSize": {
        "size": 1.0,
        "unit": "GB"
    },
    "clusterProperties": {
        "lifs": [],
        "serialNumber": "",
        "systemId": "",
        "clusterName": "",
        "ontapVersion": "",
        "accountId": "",
        "productCode": "",
        "amiId": "",
        "systemManagerUrl": "",
        "creationTime": 0,
        "instanceId": "",
        "platformLicense": "",
        "licenseExpiryDate": 0,
        "instanceType": "",
        "publicIp": null,
        "publicDnsName": null,
        "licenseType": {
            "name": "",
            "capacityLimit": {
                "size": 0.0,
                "unit": "GB"
            }
        },
        "lastModifiedOffbox": null,
        "offboxTarget": false,
        "upgradeVersions": null,
        "writingSpeedState": null
    },
    "ontapClusterProperties": {
        "nodes": [
            {
                "name": "ShirleyHa2701-01",
                "lifs": [
                    {
                        "ip": "10.0.0.29",
                        "netmask": "255.255.255.0",
                        "lifType": "Cluster",
                        "dataProtocols": [],
                        "nodeName": "ShirleyHa2701-01",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.26",
                        "netmask": "255.255.255.0",
                        "lifType": "Node Management",
                        "dataProtocols": [],
                        "nodeName": "ShirleyHa2701-01",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.13",
                        "netmask": "255.255.255.0",
                        "lifType": "Cluster Management",
                        "dataProtocols": [],
                        "nodeName": "ShirleyHa2701-01",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.27",
                        "netmask": "255.255.255.0",
                        "lifType": "Intercluster",
                        "dataProtocols": [],
                        "nodeName": "ShirleyHa2701-01",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.14",
                        "netmask": "255.255.255.0",
                        "lifType": "Data",
                        "dataProtocols": [
                            "nfs",
                            "cifs"
                        ],
                        "nodeName": "ShirleyHa2701-01",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.28",
                        "netmask": "255.255.255.0",
                        "lifType": "Data",
                        "dataProtocols": [
                            "iscsi"
                        ],
                        "nodeName": "ShirleyHa2701-01",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.16",
                        "netmask": "255.255.255.0",
                        "lifType": "SVM Management",
                        "dataProtocols": [],
                        "nodeName": "ShirleyHa2701-01",
                        "privateIp": true
                    }
                ],
                "serialNumber": "0000000000000000",
                "systemId": "2315255834",
                "platformLicense": null,
                "platformSerialNumber": null,
                "cloudProviderId": "",
                "healthy": true,
                "inTakeover": false
            },
            {
                "name": "ShirleyHa2701-02",
                "lifs": [
                    {
                        "ip": "10.0.0.24",
                        "netmask": "255.255.255.0",
                        "lifType": "Cluster",
                        "dataProtocols": [],
                        "nodeName": "ShirleyHa2701-02",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.18",
                        "netmask": "255.255.255.0",
                        "lifType": "Node Management",
                        "dataProtocols": [],
                        "nodeName": "ShirleyHa2701-02",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.19",
                        "netmask": "255.255.255.0",
                        "lifType": "Intercluster",
                        "dataProtocols": [],
                        "nodeName": "ShirleyHa2701-02",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.15",
                        "netmask": "255.255.255.0",
                        "lifType": "Data",
                        "dataProtocols": [
                            "nfs",
                            "cifs"
                        ],
                        "nodeName": "ShirleyHa2701-02",
                        "privateIp": true
                    },
                    {
                        "ip": "10.0.0.20",
                        "netmask": "255.255.255.0",
                        "lifType": "Data",
                        "dataProtocols": [
                            "iscsi"
                        ],
                        "nodeName": "ShirleyHa2701-02",
                        "privateIp": true
                    }
                ],
                "serialNumber": "0000000000000000",
                "systemId": "2315255826",
                "platformLicense": null,
                "platformSerialNumber": null,
                "cloudProviderId": "",
                "healthy": true,
                "inTakeover": false
            }
        ],
        "clusterName": "ShirleyHa2701",
        "clusterUuid": "xxx000000e-xxx00-xxx00-xxx00-xxx00xxx00",
        "ontapVersion": "9.9.0X5",
        "systemManagerUrl": "https://10.0.0.13/sysmgr/SysMgr.html",
        "creationTime": 1611698774849,
        "licenseType": {
            "name": "Cloud Volumes ONTAP BYOL",
            "capacityLimit": {
                "size": 368.0,
                "unit": "TB"
            }
        },
        "lastModifiedOffbox": null,
        "offboxTarget": true,
        "upgradeVersions": null,
        "writingSpeedState": null,
        "broadcastDomainInfos": [
            {
                "broadcastDomain": "Cluster",
                "ipSpace": "Cluster",
                "mtu": 1500
            },
            {
                "broadcastDomain": "Default",
                "ipSpace": "Default",
                "mtu": 1500
            }
        ],
        "evaluation": false,
        "capacityTierInfo": {
            "capacityTierUsedSize": {
                "size": 0.0,
                "unit": "GB"
            },
            "s3BucketName": "qxtj1b4zpsieeen.blob.core.windows.net",
            "tierLevel": "normal"
        },
        "canConfigureCapacityTier": false,
        "usedCapacity": {
            "size": 9.863281247817213E-4,
            "unit": "TB"
        },
        "userName": "admin",
        "wormEnabled": false
    },
    "cloudProviderName": "Azure",
    "snapshotPolicies": [
        {
            "name": "default",
            "schedules": [
                {
                    "frequency": "hourly",
                    "retention": 6
                },
                {
                    "frequency": "daily",
                    "retention": 2
                },
                {
                    "frequency": "weekly",
                    "retention": 2
                }
            ],
            "description": "Default policy with hourly, daily & weekly schedules."
        },
        {
            "name": "default-1weekly",
            "schedules": [
                {
                    "frequency": "hourly",
                    "retention": 6
                },
                {
                    "frequency": "daily",
                    "retention": 2
                },
                {
                    "frequency": "weekly",
                    "retention": 1
                }
            ],
            "description": "Default policy with 6 hourly, 2 daily & 1 weekly schedule."
        },
        {
            "name": "none",
            "schedules": [],
            "description": "Policy for no automatic snapshots."
        }
    ],
    "actionsRequired": [
        {
            "actionType": "licenseGracePeriod",
            "parameters": {
                "aggregateName": "",
                "numOfDisks": 0,
                "diskSize": null,
                "volumeNames": null,
                "maxCapacity": null,
                "licenseExpiryDate": 1611698969000,
                "serialNumber": "000000000000000000",
                "volumeMoveParameters": null,
                "workingEnvironmentId": "",
                "licenseParameters": null,
                "resourcesToDelete": null,
                "instances": [],
                "moreInfo": null,
                "providerVolumeType": null,
                "volumeInfo": null,
                "currentInstanceType": null
            },
            "severity": "error"
        },
        {
            "actionType": "licenseGracePeriod",
            "parameters": {
                "aggregateName": "",
                "numOfDisks": 0,
                "diskSize": null,
                "volumeNames": null,
                "maxCapacity": null,
                "licenseExpiryDate": 1611699072000,
                "serialNumber": "000000000000000000000",
                "volumeMoveParameters": null,
                "workingEnvironmentId": "",
                "licenseParameters": null,
                "resourcesToDelete": null,
                "instances": [],
                "moreInfo": null,
                "providerVolumeType": null,
                "volumeInfo": null,
                "currentInstanceType": null
            },
            "severity": "error"
        }
    ],
    "activeActions": [],
    "replicationProperties": {
        "peers": [],
        "replicationTargets": []
    },
    "schedules": [
        {
            "name": "day",
            "schedule": [
                {
                    "stop": {
                        "day": 0,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 1,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 1,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 2,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 2,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 3,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 3,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 4,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 4,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 5,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 5,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 6,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 6,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 0,
                        "hour": 8,
                        "minute": 0
                    }
                }
            ],
            "enabled": false
        },
        {
            "name": "Weekend",
            "schedule": [
                {
                    "stop": {
                        "day": 6,
                        "hour": 8,
                        "minute": 0
                    },
                    "start": {
                        "day": 1,
                        "hour": 8,
                        "minute": 0
                    }
                }
            ],
            "enabled": false
        },
        {
            "name": "Weekdays",
            "schedule": [
                {
                    "stop": {
                        "day": 1,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 2,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 2,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 3,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 3,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 4,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 4,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 5,
                        "hour": 8,
                        "minute": 0
                    }
                },
                {
                    "stop": {
                        "day": 5,
                        "hour": 20,
                        "minute": 0
                    },
                    "start": {
                        "day": 6,
                        "hour": 8,
                        "minute": 0
                    }
                }
            ],
            "enabled": false
        }
    ],
    "svms": [
        {
            "name": "svm_ShirleyHa2701",
            "state": "running",
            "language": "c.utf_8",
            "allowedAggregates": [
                "aggr1"
            ],
            "ver3Enabled": true,
            "ver4Enabled": true
        }
    ],
    "workingEnvironmentType": "VSA",
    "supportRegistrationProperties": {
        "supportRegistrationStatus": "registered",
        "licenseExpiryDate": 1604102400000
    },
    "supportRegistrationInformation": [
        {
            "supportRegistrationStatus": "registered",
            "serialNumber": "00000000000000",
            "licenseExpiryDate": 1611698969000,
            "cloudLicenseExists": true,
            "nssAccountId": "x0x0x000-0000-0000x-00de-x000xxxx00000"
        },
        {
            "supportRegistrationStatus": "registered",
            "serialNumber": "0000000001111",
            "licenseExpiryDate": 1611699072000,
            "cloudLicenseExists": true,
            "nssAccountId": "x0x0x000-0000-0000x-00de-x000xxxx00000"
        }
    ],
    "capacityFeatures": {
        "providerVolumesType": [
            {
                "size": {
                    "size": 500.0,
                    "unit": "GB"
                },
                "supportedVolumeTypes": [
                    "Premium_LRS"
                ],
                "maxDisksAllow": {
                    "numOfDisks": 12,
                    "reason": null
                }
            },
            {
                "size": {
                    "size": 1.0,
                    "unit": "TB"
                },
                "supportedVolumeTypes": [
                    "Premium_LRS"
                ],
                "maxDisksAllow": {
                    "numOfDisks": 12,
                    "reason": null
                }
            },
            {
                "size": {
                    "size": 2.0,
                    "unit": "TB"
                },
                "supportedVolumeTypes": [
                    "Premium_LRS"
                ],
                "maxDisksAllow": {
                    "numOfDisks": 12,
                    "reason": null
                }
            },
            {
                "size": {
                    "size": 4.0,
                    "unit": "TB"
                },
                "supportedVolumeTypes": [
                    "Premium_LRS"
                ],
                "maxDisksAllow": {
                    "numOfDisks": 12,
                    "reason": null
                }
            },
            {
                "size": {
                    "size": 8.0,
                    "unit": "TB"
                },
                "supportedVolumeTypes": [
                    "Premium_LRS"
                ],
                "maxDisksAllow": {
                    "numOfDisks": 12,
                    "reason": null
                }
            }
        ],
        "defaultProviderVolumeType": {
            "size": {
                "size": 500.0,
                "unit": "GB"
            },
            "diskType": "Premium_LRS",
            "capacityTier": "Blob",
            "iops": null
        },
        "supportedCapacityTiers": {
            "supportedCapacityTiersPerVolumeType": [
                {
                    "volumeType": "Premium_LRS",
                    "supportedCapacityTiers": [
                        "Blob"
                    ],
                    "availableTieringPolicies": [
                        "none",
                        "snapshot_only",
                        "auto",
                        "all"
                    ]
                }
            ],
            "capacityTiersDisableReasons": [],
            "compositeSupported": true,
            "forceCompositeVersion": true
        },
        "maxDisksPerAggregate": 12,
        "existingIops": []
    },
    "encryptionProperties": {
        "ontapEncryption": false,
        "awsVolumeEncryption": false,
        "azureVolumeEncryption": true,
        "gcpVolumeEncryption": false,
        "keyManagers": [],
        "encryptionCertificates": [],
        "awsEncryptionKey": null
    },
    "supportedFeatures": {
        "supportsMixedAggregates": false,
        "supportsTieringWithServiceAccount": false
    },
    "isHA": true,
    "haProperties": {
        "loadBalancerName": "ShirleyHa2701-rg-lb",
        "node1Info": {
            "instanceName": "ShirleyHa2701-vm1",
            "instanceId": null,
            "primaryIp": "10.0.0.26",
            "state": "running",
            "serialNumber": "000000000000000",
            "availabilitySet": {
                "faultDomain": 0,
                "updateDomain": 0
            }
        },
        "node2Info": {
            "instanceName": "ShirleyHa2701-vm2",
            "instanceId": null,
            "primaryIp": "10.0.0.18",
            "state": "running",
            "serialNumber": "000000000000000000000000",
            "availabilitySet": {
                "faultDomain": 1,
                "updateDomain": 1
            }
        }
    },
    "k8sProperties": {
        "isConnected": false,
        "mainClusterIds": [],
        "connectedClusterIds": []
    },
    "fpolicyProperties": {
        "status": 0,
        "fPolicyProtocolStatus": {
            "nfsv3": 0,
            "nfsv4": 0,
            "cifs": -1
        },
        "fileExtensions": [
            "micro",
            "encrypted",
            "locked",
            "crypto",
            "crypt",
            "crinf",
            "r5a",
            "XRNT",
            "XTBL",
            "R16M01D05",
            "pzdc",
            "good",
            "LOL!",
            "OMG!",
            "RDM",
            "RRK",
            "encryptedRS",
            "crjoker",
            "EnCiPhErEd",
            "LeChiffre"
        ]
    },
    "saasProperties": {
        "subscription": null,
        "freeTrialExpiry": null,
        "saasEnabled": false
    },
    "cbsProperties": {
        "cbsBackupStatus": "off",
        "cbsRules": [],
        "numberOfBackedUpVolumes": 0,
        "objectStoreName": null,
        "providerSpecific": null,
        "cbsPolicyName": null,
        "usedCapacity": null,
        "ipSpace": null,
        "region": null,
        "providerAccountName": null,
        "exclusionReason": null
    },
    "complianceProperties": {
        "scanStatus": "SCAN_DISABLED",
        "complianceStatus": null,
        "lastDeploymentError": null,
        "complianceBackupStatus": null
    },
    "monitoringProperties": {
        "monitoringStatus": "MONITORING_DISABLED",
        "monitoringInfo": null,
        "tenantUrl": null
    }
}
