---
sidebar: sidebar
permalink: cm/wf_aws_ontap_get_aggrs.html
keywords: cloud, manager, rest, api, get aggregates
summary: 'You can retrieve a list of available disk aggregates.'
---

= Get aggregates
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can retrieve a list of available disk aggregates.

Choose the correct workflow depending on the type of Cloud Volumes ONTAP deployment:

* <<Get aggregates for single node, Single Node>>
* <<Get aggregates for high availability pair, HA pair>>

== Get aggregates for single node
You can use this workflow to retrieve the aggregates for a single node working environment.

=== 1. Select the working environment to use

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environments-for-single-node[Get working environments] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

=== 2. Get the list of aggregates

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/vsa/aggregates/{workingEnvironmentId}
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/vsa/aggregates/<WORKING_ENV_ID>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameter <WORKING_ENV_ID> `(workingEnvironmentId)`

Output::
An array of aggregates for the indicated working environment is returned as shown in the JSON output example.

JSON output example::
[source,json]
[
    {
        "name": "aggr1",
        "availableCapacity": {
            "size": 87.55,
            "unit": "GB"
        },
        "totalCapacity": {
            "size": 88.57,
            "unit": "GB"
        },
        "usedCapacity": {
            "size": 1.02,
            "unit": "GB"
        },
        "volumes": [
            {
                "name": "svm_ziv01we01_root",
                "totalSize": {
                    "size": 1.0,
                    "unit": "GB"
                },
                "usedSize": {
                    "size": 0.00115203857421875,
                    "unit": "GB"
                },
                "thinProvisioned": false,
                "isClone": false,
                "rootVolume": true
            }
        ],
        "providerVolumes": [
            {
                "id": "vol-066fea889cbc6a65c",
                "name": "vol-066fea889cbc6a65c",
                "size": {
                    "size": 100.0,
                    "unit": "GB"
                },
                "state": "in-use",
                "device": "/dev/xvdg",
                "instanceId": "i-0fa9a2879e67a8829",
                "diskType": "gp2",
                "encrypted": true,
                "iops": null
            }
        ],
        "disks": [
            {
                "name": "NET-1.3",
                "position": "data",
                "ownerNode": "ziv01we01-01",
                "device": "xvdg vol066fea889cbc6a65c",
                "vmDiskProperties": null
            }
        ],
        "state": "online",
        "encryptionType": "cloudEncrypted",
        "encryptionKeyId": null,
        "isRoot": false,
        "homeNode": "ziv01we01-01",
        "ownerNode": "ziv01we01-01",
        "capacityTier": null,
        "capacityTierUsed": null,
        "sidlEnabled": true,
        "snaplockType": "non_snaplock"
    }
]

== Get aggregates for high availability pair
You can use this workflow to retrieve the aggregates for an HA working environment.

=== 1. Select the working environment to use

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environments] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

=== 2. Get the list of aggregates

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/aws/ha/aggregates/{workingEnvironmentId}
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/aws/ha/aggregates/<WORKING_ENV_ID>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameter <WORKING_ENV_ID> `(workingEnvironmentId)`

Output::
An array of aggregates for the indicated working environment is returned as shown in the JSON output example.

JSON output example::
[source,json]
[
    {
        "name": "aggr1",
        "availableCapacity": {
            "size": 83.13,
            "unit": "GB"
        },
        "totalCapacity": {
            "size": 84.14,
            "unit": "GB"
        },
        "usedCapacity": {
            "size": 1.02,
            "unit": "GB"
        },
        "volumes": [
            {
                "name": "svm_ziv04we01ha_root",
                "totalSize": {
                    "size": 1.0,
                    "unit": "GB"
                },
                "usedSize": {
                    "size": 7.0953369140625E-4,
                    "unit": "GB"
                },
                "thinProvisioned": false,
                "isClone": false,
                "rootVolume": true
            }
        ],
        "providerVolumes": [
            {
                "id": "vol-0d5d1983432218cec",
                "name": "vol-0d5d1983432218cec",
                "size": {
                    "size": 100.0,
                    "unit": "GB"
                },
                "state": "in-use",
                "device": "/dev/xvdh",
                "instanceId": "i-053d9d1bce8121c43",
                "diskType": "gp2",
                "encrypted": true,
                "iops": null
            },
            {
                "id": "vol-0a3fe8eaed2af69de",
                "name": "vol-0a3fe8eaed2af69de",
                "size": {
                    "size": 100.0,
                    "unit": "GB"
                },
                "state": "in-use",
                "device": "/dev/xvdh",
                "instanceId": "i-0392f55ca4bc06322",
                "diskType": "gp2",
                "encrypted": true,
                "iops": null
            }
        ],
        "disks": [
            {
                "name": "NET-1.4",
                "position": "data",
                "ownerNode": "ziv04we01ha-01",
                "device": "xvdh vol0d5d1983432218cec",
                "vmDiskProperties": null
            },
            {
                "name": "NET-2.4",
                "position": "data",
                "ownerNode": "ziv04we01ha-01",
                "device": "xvdh vol0a3fe8eaed2af69de",
                "vmDiskProperties": null
            }
        ],
        "state": "online",
        "encryptionType": "cloudEncrypted",
        "encryptionKeyId": null,
        "isRoot": false,
        "homeNode": "ziv04we01ha-01",
        "ownerNode": "ziv04we01ha-01",
        "capacityTier": null,
        "capacityTierUsed": null,
        "sidlEnabled": true,
        "snaplockType": "non_snaplock"
    },
    {
        "name": "ziv04we01haagg01",
        "availableCapacity": {
            "size": 84.14,
            "unit": "GB"
        },
        "totalCapacity": {
            "size": 84.14,
            "unit": "GB"
        },
        "usedCapacity": {
            "size": 156.0,
            "unit": "KB"
        },
        "volumes": [],
        "providerVolumes": [
            {
                "id": "vol-0149ffa06bb4e92ad",
                "name": "vol-0149ffa06bb4e92ad",
                "size": {
                    "size": 100.0,
                    "unit": "GB"
                },
                "state": "in-use",
                "device": "/dev/xvdi",
                "instanceId": "i-0392f55ca4bc06322",
                "diskType": "gp2",
                "encrypted": true,
                "iops": null
            },
            {
                "id": "vol-03e6ada9e893b1196",
                "name": "vol-03e6ada9e893b1196",
                "size": {
                    "size": 100.0,
                    "unit": "GB"
                },
                "state": "in-use",
                "device": "/dev/xvdi",
                "instanceId": "i-053d9d1bce8121c43",
                "diskType": "gp2",
                "encrypted": true,
                "iops": null
            }
        ],
        "disks": [
            {
                "name": "NET-2.5",
                "position": "data",
                "ownerNode": "ziv04we01ha-01",
                "device": "xvdi vol0149ffa06bb4e92ad",
                "vmDiskProperties": null
            },
            {
                "name": "NET-1.5",
                "position": "data",
                "ownerNode": "ziv04we01ha-01",
                "device": "xvdi vol03e6ada9e893b1196",
                "vmDiskProperties": null
            }
        ],
        "state": "online",
        "encryptionType": "cloudEncrypted",
        "encryptionKeyId": null,
        "isRoot": false,
        "homeNode": "ziv04we01ha-01",
        "ownerNode": "ziv04we01ha-01",
        "capacityTier": null,
        "capacityTierUsed": null,
        "sidlEnabled": true,
        "snaplockType": "non_snaplock"
    }
]
