---
sidebar: sidebar
permalink: cm/wf_aws_ontap_create_quote.html
keywords: cloud, manager, rest, api, aggregate, volume quote
summary: 'You can create a quote for a new volume which returns a resource quote needed to satisfy the request.'
---

= Create quote
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a quote for a new volume which returns a resource quote needed to satisfy the request. The resource quote contains aggregate information where the volume will be created and confirms if the space is available. This is a recommended step but is not mandatory.

=== 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html[Get working environments] and choose the `publicId` value for the working environment and `svmName`.

=== 2. Select the aggregate

Perform the workflow link:wf_aws_ontap_get_aggrs.html[Get aggregates] and choose the `name` value.

=== 3. Select the permutations configuration

Perform the workflow link:wf_aws_cloud_md_get_permutations.html[Get permutations] and choose the `size` and `diskType` values for step 4.

=== 4. Generate the volume quote

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/vsa/quote
|===

curl example::
[source,curl]
curl --location --request POST 'https://cloudmanager.cloud.netapp.com/occm/api/vsa/volumes/quote' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID> --header 'Authorization: Bearer <ACCESS_TOKEN>' --d @JSONinput

Input::

The JSON input example includes the list of input parameters.

JSON input example::
[source,json]
{
  "workingEnvironmentId": "VsaWorkingEnvironment-5dZfyKS5",
  "svmName": "svm_ziv01we01",
  "aggregateName": "ziv01agg01",
  "name": "ziv1vol02",
  "size": {
    "size": "100",
    "unit": "GB"
  },
  "enableThinProvisioning": "true",
  "providerVolumeType": "gp2",
  "verifyNameUniqueness": "true"
}

Output::

The JSON output example includes an example of the quote details.

JSON output example
[source,json]
{
    "numOfDisks": 0,
    "diskSize": {
        "size": 100.0,
        "unit": "GB"
    },
    "aggregateName": "ziv01agg01",
    "newAggregate": false,
    "autoVsaCapacityManagement": true
}
