---
sidebar: sidebar
permalink: cm/wf_azure_ontap_create_vol_nfs.html
keywords: cloud, manager, rest, api, aggregate, svm, virtual, private, cloud
summary: 'You can use this workflow to create a volume accessed through NFS.'
---

= Create a volume using NFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to create a volume accessed through the NFS protocol.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Create a volume using NFS for single node, Single Node>>
* <<Create a volume using NFS for high availability pair, HA pair>>

== Create a volume using NFS for single node
You can use this workflow to create a volume using NFS protocol for a single node working environment.

=== 1. Select a working environment

Perform the workflow link:wf_azure_cloud_create_we_paygo.html#create-working-environment-for-single-node[Create working environments] and choose the `publicId` value for the `workingEnvironmentId` parameter in the JSON input. From the `capacityFeatures` field in the response, choose the value of `Blob` for the `capacityTier` parameter.

=== 2. Select the rules

Choose values for the `exportPolicyInfo->rules->ruleAccessControl` and `exportPolicyInfo->rules->superUser` parameters.

=== 3. Select the aggregate

Perform the workflow link:wf_azure_ontap_get_aggrs.html[Get aggregates]. From the `providerVolumes` field in the response, you must also choose the value of the `providerVolumeType` parameter, the value of `null` for the `iops` parameter, and the value of `null` for the `throughput` parameter.

=== 3. Create a volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/azure/vsa/volumes
|===

curl example::
[source,curl]
curl --location --request POST 'https://api.bluexp.netapp.com/occm/api/azure/vsa/volumes?createAggregateIfNotFound=true' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --d @JSONinput

Input::

The JSON input example includes the minimum list of input parameters.

JSON input example::
[source,json]
   {
  "workingEnvironmentId": "vsaworkingenvironment-sfrf3wvj",
  "svmName": "svm_zivgcp01we02",
  "aggregateName": "ziv01agg01",
  "name": "zivagg01vol01",
  "size": {
    "size": 100,
    "unit": "GB"
  },
  "snapshotPolicyName": "default",
  "exportPolicyInfo": { 
  "policyType": "custom", 
    "rules": [ 
        { 
            "index": 1, 
            "ruleAccessControl": "readwrite", 
            "ips": [ 
                "0.0.0.0/0" 
            ], 
            "nfsVersion": [ 
                "nfs3", 
                "nfs4" 
            ], 
            "superUser": true 
        } 
    ] 
}, 
"enableThinProvisioning": true, 
"enableCompression": true, 
"enableDeduplication": true, 
"maxNumOfDisksApprovedToAdd": 0, 
"evCapacityApprovedToAdd": null, 
"verifyNameUniqueness": true, 
"providerVolumeType": "Premium_LRS", 
"iops": null, 
"throughput": null, 
"capacityTier": "Blob", 
"tieringPolicy": "auto", 
"minimumCoolingDays": 31 
} 

Output::

None

== Create a volume using NFS for high availability pair

You can use this workflow to create a volume using NFS protocol for an HA working environment.

=== 1. Select a working environment

Perform the workflow link:wf_azure_cloud_create_we_paygo.html#create-working-environment-for-high-availability-pair[Create working environments] and choose the `publicId` value for the `workingEnvironmentId` parameter in the JSON input. From the `capacityFeatures` field in the response, choose the value of `Blob` for the `capacityTier` parameter.

=== 2. Select rules

Choose values for the `exportPolicyInfo->rules->ruleAccessControl` and `exportPolicyInfo->rules->superUser` parameters.

=== 3. Select the aggregate

Perform the workflow link:wf_azure_ontap_get_aggrs.html[Get aggregates]. From the `providerVolumes` field in the response, you must also choose the value of the `providerVolumeType` parameter, the value of `null` for the `iops` parameter, and the value of `null` for the `throughput` parameter.

=== 3. Create a volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/azure/ha/volumes
|===

curl example::
[source,curl]
curl --location --request POST 'https://api.bluexp.netapp.com/occm/api/azure/ha/volumes?createAggregateIfNotFound=false' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --d @JSONinput

Input::

The JSON input example includes the minimum list of input parameters.

JSON input example::
[source,json]
 "workingEnvironmentId": "vsaworkingenvironment-sfrf3wvj",
  "svmName": "svm_zivgcp01we02",
  "aggregateName": "ziv01agg01",
  "name": "zivagg01vol01",
  "size": {
    "size": 100,
    "unit": "GB"
  },
  "snapshotPolicyName": "default",
  "exportPolicyInfo": { 
    "policyType": "custom", 
    "rules": [ 
        { 
            "index": 1, 
            "ruleAccessControl": "readwrite", 
            "ips": [ 
                "0.0.0.0/0" 
            ], 
            "nfsVersion": [ 
                "nfs3", 
                "nfs4" 
            ], 
            "superUser": true 
        } 
    ] 
}, 
"enableThinProvisioning": true, 
"enableCompression": true, 
"enableDeduplication": true, 
"maxNumOfDisksApprovedToAdd": 0, 
"evCapacityApprovedToAdd": null, 
"verifyNameUniqueness": true, 
"providerVolumeType": "Premium_LRS", 
"iops": null, 
"throughput": null, 
"capacityTier": "Blob", 
"tieringPolicy": "auto", 
"minimumCoolingDays": 31 
} 

Output::

None
