---
sidebar: sidebar
permalink: cm/wf_azure_ontap_create_vol_cifs.html
keywords: vcloud, manager, rest, api
summary: 'You can use this workflow to create a volume accessed through CIFS.'
---

= Create a volume using CIFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to create a volume accessed through CIFS protocol.

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Create volume using CIFS for single node, Single Node>>
* <<Create volume using CIFS for high availability pair, HA pair>>

== Create volume using CIFS for single node
You can use this workflow to create a volume using CIFS protocol for a single node working environment.

=== 1. Choose the CIFS configuration

A CIFS server configuration must be defined for your working environment. You can do one of the following:

* If a CIFS configuration already exists, perform the workflow link:wf_azure_ontap_get_cifs.html#get-cifs-server-configuration-for-single-node[Get CIFS server configurations] to access the configuration parameters.
* If a CIFS configuration does not exist, perform the workflow link:wf_azure_ontap_create_cifs.html#create-cifs-server-configuration-for-single-node[Create CIFS server configuration] to create one.

=== 2. Select the working environment

Perform the workflow link:wf_azure_ontap_get_cifs.html#get-cifs-server-configuration-for-single-node[Get working environments] and choose the `publicId` value for the `workingEnvironmentId` (working environment) and the `svmName` (SVM name). From the `capacityFeatures` field in the response, choose the value of `Blob` for the `capacityTier` parameter.

=== 3. Select the aggregate

Perform the workflow link:wf_azure_ontap_get_aggrs.html#get-aggregates-for-single-node[Get aggregates] and choose the `name` for the `aggregateName` value. From the `providerVolumes` field in the response, you must also choose the value of the `providerVolumeType` parameter, the value of `null` for the `iops` parameter, and the value of `null` for the `throughput` parameter.

[NOTE]
If aggregate name does not exist and the `createAggregateIfNotFound` query parameter is set `true`, the create volume request is allowed if the named aggregate is not found.

=== 4. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.

=== 5. Create the quote

Perform the workflow link:wf_azure_ontap_create_quote.html#create-quote-for-a-single-node[Create quote]. This is a recommended step but is not mandatory.

=== 6. Create the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/azure/vsa/volumes
|===

curl example::
[source,curl]
curl --location --request POST 'https://api.bluexp.netapp.com/occm/api/azure/vsa/volumes?createAggregateIfNotFound=true' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --d @JSONinput

Input::

The JSON input example includes the minimum list of input parameters, including:

* <WORKING_ENV_ID> `(workingEnvironmentId)` string
* <SVM_NAME> `(svmName)` string
* <AGGR_NAME> `(aggregateName)` string

If an aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

JSON input example::
[source,json]
{
  "workingEnvironmentId": "VsaWorkingEnvironment-4b3YXODB",
  "svmName": "svm_name",
  "aggregateName": "aggr1",
  "name": "volume_cifs",
  "size": {
    "size": 1,
    "unit": "GB"
 },
    "snapshotPolicyName": "default",
     "shareInfo": {
        "shareName": "volume_cifs_share",
        "accessControl": {
            "permission": "full_control",
            "users": [
                "Everyone"
            ]
        }
    },
  "enableThinProvisioning": true,
  "enableCompression": true,
  "enableDeduplication": true,
  "maxNumOfDisksApprovedToAdd": 0
  "evCapacityApprovedToAdd": null, 
  "verifyNameUniqueness": true, 
  "providerVolumeType": "StandardSSD_LRS", 
  "iops": null, 
  "throughput": null, 
  "capacityTier": "Blob", 
  "tieringPolicy": "auto", 
  "minimumCoolingDays": 31 
  } 



Output::

None

== Create volume using CIFS for high availability pair
You can use this workflow to create a volume using CIFS protocol for an HA working environment.

=== 1. Choose the CIFS configuration

A CIFS server configuration must be defined for your working environment. You can do one of the following:

* If a CIFS configuration already exists, perform the workflow link:wf_azure_ontap_get_cifs.html#get-cifs-server-configuration-for-high-availability-pair[Get CIFS server configurations] to access the configuration parameters.
* If a CIFS configuration does not exist, perform the workflow link:wf_azure_ontap_create_cifs.html#create-cifs-server-configuration-for-high-availability-pair[Create CIFS server configuration] to create one.

=== 2. Select the working environment

Perform the workflow link:wf_azure_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environments] and choose the `publicId` value for the `workingEnvironmentId` (working environment) and the `svmName` (SVM name). From the `capacityFeatures` field in the response, choose the value of `Blob` for the `capacityTier` parameter.

=== 3. Select the aggregate

Perform the workflow link:wf_azure_ontap_get_aggrs.html#get-aggregates-for-high-availability-pair[Get aggregates] and choose the `name` for the `aggregateName` value. From the `providerVolumes` field in the response, you must also choose the value of the `providerVolumeType` parameter, the value of `null` for the `iops` parameter, and the value of `null` for the `throughput` parameter.

[NOTE]
If aggregate name does not exist and the `createAggregateIfNotFound` query parameter is set `true`, the create volume request is allowed if the named aggregate is not found.

=== 4. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `byte`.

=== 5. Create the quote

Perform the workflow link:wf_azure_ontap_create_quote.html#create-quote-for-high-availability-pair[Create quote]. This is a recommended step but is not mandatory.

=== 6. Create the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/azure/ha/volumes
|===

curl example::
[source,curl]
curl --location --request POST 'https://api.bluexp.netapp.com/occm/api/azure/ha/volumes?createAggregateIfNotFound=true' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --d @JSONinput

Input::

The JSON input example includes the minimum list of input parameters, including:

* <WORKING_ENV_ID> `(workingEnvironmentId)` string
* <SVM_NAME> `(svmName)` string
* <AGGR_NAME> `(aggregateName)` string

If an aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

JSON input example::
[source,json]
[source,json]
{
  "workingEnvironmentId": "VsaWorkingEnvironment-4b3YXODB",
  "svmName": "svm_name",
  "aggregateName": "aggr1",
  "name": "volume_ha_cifs",
  "size": {
    "size": 1,
    "unit": "GB"
 },
    "snapshotPolicyName": "default",
     "shareInfo": {
        "shareName": "volume_cifs_share",
        "accessControl": {
            "permission": "full_control",
            "users": [
                "Everyone"
            ]
        }
    },
  "enableThinProvisioning": true,
  "enableCompression": true,
  "enableDeduplication": true,
  "maxNumOfDisksApprovedToAdd": 0
  "evCapacityApprovedToAdd": null, 
  "verifyNameUniqueness": true, 
  "providerVolumeType": "Premium_LRS", 
  "iops": null, 
  "throughput": null, 
  "capacityTier": "Blob", 
  "tieringPolicy": "auto", 
  "minimumCoolingDays": 31 
  } 

Output::

None
