---
sidebar: sidebar
permalink: cm/wf_azure_cloud_create_we_paygo.html
keywords: paygo, cloud, volumes, ontap, connector, cloud manager, region, workspace
summary: 'You can use this workflow to create a new Cloud Volumes ONTAP working environment using PAYGO ("pay as you go") licensing. A new volume is also created with the working environment.'
---

= Create a working environment with PAYGO licensing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to create a new Azure Cloud Volumes ONTAP working environment using pay-as-you-go (PAYGO) licensing.


=====
*Note the following when using PAYGO licensing*:

* A marketplace subscription is required.
* A NetApp Support Site (NSS) key is recommended to register the system for support, but it's not required.
//* A new volume can also be created with this working environment.
* You can add more volumes after creating the working environment. You can choose to create a volume using either link:wf_azure_ontap_create_vol_nfs.html[NFS], link:wf_azure_ontap_create_vol_cifs.html[CIFS], or link:wf_azure_ontap_create_vol_iscsi.html[iSCSI] protocol.
=====

=== 1. Select the region

Perform the workflow link:wf_azure_cloud_md_get_regions.html[Get regions] and choose the `name` value of the required region for the `region` parameter in step 11.

=== 2. Select the workspace

Perform the workflow link:wf_common_identity_get_tenants.html[Get tenants] and choose the `workspacePublicId` value for the `tenantId` parameter in step 11.

=== 3. Select the VNets

Perform the workflow link:wf_azure_cloud_md_get_vnets.html[Get VNets] and do the following:

* Choose the `id` value of the desired vnet from the `virtualNetworks` for the `vnetId` parameter in step 11.
*	Choose the `cidr` value of the desired cidr from the `virtualNetworks` for the `cidr` parameter in step 11.
* Choose the `id` of the desired subnet from the `virtualNetworks`-> `cidrs`-> `subnets` for the `subnetId` parameter in step 11.
*	Choose the `id` of the desired security group from the `securityGroups` field for the `securityGroupId` parameter in step 11.


=== 4. Select the Azure availability zone

Perform the workflow link:wf_azure_cloud_md_get_availability_zones.html[Get Azure Availability Zones] and choose the number from `zones` for the `availabilityZone` parameter in step 11.

=== 5. Get Azure packages configuration

Perform the link:wf_azure_cloud_md_get_packages.html[Get Azure Packages] workflow and choose the `name` of the desired package item for the `packageName` parameter.

=== 6. Attach a marketplace subscription

Perform the workflow link:wf_common_occm_attach_subscription.html[Attach SaaS subscription].

=== 7. (Optional) Obtain an NSS key

An NSS key is *optional* when using PAYGO licensing. If needed, you can create a key or select an existing key, and include the NSS key in the `nssAccount` parameter in step 11.

* To create a new NSS key using the Cloud Manager web user interface, perform the task link:get_nss_key.html[Add NSS credentials key] and choose the `id`.

* To select an existing NSS key, perform the workflow link:wf_common_identity_get_nss_keys.html[Get NSS keys] and choose the `id` of the required NSS user.

=== 8. Select Azure cloud provider accounts

Perform the link:wf_azure_cloud_md_create_account.html[Create Azure Cloud Provider Accounts] workflow and choose the `publicId` of the desired cloud provider account item from the `azureAccounts` for the `cloudProviderAccount` parameter.

=== 9. Select Azure permutations

Perform the link:wf_azure_cloud_md_get_permutations.html[Get Azure Permutations] workflow and pick the desired permutation:

*	Choose the `ontapVersion` of the desired permutation for the `ontapVersion` field inside the `vsaMetadata` parameter  in step 11.
*	Choose the `type` of the desired license item from the  `license` parameter for the `licenseType` field inside the `vsaMetadata` parameter in step 11.
*	Choose the `instanceType` of the desired permutation for the `instanceType` field inside the `vsaMetadata` parameter in step 11.

=== 10. Select Azure storage account types

Perform the link:wf_azure_cloud_md_get_storage_account_types.html[Get Azure Storage Account Types] workflow and pick the desired storage type.

*	Choose the `diskType` of the desired storage type item for the `storageType` parameter in step 11.
*	Choose the `size` of the desired disk size from the `sizes` -> `size` field for the `size` field inside the `diskSize` parameter in step 11.
*	Choose the `unit` of the desired disk size from the `sizes` -> `size` field for the `unit` field inside the `diskSize` parameter in step 11.

=== 11. Create the working environment

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/azure/vsa/working-environments
|===

curl example::
[source,curl]
----
curl --location --request POST 'https://cloudmanager.cloud.netapp.com/occm/api/azure/vsa/working-environments' --header 'x-agent-id: <AGENT_ID>' //<1> --header 'Authorization: Bearer <ACCESS_TOKEN>' //<2> ---header 'Content-Type: application/json' --d @JSONinput
----
(1) Replace <AGENT_ID> with your agent ID.
(2) Replace <ACCESS_TOKEN> with your obtained access bearer token.


Input::

The JSON input example includes the minimum list of parameters.

[NOTE]
This request uses PAYGO licensing as indicated in the `licenseType` parameter.

JSON input example::
[source,json]
{
	 "name":"cvsaws",
	 "tenantId":"tenantID",
	 "region":"westeurope",
	 "packageName":"azure_poc",
	 "dataEncryptionType":"AZURE",
	 "vsaMetadata":{
		 "ontapVersion":"ONTAP-9.10.0.T1.azure",
		 "licenseType":"azure-cot-explore-paygo",
		 "instanceType":"Standard_DS3_v2"
	},
	 "writingSpeedState":"NORMAL",
	 "subnetId":"/subscriptions/d333af45-0d07-4154-943d-c25fbbce1b18/resourceGroups/occm_group_westeurope/providers/Microsoft.Network/virtualNetworks/Vnet1/subnets/Subnet2",
	 "svmPassword":"Netapp123",
	 "vnetId":"/subscriptions/d333af45-0d07-4154-943d-c25fbbce1b18/resourceGroups/occm_group_westeurope/providers/Microsoft.Network/virtualNetworks/Vnet1",
	 "cidr":"10.0.0.0/16",
	 "ontapEncryptionParameters":null,
	 "securityGroupId":"/subscriptions/d333af45-0d07-4154-943d-c25fbbce1b18/resourceGroups/Cloud-Compliance-1nThiJkG05ZgcyucIJvCSbtBdpVnK-20210916092111/providers/Microsoft.Network/networkSecurityGroups/Cloud-Compliance-1nThiJkG05ZgcyucIJvCSbtBdpVnK-20210916092111",
	 "skipSnapshots":false,
	 "diskSize":{
		 "size":500,
		 "unit":"GB",
		 "_identifier":"500 GB"
	},
	 "storageType":"Premium_LRS",
	 "azureTags":[],
	 "subscriptionId":"d333af45-0d07-4154-943d-c25fbbce1b18",
	 "cloudProviderAccount":"ManagedServiceIdentity",
	 "backupVolumesToCbs":false,
	 "enableCompliance":false,
	 "enableMonitoring":false,
	 "availabilityZone":1,
	 "allowDeployInExistingRg":true,
	 "resourceGroup":"occm_group_westeurope"
}


Output::

The JSON output example includes an example of the `VsaWorkingEnvironmentResponse`.

JSON output example::
[source,json]
{
    "publicId": "VsaWorkingEnvironment-uFPaNkrv",
    "name": "Azure123",
    "tenantId": "tenantID",
    "svmName": "svm_Azure123",
    "creatorUserEmail": "user_mail",
    "status": null,
    "providerProperties": null,
    "reservedSize": null,
    "clusterProperties": null,
    "ontapClusterProperties": null,
    "cloudProviderName": "Azure",
    "snapshotPolicies": null,
    "actionsRequired": null,
    "activeActions": null,
    "replicationProperties": null,
    "schedules": null,
    "svms": null,
    "workingEnvironmentType": "VSA",
    "supportRegistrationProperties": null,
    "supportRegistrationInformation": null,
    "capacityFeatures": null,
    "encryptionProperties": null,
    "supportedFeatures": null,
    "isHA": false,
    "haProperties": null,
    "k8sProperties": null,
    "fpolicyProperties": null,
    "saasProperties": null,
    "cbsProperties": null,
    "complianceProperties": null,
    "monitoringProperties": null
}
