---
sidebar: sidebar
permalink: cm/wf_azure_before.html
keywords: azure, workflows, cloud, manager, rest, api
summary: There are several workflows you can use with the Azure public cloud.
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several workflows you can use with the Azure public cloud.

[NOTE]
Review the link:getting_started.html[Get started] section before using any of the Cloud Manager REST API workflows.

== Workflow categories
The Azure workflows are organized into the following functional categories:

Working environments::
Perform these workflows under this category to manage a working environment created based on your preferred licensing instance (PAYGO or BYOL). In addition, you can manipulate the server configuration (required for CIFS server) if you want to create volumes using the CIFS protocol.

Aggregates::
Perform these workflows to manage the ONTAP aggregates. You can create an aggregate, delete an aggregate, add disks to an aggregate, and retrieve existing aggregates based on your requirement.

Volumes::
Perform these workflows to manage the volumes based on your storage requirements. You can add a volume (using NFS, CIFS or ISCSI protocol), delete a volume, retrieve an existing volume, and more.

Metadata::
Perform these workflows to retrieve basic configuration information of your cloud providers.

Miscellaneous::
Perform this workflow to create a cloud provider account by specifying the cloud provider type.

Review the link:workflow_processes.html[Understanding the workflow processes] page to know more about the organizational structure of the workflows before creating and deploying them in a cloud environment.

== Azure subscription
Before beginning to use the Azure workflows, you'll need to create an Azure account through the Microsoft Azure portal and obtain a subscription ID.

== Connector setup

You must have a *Connector* for the cloud environment before creating a working environment and performing other activities using the workflows. You can create a Connector using the Cloud Manager web UI. When you create a Connector, Cloud Manager adds the Azure cloud provider account that you deployed the Connector in to your list of available accounts. Your Azure account needs to have the right permissions in order to create a Connector.

Review https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html[Learn about Azure Connectors] to know how to create and deploy an Azure Connector.
