---
sidebar: sidebar
permalink: wf_aws_cloud_md_get_vpcs.html
keywords: aws, workflows, virtual, private, cloud,
summary: You can use this workflow to retrieve a list of the available virtual private clouds.
---

= Get list of virtual private clouds
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to retrieve a list of the available virtual private clouds (VPCs).

Choose the correct workflow depending on the type of Cloud Volumes ONTAP deployment:

* <<Get VPCs for single node, Single Node>>
* <<Get VPCs for high availability pair, HA pair>>

== Get VPCs for single node
You can use this workflow to get VPCs for a single node working environment.

=== 1. Select the region to use

Perform the workflow link:wf_aws_cloud_md_get_regions.html[Get regions] and choose the `code` value for the region.

=== 2. Get the VPCs

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/vsa/metadata/vpcs?region=us-east-1
|===

Curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/vsa/metadata/vpcs?region=us-east-1' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Query parameters:

* `region`

Output::

The JSON output example includes the list of virtual private clouds.

JSON output example::
[source,json]
[
    {
        "vpcId": "vpc-b16c90d4",
        "state": "available",
        "cidrBlock": "172.31.0.0/16",
        "tags": [
            {
                "key": "Name",
                "value": "VPC for VSA"
            },
            {
                "key": "last",
                "value": "ioio"
            }
        ],
        "default": true,
        "subnets": [
            {
                "subnetId": "subnet-c1d99699",
                "cidr": "172.31.5.0/24",
                "subnetName": "subnet5",
                "availabilityZone": "us-east-1a",
                "availableIps": 247,
                "minimumRequiredIps": 8,
                "outpostArn": null
            },
            {
                "subnetId": "subnet-deebdbe3",
                "cidr": "172.31.6.0/24",
                "subnetName": "Proxy Subnet",
                "availabilityZone": "us-east-1e",
                "availableIps": 248,
                "minimumRequiredIps": 8,
                "outpostArn": null
            }
        ],
        "securityGroups": [
            {
                "securityGroupId": "sg-000a2be93c8668b1b",
                "description": "NetApp OCCM Instance External Security Group",
                "name": "lilush2000OCCM1590415972561-OCCMSecurityGroup-JDB72N6W90UG"
            },
            {
                "securityGroupId": "sg-0017cf49544fbb31e",
                "description": "Enable HTTP and NFS for Cloud Restore Instance",
                "name": "Cloud-Restore-Instance-account-TgPvchSk-CloudRestoreInstanceSecurityGroup-ZH4GN8E8AU1K"
            }
        ],
        "tenancy": "default"
    },
    {
        "vpcId": "vpc-fe5c1f98",
        "state": "available",
        "cidrBlock": "140.30.0.0/16",
        "tags": [
            {
                "key": "Name",
                "value": "VPCWIthNOS3"
            }
        ],
        "default": false,
        "subnets": [
            {
                "subnetId": "subnet-e84722d4",
                "cidr": "140.30.5.0/24",
                "subnetName": "subnet1",
                "availabilityZone": "us-east-1e",
                "availableIps": 250,
                "minimumRequiredIps": 8,
                "outpostArn": null
            }
        ],
        "securityGroups": [
            {
                "securityGroupId": "sg-0ccb5855f56acd419",
                "description": "ONTAP Cloud firewall rules for management and data interface",
                "name": "SG-Version10-duahpJbS-NetAppExternalSecurityGroup-EB0BZTI536LE"
            },
            {
                "securityGroupId": "sg-1911fa66",
                "description": "default VPC security group",
                "name": "default"
            }
        ],
        "tenancy": "default"
    }
]

== Get VPCs for high availability pair
You can use this workflow to get VPCs for an HA working environment.

=== 1. Select the region to use

Perform the workflow link:wf_aws_cloud_md_get_regions.html[Get regions] and choose the `code` value for the region.

=== 2. Get the VPCs

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/aws/ha/metadata/vpcs?region=us-east-1
|===

Curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/aws/ha/metadata/vpcs?region=us-east-1' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Query parameters:

* `region`

Output::

The JSON output example includes the list of virtual private clouds.

JSON output example::
[source,json]
[
    {
        "vpcId": "vpc-b16c90d4",
        "state": "available",
        "cidrBlock": "172.31.0.0/16",
        "tags": [
            {
                "key": "Name",
                "value": "VPC for VSA"
            },
            {
                "key": "last",
                "value": "ioio"
            }
        ],
        "default": true,
        "subnets": [
            {
                "subnetId": "subnet-c1d99699",
                "cidr": "172.31.5.0/24",
                "subnetName": "subnet5",
                "availabilityZone": "us-east-1a",
                "availableIps": 247,
                "minimumRequiredIps": 8,
                "outpostArn": null
            },
            {
                "subnetId": "subnet-deebdbe3",
                "cidr": "172.31.6.0/24",
                "subnetName": "Proxy Subnet",
                "availabilityZone": "us-east-1e",
                "availableIps": 248,
                "minimumRequiredIps": 8,
                "outpostArn": null
            }
        ],
        "securityGroups": [
            {
                "securityGroupId": "sg-000a2be93c8668b1b",
                "description": "NetApp OCCM Instance External Security Group",
                "name": "lilush2000OCCM1590415972561-OCCMSecurityGroup-JDB72N6W90UG"
            },
            {
                "securityGroupId": "sg-0017cf49544fbb31e",
                "description": "Enable HTTP and NFS for Cloud Restore Instance",
                "name": "Cloud-Restore-Instance-account-TgPvchSk-CloudRestoreInstanceSecurityGroup-ZH4GN8E8AU1K"
            }
        ],
        "tenancy": "default"
    },
    {
        "vpcId": "vpc-fe5c1f98",
        "state": "available",
        "cidrBlock": "140.30.0.0/16",
        "tags": [
            {
                "key": "Name",
                "value": "VPCWIthNOS3"
            }
        ],
        "default": false,
        "subnets": [
            {
                "subnetId": "subnet-e84722d4",
                "cidr": "140.30.5.0/24",
                "subnetName": "subnet1",
                "availabilityZone": "us-east-1e",
                "availableIps": 250,
                "minimumRequiredIps": 8,
                "outpostArn": null
            }
        ],
        "securityGroups": [
            {
                "securityGroupId": "sg-0ccb5855f56acd419",
                "description": "ONTAP Cloud firewall rules for management and data interface",
                "name": "SG-Version10-duahpJbS-NetAppExternalSecurityGroup-EB0BZTI536LE"
            },
            {
                "securityGroupId": "sg-1911fa66",
                "description": "default VPC security group",
                "name": "default"
            }
        ],
        "tenancy": "default"
    }
]
