---
sidebar: sidebar
permalink: cm/wf_aws_ontap_create_cifs.html
keywords: cloud, manager, rest, api, aws, cifs, server, configuration
summary: 'You can use this workflow to set up a new CIFS server configuration for an existing Cloud Volumes ONTAP working environment.'
---

= Create a CIFS server configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you want to create CIFS volumes on your Cloud Volumes ONTAP system, you first need to configure the CIFS server. You can choose to set up the CIFS server in a workgroup or in an Active Directory domain. Review the link:https://docs.netapp.com/us-en/ontap/smb-config/set-up-server-workgroup-task.html[Set up SMB (CIFS) in a workgroup] and link:https://docs.netapp.com/us-en/ontap/smb-config/set-up-server-workgroup-task.html[Set up SMB (CIFS) in an Active Directory domain] topics for more information.

Choose the correct workflow depending on the type of the Cloud Volumes ONTAP deployment:

* <<Create CIFS server configuration for single node, Single Node>>
* <<Create CIFS server configuration for high availability pair, HA pair>>

== Create CIFS server configuration for single node
You can use this workflow to create a CIFS server configuration for a single node system.

Choose the workflow that is specific to your goal:

* <<Set up a CIFS server in a workgroup>>
* <<Set up a CIFS server in an Active Directory domain>>

=== Set up a CIFS server in a workgroup
You can configure a CIFS server in a workgroup when the Microsoft Active Directory domain infrastructure is not available.

==== Step 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environments-for-single-node[Get working environments] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

==== Step 2. Create the CIFS configuration

Create the CIFS server configuration.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/vsa/working-environments/{workingEnvironmentId}/cifs-workgroup
|===

.Curl example
[source,curl]
curl --request POST
--location  "https://api.bluexp.netapp.com/occm/api/vsa/working-environments/<WORKING_ENV_ID>/cifs-workgroup" 
--header "Content-Type: application/json" 
--header "x-agent-id: <AGENT_ID>" 
--header "Authorization: Bearer <ACCESS_TOKEN>" 
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.


[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the working environment ID
|===

.JSON input example
[source,json]
{
  "serverName": "SMB_SERVER02",
  "workgroupName": "workgroup02",
  "svmName": "svm_ziv01we01"
}

.Output

None.

=== Set up a CIFS server in an Active Directory domain
You can create a CIFS server on the SVM and specify the Active Directory (AD) domain to which it belongs.

==== Step 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environments-for-single-node[Get working environments] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

==== Step 2. Determine the Active Directory configuration

You need the following configuration parameters for an Active Directory server.


[cols="35,65"*,options="header"]
|===
|Input parameter
|Description
|dnsDomain
|Use the Active Directory domain as the DNS name.
|ipAddresses
|Define the primary DNS IP address and optionally add a secondary IP address.
|netBIOS
|Use the CIFS server NetBIOS name.
|organizationalUnit
|Include the organizational unit as appropriate.
|activeDirectoryDomain
|Set the Active Directory domain to join.
|activeDirectoryUsername
|A username with authorization to join the domain.
|activeDirectoryPassword
|The password for the authorized username.
|===

==== Step 3. Create the CIFS configuration

Create the CIFS server configuration.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/vsa/working-environments/{workingEnvironmentId}/cifs
|===

.Curl example
[source,curl]
curl --request POST 
--location "https://api.bluexp.netapp.com/occm/api/vsa/working-environments/<WORKING_ENV_ID>/cifs" \ 
--header "Content-Type: application/json" 
--header "x-agent-id: <AGENT_ID>" 
--header "Authorization: Bearer <ACCESS_TOKEN>" 
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.


[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the working environment ID
|===

.JSON input example
[source,json]
{
  "dnsDomain": "zivh.netapp.com",
  "ipAddresses": [
    "172.31.5.241"
  ],
  "netBIOS": "zivaws02we03",
  "organizationalUnit": "CN=Computers",
  "activeDirectoryDomain": "zivh.netapp.com",
  "activeDirectoryUsername": "administrator",
  "activeDirectoryPassword": "password"
}

.Output

None.

== Create CIFS server configuration for high availability pair
You can use this workflow to create a CIFS server configuration for an HA working environment.

Choose the workflow that is specific to your goal:

* <<Set up a CIFS server in a workgroup (HA)>>
* <<Set up a CIFS server in an Active Directory domain (HA)>>

=== Set up a CIFS server in a workgroup (HA)
You can configure a CIFS server in a workgroup when the Microsoft Active Directory domain infrastructure is not available.

==== Step 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environments] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

==== Step 2. Create the CIFS configuration

Create the CIFS server configuration.

.Additional input parameters

The JSON input example includes the minimum list of parameters.


[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/aws/ha/working-environments/{workingEnvironmentId}/cifs-workgroup
|===

.Curl example
[source,curl]
curl --request POST  
--location "https://api.bluexp.netapp.com/occm/api/aws/ha/working-environments/<WORKING_ENV_ID>/cifs-workgroup"
--header "Content-Type: application/json" 
--header "x-agent-id: <AGENT_ID>" 
--header "Authorization: Bearer <ACCESS_TOKEN>" 
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.


[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the working environment ID
|===

.JSON input example::
[source,json]
{
  "serverName": "SMB_SERVER02",
  "workgroupName": "workgroup02",
  "svmName": "svm_ziv01we01"
}

.Output

None.

=== Set up a CIFS server in an Active Directory domain (HA)
You can create a CIFS server on the SVM and specify the Active Directory (AD) domain to which it belongs.

==== 1. Select the working environment

Perform the workflow link:wf_aws_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environments] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

==== 2. Determine the Active Directory configuration

You need the following configuration parameters for an Active Directory server.

[cols="35,65"*,options="header"]
|===
|Input parameter
|Description
|dnsDomain
|Use the Active Directory domain as the DNS name.
|ipAddresses
|Define the primary DNS IP address and optionally add a secondary IP address.
|netBIOS
|Use the CIFS server NetBIOS name.
|organizationalUnit
|Include the organizational unit as appropriate.
|activeDirectoryDomain
|Set the Active Directory domain to join.
|activeDirectoryUsername
|A username with authorization to join the domain.
|activeDirectoryPassword
|The password for the authorized username.
|===

==== 3. Create the CIFS configuration

Create the CIFS server configuration.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/aws/ha/working-environments/{workingEnvironmentId}/cifs
|===

.Curl example
[source,curl]
curl --request POST
--location  "https://api.bluexp.netapp.com/occm/api/aws/ha/working-environments/<WORKING_ENV_ID>/cifs" 
--header "Content-Type: application/json" 
--header "x-agent-id: <AGENT_ID>" 
--header "Authorization: Bearer <ACCESS_TOKEN>" 
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.


[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the working environment ID
|===


.JSON input example
[source,json]
{
  "dnsDomain": "zivh.netapp.com",
  "ipAddresses": [
    "172.31.5.241"
  ],
  "netBIOS": "zivaws02we03",
  "organizationalUnit": "CN=Computers",
  "activeDirectoryDomain": "zivh.netapp.com",
  "activeDirectoryUsername": "administrator",
  "activeDirectoryPassword": "password"
}

.Output

None.
