---
sidebar: sidebar
permalink: cm/wf_aws_before.html
keywords: aws, workflows, cloud, manager, rest, api
summary: There are several workflows you can use with the Amazon Web Services public cloud.
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several workflows you can use with the Amazon Web Services (AWS) public cloud.

[NOTE]
Review the link:https://docs.netapp.com/us-en/cloud-manager-automation/cm/prepare.html[Get started] section before using any of the Cloud Volumes ONTAP REST API workflows.

== Workflow categories
The AWS workflows are organized into the following functional categories:

* Working environments
* Aggregates
* Volumes
* Metadata
* Miscellaneous

See link:workflow_processes.html[Understanding the workflow processes] for more information on these categories.

[NOTE]
The link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-aws-elastic-volumes.html[Amazon EBS Elastic Volumes] feature is enabled by default on new Cloud Volumes ONTAP 9.11.0 or later systems when using `gp3` or `io1` disks.
To support the feature, a few additional fields have been added. The workflows have been updated to reflect the changes. 

== Connector setup

You must have a *Connector* for the cloud environment before creating a working environment and performing other activities using the workflows. You can create a Connector using the BlueXP web UI. When you create a Connector, BlueXP adds the AWS cloud provider account that you deployed the Connector in to your list of available accounts. Your AWS account needs to have the right permissions in order to create a Connector.

Review https://docs.netapp.com/us-en/occm/task_creating_connectors_aws.html[Learn about AWS Connectors] to know how to create and deploy an AWS Connector.
