---
sidebar: sidebar
permalink: cm/wf_azure_cloud_delete_we.html
keywords: cloud, manager, rest, api, working, environment, cloud, volumes, ontap, occm
summary: 'You can delete an existing Cloud Volumes ONTAP working environment.'
---

= Delete a working environment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can delete an existing Azure Cloud Volumes ONTAP working environment.

=== 1. Create the working environment 

Perform the workflow link:wf_azure_cloud_create_we_paygo.html[Create Azure single node working environment] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

=== 2. Delete the working environment

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/azure/vsa/working-environments/{workingEnvironmentId}
|===

Curl example::
[source,curl]
curl --location --request DELETE 'https://cloudmanager.cloud.netapp.com/occm/api/azure/vsa/working-environments/<WORKING_ENV_ID>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameter <WORKING_ENV_ID> `(workingEnvironmentId)` string

(Optional) Query parameters:

* `localDelete` boolean
+
If `true` the Cloud Volumes ONTAP instance in the cloud is not terminated, but Cloud Manager no longer manages it (default is `false`).

* `forceDelete` boolean
+
If `true` the working environment is deleted even if it is part of one or more SnapMirror relationships (default is `false`).

Output::

None
