---
sidebar: sidebar
permalink: cm/wf_aws_ontap_delete_aggr.html
keywords: aggregate, delete, working, environment, aws, workflows
summary: 'You can delete an existing disk aggregate.'
---

= Delete aggregate
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can delete an existing disk aggregate.

=== 1. Select the working environment to use

Perform the workflow link:wf_aws_cloud_get_wes.html[Get working environments] and choose the `publicId` value for the working environment path parameter.

=== 2. Select the aggregate to delete

Perform the workflow link:wf_aws_ontap_get_aggrs.html[Get aggregates] and choose the `name` value for the aggregate path parameter.

=== 3. Delete the aggregate

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/vsa/aggregates/{workingEnvironmentId}/{aggregateName}
|===

curl example::
[source,curl]
curl --location --request DELETE 'https://cloudmanager.cloud.netapp.com/occm/api/vsa/aggregates/<WORKING_ENV_ID>/<AGGR_NAME>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameter <WORKING_ENV_ID> (`workingEnvironmentId`)
Path parameter <AGGR_NAME> (`aggregateName`)

Output::

None
