---
sidebar: sidebar
permalink: cm/wf_aws.html
keywords: aws, workflows, cloud, manager, rest, api
summary: There are several workflows you can use with the Amazon Web Services public cloud.
---

= Workflows for Amazon Web Services
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several workflows you can use with the Amazon Web Services public cloud.

[NOTE]
Before using any of the Cloud Manager REST API workflows, make sure to first review link:getting_started.html[Getting started].

== Workflow categories
The AWS workflows are organized into the following categories:

* Working environments
* Aggregates
* Volumes
* Metadata

== Connector setup

You must have a *Connector* for the cloud environment before creating a working environment and performing other activities using the workflows. You can create a Connector using the Cloud Manager web UI. When you create a Connector, Cloud Manager adds the Azure cloud provider account that you deployed the Connector in to your list of available accounts. Your Azure account needs to have the right permissions in order to create a Connector.

Review https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html[Learn about Azure Connectors] to know how to create and deploy an Azure Connector.
