---
sidebar: sidebar
permalink: cm/wf_common_identity_create_service_token.html
keywords: generate, user, token
summary: 'You must generate a bearer token to authenticate and access the Cloud Manager REST API. There are two workflows available depending on the type of authentication.'
---

= Create service token
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This workflow describes how to create a service access token used by services to perform automated tasks.

.Before you begin
You need to obtain the following:

 * `client_id`: The application ID that the Cloud Manager SaaS UI has assigned to your application.
 * `client_secret`: The secret generated by the UI when you registered the application.

=== 1. Generate the service token

This API call uses the _Auth0_ authentication service and not the NetApp Cloud Manager service. See the URL in the curl example below and adjust for your environment as needed.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Resource path
|POST
|/oauth/token
|===

curl example::
[source,curl]
curl --location --request POST 'https://netapp-cloud-account.auth0.com/oauth/token' --header 'Content-Type: application/json' --d @JSONinput

Input parameters::

The JSON input example includes the list of input parameters.

JSON input example::
[source,json]
{
    "audience": "https://api.cloud.netapp.com",
    "client_id": "TvPPs4SeM5smEElsGmdDUznljhN3YY8s",
    "client_secret": "3ajeU_pG9rngJvsdfFRghtr5G3NnmgdnYG7IVfN5wDR_tnd1-qfScYC_TPraT",
    "grant_type": "client_credentials"
}


Output::

The JSON output example includes the list of returned values. The `expires_in` value is expressed in seconds.

JSON output example::
[source,json]
{
    "access_token": "<SERVICE_TOKEN>",
    "scope": "occm-access",
    "expires_in": 86400,
    "token_type": "Bearer"
}
