---
sidebar: sidebar
permalink: cm/wf_common_identity_get_tenants.html
keywords: cloud, manager, rest, api, account, id, tenants, cloud, manager, web, ui
summary: "You can retrieve a list of tenants visible to the user currently signed in through the account workspace."
---

= Get tenants
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can retrieve a list of tenants visible to the user currently signed in through the account workspace.

== Step 1. Get the account identifier

Perform the workflow link:wf_common_identity_get_supported_srv.html[Get supported services] to retrieve the account ID.

[NOTE]
You can also get the account identifier through the BlueXP web UI. See link:../platform/get_identifiers.html[Get required identifiers] for more information.

== Step 2. Get the account workspace

You can issue the REST API call to retrieve the account workspace.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Resource path
|GET
|/tenancy/account/{account_id}/workspace
|===

.Curl example
[source,curl]
curl --request GET \
--location "https://api.bluexp.netapp.com/tenancy/account/<ACCOUNT_ID>/workspace" \
--header "Content-Type: application/json" \
--header "Authorization: Bearer <ACCESS_TOKEN>"

.Input parameters

Path parameter with the account ID.

.JSON Output example

The JSON output example shows the list of tenants.

.Example output
----
[
    {
        "workspacePublicId": "workspace-ced4x9X4",
        "workspaceName": "Workspace-1",
        "associatedAgents": []
    }
]
----
