---
sidebar: sidebar
permalink: cm/wf_common_identity_get_nss_keys.html
keywords: cloud, manager, rest, api
summary: "You can retrieve all of the available NetApp Support Site credential keys."
---

= Get NSS keys
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can retrieve all of the available NetApp Support Site credential keys.

=== 1. Select the account to use

Perform the workflow link:wf_common_identity_get_provider_accounts.html[Get cloud provider accounts] and choose the `accountId` value for the path parameter.

=== 2. Retrieve the NSS keys

[cols="25,75"*,options="header"]
|===
|HTTP method
|Resource path
|GET
|/ipa/account/{accountId}/nss-keys
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/ipa/account/<ACCOUNT_ID>/nss-keys?includeResources=true' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID> --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input parameters::

* Path parameter <ACCOUNT_ID> `(accountId)`
* Query parameter `includeResources` is optional

Output::

The JSON output example includes a list of the NSS keys.

JSON output example::
[source,json]
[
    {
        "id": "d69a5214-7d61-486e-8750-8e1f68601c43",
        "username": "zivtest03",
        "resources": [VsaWorkingEnvironment-4UHd0x6l],
        "credentialType": "password"
    },
    {
        "id": "98f2c5db-af76-428f-ae81-08fdfa1e04ae",
        "username": "zivtest23",
        "resources": [],
        "credentialType": "password"
    }
]
