---
sidebar: sidebar
permalink: cm/wf_flexgroup_ontap_create_vol.html
keywords: cloud, manager, rest, api, aggregate, svm, virtual, private, cloud
summary: 'You can use this workflow to create a volume accessed through NFS.'
---

= Create a FlexGroup volume
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to create a FlexGroup volume using the NFS and CIFS protocols. 

.Requirements

* The ONTAP cluster must be running version 9.7 or later.

* You should be aware of the considerations and requirements when selecting the aggregates for provisioning a FlexGroup volume. For details, refer to https://docs.netapp.com/us-en/ontap/flexgroup/create-task.html[ONTAP documentation^].

* You should be aware of minimum and maximum size limits. For details, refer to the https://www.netapp.com/pdf.html?item=/media/12385-tr4571.pdf[NetApp ONTAP FlexGroup volumes best practices and implementation guide^].


.Limitations

* FlexGroup volumes are not supported as a source for data replication from the BlueXP replication service.

“FlexGroup volume size validation״
FG volume min/max size limit is based on the number of constituents.
The maximum constituent number is 200;
min size of constituents member is 100GB, max size is 100TB
so, f.e.

If you set 10 constituents, the min vol size should be 100GB * 10 = 1TB and the max vol size should be 100TB * 10 = 1000TB
Note: constituents member in request is total constituents for FlexGroup volume, this number shall be distributed equally between required aggregates from the list. The number of constituents for a FlexGroup volume should match the number of requested aggregate.
 





“Onprem - Can choose one or more aggregates. Can have Several aggregates on several nodes . once first is chosen we will disable all other aggregates (that have a different disk type or size”
“all aggregates shall be assigned to the requested svm”
“Tiering Validation - All aggregates must have Tiering Enabled/Disabled.”
“WORM Validation - All aggregates must have WORM Enabled/Disabled.”

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.


== 1. Select the working environment

Perform the workflow link:wf_onprem_get_wes.html[Get working environments] and choose the `publicId` and the `svmName` values for the `workingEnvironmentId` and the `svmName` parameters.

== 2. Select the aggregate

You can select one or more aggregates depending on your requirement. 

[NOTE]
If an aggregate exists, `aggregateName` parameter is not provided.

== 3. Select the network 

Choose the desired value for the `exportPolicyInfo` parameter. You need to specify your internal network IP for the `ips` parameter that can access a volume.

== 4. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.


== 5. Create the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/onprem/volumes
|===

curl example::
[source,curl]
curl --location --request POST 'https://cloudmanager.cloud.netapp.com/occm/api/onprem/volumes' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --d @JSONinput

Optional parameters::

FlexGroupVolumeInfo


Input::

The JSON input example includes the minimum list of input parameters, including:

* <WORKING_ENV_ID> `(workingEnvironmentId)`
* <SVM_NAME> `(svmName)`
* <AGGR_NAME> `(aggregateName)`

If aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

JSON input example::
[source,json]
{
  "verifyNameUniqueness": true,
  "name": "fgvol3",
  "volumeTags": [],
  "size": {
    "size": "2",
    "unit": "TB"
  },
  "enableCompression": true,
  "enableDeduplication": true,
  "flexGroupVolumeInfo": {
    "aggregateList": [
      "aggr2GP3",
      "aggr1"
    ],
    "numberOfConstituents": 10
  },
  "enableThinProvisioning": true,
  "svmName": "svm_cvogalinaonprem",
  "snapshotPolicyName": "default",
  "autoVsaCapacityManagementEnabled": true,
  "exportPolicyInfo": {
    "policyType": "custom",
    "rules": [
      {
        "nfsVersion": [
          "nfs3",
          "nfs4"
        ],
        "ruleAccessControl": "readwrite",
        "ips": [
          "0.0.0.0/0"
        ],
        "superUser": true,
        "index": 1
      }
    ]
  },
  "workingEnvironmentId": "OnPremWorkingEnvironment-oB3ntdCq"
}


Output::

None

