---
sidebar: sidebar
permalink: cm/wf_flexgroup_ontap_create_vol_nfs.html
keywords: cloud, manager, rest, api, aggregate, svm, virtual, private, cloud
summary: 'You can use this workflow to create a volume accessed through NFS.'
---

= Create a FlexGroup volume
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to create a FlexGroup volume.

“For now, we don't allow to choose FG volume as source for replication“
“ISCSI option shall not be supported by Flex Group volume”
“FlexGroup volume size validation״
FG volume min/max size limit based on number of constituents.
max constituents number is 200
min size of constituents member is 100GB, max size is 100TB
so, f.e.

if user will set 10 constituents, 

the min vol size should be 100GB * 10 = 1TB
the max vol size should be 100TB * 10 = 1000TB
Note: constituents member in request is total constituents for FlexGroup volume, this number shall be distributed equally between required aggregates from the list. So, number of constituents for the FlexGroup volume shall match the number of requested aggregates
 

[NOTE] FlexGroup is supported for on premises systems running ONTAP 9.7 and later.

If existing, aggregateName parameter shall not be provided.

“Onprem - Can choose one or more aggregates. Can have Several aggregates on several nodes . once first is chosen we will disable all other aggregates (that have a different disk type or size”
“all aggregates shall be assigned to the requested svm”
“Tiering Validation - All aggregates must have Tiering Enabled/Disabled.”
“WORM Validation - All aggregates must have WORM Enabled/Disabled.”

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.


== 1. Select the working environment

Perform the workflow link:wf_onprem_get_wes.html[Get working environments] and choose the `publicId` and the `svmName` values for the `workingEnvironmentId` and the `svmName` parameters.

== 2. Select the aggregate

Perform the workflow link:wf_onprem_ontap_get_aggrs.html[Get aggregates] and choose the `name` value of the aggregate for the `name` parameter.

[NOTE]
If aggregate name does not exist and the `createAggregateIfNotFound` query parameter is set `true`, the create volume request is allowed if the named aggregate is not found.

== 3. Select the network 

Choose the desired value for the `exportPolicyInfo` parameter. You need to specify your internal network IP for the `ips` parameter that can access a volume.

== 4. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.


== 5. Create the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/onprem/volumes
|===

curl example::
[source,curl]
curl --location --request POST 'https://cloudmanager.cloud.netapp.com/occm/api/onprem/volumes' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --d @JSONinput

Optional parameters::

FlexGroupVolumeInfo


Input::

The JSON input example includes the minimum list of input parameters, including:

* <WORKING_ENV_ID> `(workingEnvironmentId)`
* <SVM_NAME> `(svmName)`
* <AGGR_NAME> `(aggregateName)`

If aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

JSON input example::
[source,json]
{
    "workingEnvironmentId": "OnPremWorkingEnvironment-xxx",
    "aggregateName": "aggr2",
    "name": "vol3",
    "size": {
        "size": "100",
        "unit": "GB"
    },
    "snapshotPolicyName": "default",
    "svmName": "svm_dfr",
    "enableCompression": true,
    "enableDeduplication": true,
    "enableThinProvisioning": true,
    "verifyNameUniqueness": true,
    "volumeTags": [],
    "exportPolicyInfo": {
        "policyType": "custom",
        "rules": [
            {
                "index": 1,
                "ruleAccessControl": "readwrite",
                "ips": [
                    "0.0.0.0/0"
                ],
                "nfsVersion": [
                    "nfs3",
                    "nfs4"
                ],
                "superUser": true
            }
        ]
    }
}


Output::

None

