---
sidebar: sidebar
permalink: cm/wf_gcp_ontap_create_vol_nfs.html
keywords: cloud, manager, rest, api, aggregate, svm, virtual, private, cloud
summary: 'You can use this workflow to create a volume accessed through NFS.'
---

= Create a volume using NFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to create a volume accessed through NFS protocol.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Create a volume using NFS for single node, Single Node>>
* <<Create a volume using NFS for high availability pair, HA pair>>

== Create a volume using NFS for single node
You can use this workflow to create a volume using NFS for a single node working environment.

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.

=== 1. Select the working environment

Perform the workflow link:wf_gcp_cloud_get_wes.html#get-working-environment-for-single-node[Get working environment] and choose the `publicId` and the `svmName` values for the `workingEnvironmentId`  and the `svmName` parameters. From the `capacityFeatures` field in the response, choose the value of the `capacityTier` parameter.

=== 2. Select the aggregate

Perform the workflow link:wf_gcp_ontap_get_aggrs.html#get-aggregates-for-single-node[Get aggregates] and choose the `name` value of the aggregate for the `name` parameter. From the `providerVolumes` field in the response, you must also choose the value of the `providerVolumeType` parameter, the value of the `iops` parameter, and the value of the `throughput` parameter.

[NOTE]
If aggregate name does not exist and the `createAggregateIfNotFound` query parameter is set `true`, the create volume request is allowed if the named aggregate is not found.

=== 3. Choose the size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.

=== 4. Select the region
Perform the workflow link:wf_gcp_cloud_md_get_regions.html#get-regions-for-single-node[Get regions] workflow and pick `ipCidrRange` value of the required `region-> subnets` for `exportPolicy->ips` value.

=== 5. Select the rules

Choose values for the `exportPolicyInfo->rules->ruleAccessControl` and `exportPolicyInfo->rules->superUser` parameters.

=== 6. Create the quote

Perform the workflow link:wf_gcp_ontap_create_quote.html#create-quote-for-single-node[Create quote]. This is a recommended step but is not mandatory.

=== 7. Create the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/gcp/vsa/volumes
|===

curl example::
[source,curl]
curl --location --request POST 'https://api.bluexp.netapp.com/occm/api/gcp/vsa/volumes?createAggregateIfNotFound=false' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --d @JSONinput

Input::

The JSON input example includes the minimum list of input parameters, including:

* <WORKING_ENV_ID> `(workingEnvironmentId)`
* <SVM_NAME> `(svmName)`
* <AGGR_NAME> `(aggregateName)`

If aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

JSON input example::
[source,json]
{ 
  "workingEnvironmentId": "vsaworkingenvironment-u5lqmxrf",
   "svmName": "svm_name", 
   "aggregateName": "aggr1", 
   "name": "gcp_vol_nfs", 
   "size": { 
    "size": "1", 
    "unit": "GB"
    }, 
    "snapshotPolicyName": "default", 
    "exportPolicyInfo": { 
      "policyType": "custom", 
      "rules": 
      [ 
        { 
          "index": 1, 
          "ruleAccessControl": 
          "readwrite", 
          "ips": [ "0.0.0.0/0" ], 
          "nfsVersion": [ 
            "nfs3", 
            "nfs4" 
            ], 
             "superUser": True       
      }
    ]
 }
          "enableThinProvisioning": true, 
          "enableCompression": true, 
          "enableDeduplication": true, 
          "maxNumOfDisksApprovedToAdd": 0, 
          "evCapacityApprovedToAdd": null, 
          "verifyNameUniqueness": true, 
          "providerVolumeType": "pd-ssd", 
          "iops": null, 
          "throughput": null, 
          "capacityTier": "cloudStorage", 
          "tieringPolicy": "auto", 
          "minimumCoolingDays": 31
} 

Output::

None

== Create a volume using NFS for high availability pair
You can use this workflow to create a volume using NFS for an HA working environment.

[NOTE]
If the properties `aggregateName` and `maxNumOfDisksApprovedToAdd` are not provided on the REST API call, the response will fail with a suggested name for the aggregate and the number of disks needed to fulfill the request.

=== 1. Select a working environment

Perform the workflow link:wf_gcp_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environment] and choose the `publicId` and the `svmName` values for the `workingEnvironmentId`  and the `svmName` parameters.  From the `capacityFeatures` field in the response, choose the value of the `capacityTier` parameter.

=== 2. Select an aggregate

Perform the workflow link:wf_gcp_ontap_get_aggrs.html#get-aggregates-for-high-availability-pair[Get aggregates] and choose the `name` value of the aggregate for the `name` parameter.  From the `providerVolumes` field in the response, you must also choose the value of the `providerVolumeType` parameter, the value of the `iops` parameter, and the value of the `throughput` parameter.

[NOTE]
If aggregate name does not exist and the `createAggregateIfNotFound` query parameter is set `true`, the create volume request is allowed if the named aggregate is not found.

=== 3. Choose a size for the disk

Choose the size value for the `size:size` parameter. The `size:unit` must be one of the following: `TB`, `GB`, `MB`, `KB`, or `Byte`.

=== 4. Select a region
Perform the workflow link:wf_gcp_cloud_md_get_regions.html#get-regions-for-high-availability-pair[Get regions] workflow and pick `ipCidrRange` value of the required `region-> subnets` for `exportPolicy->ips` value.

=== 5. Select rules

Choose values for the `exportPolicyInfo->rules->ruleAccessControl` and `exportPolicyInfo->rules->superUser`
parameters.

=== 6. Create a quote

Perform the workflow link:wf_gcp_ontap_create_quote.html#create-quote-for-high-availability-pair[Create quote]. This is a recommended step but is not mandatory.

=== 7. Create the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/gcp/ha/volumes
|===

curl example::
[source,curl]
curl --location --request POST 'https://api.bluexp.netapp.com/occm/api/gcp/ha/volumes' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --d @JSONinput

Input::

The JSON input example includes the minimum list of input parameters, including:

* <WORKING_ENV_ID> `(workingEnvironmentId)`
* <SVM_NAME> `(svmName)`
* <AGGR_NAME> `(aggregateName)`

If aggregate name does not exist, you can set the `createAggregateIfNotFound` query parameter to `true` which allows the aggregate not-found condition.

JSON input example::
[source,json]
{ 
  "workingEnvironmentId": "vsaworkingenvironment-u5lqmxrf",
   "svmName": "svm_name", 
   "aggregateName": "aggr1", 
   "name": "gcp_vol_nfs", 
   "size": { 
    "size": "1", 
    "unit": "GB"
    }, 
    "snapshotPolicyName": "default", 
    "exportPolicyInfo": { 
      "policyType": "custom", 
      "rules": 
      [ 
        { 
          "index": 1, 
          "ruleAccessControl": 
          "readwrite", 
          "ips": [ "0.0.0.0/0" ], 
          "nfsVersion": [ 
            "nfs3", 
            "nfs4" 
            ], 
             "superUser": True       
      }
    ]
 }
          "enableThinProvisioning": true, 
          "enableCompression": true, 
          "enableDeduplication": true, 
          "maxNumOfDisksApprovedToAdd": 0, 
          "evCapacityApprovedToAdd": null, 
          "verifyNameUniqueness": true, 
          "providerVolumeType": "pd-ssd", 
          "iops": null, 
          "throughput": null, 
          "capacityTier": "cloudStorage", 
          "tieringPolicy": "auto", 
          "minimumCoolingDays": 31
} 

Output::

None
