---
sidebar: sidebar
permalink: cm/wf_gcp_cloud_md_get_instance_type_nosupport.html
keywords: cloud, volumes, ontap, cvo, regions, aws, workflows
summary: This workflow retrieves the AWS regions in which an Cloud Volumes ONTAP working environment may be created.
---

= Get instance types not supporting acceleration and capacity tiering
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This workflow retrieves the GCP instance types which do not support the acceleration and capacity tiering. This means that these kind instance types do not use any sort of hardware accelerator. You can check the instance types  while provisioning the Cloud Volumes ONTAP.

Choose the correct workflow depending on the type of Cloud Volumes ONTAP deployment:
* <<Create working environment for single node, Single Node>>
* <<Create working environment for high availability pair, HA pair>>

== Create working environment for single node
You can use this workflow to create single node working environment with BYOL licensing.
=== 1. Get the instance types

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|occm/api/gcp/vsa/metadata/instance-types-not-supporting-acceleration-and-capacity-tiering
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/gcp/vsa/metadata/instance-types-not-supporting-acceleration-and-capacity-tiering' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

None


Output::

The JSON output provides an example of a list of instance types.

JSON output example::
[source,json]
{
    "instanceTypes": []
}
