---
sidebar: sidebar
permalink: cm/wf_gcp_cloud_md_create_buckets.html
keywords: buckets, cloud, volumes, ontap, working, environment, occm
summary: You can perform this workflow to create the S3 buckets.
---

= Create bucket
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can perform this workflow to create a new bucket. This is a Google Cloud storage bucket (data container in Google Cloud) required for data tiering and backup.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Create bucket for single node, Single Node>>
* <<Create bucket for high availability pair, HA pair>>

== Create bucket for single node
You can use this workflow to create a bucket for a single node working environment.

=== 1. Select the project
Perform the link:wf_gcp_cloud_md_get_projects.html#get-projects-for-single-node[Get projects] workflow and choose the `projectId`` value of the required project for the `projectId` parameter.

=== 2. Select the region
Perform the link:wf_gcp_cloud_md_get_regions.html#get-regions-for-single-node[Get regions] workflow and choose the `name` value of the required region for the `location` parameter.

=== 3. Create a bucket

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/gcp/vsa/metadata/create-bucket
|===

curl example::
[source,curl]
curl --location --request POST 'https://api.bluexp.netapp.com/occm/api/gcp/vsa/metadata/create-bucket' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --header 'Content-Type: application/json' --d JSONinput


JSON input example::
[source,json]
{
  "projectId": "occm-dev",
  "bucketName": "zivgcpbucket02",
  "location": "us-west1",
  "storageClass": "standard"
}

Output::

None

== Create bucket for high availability pair
You can use this workflow to create a bucket for an HA working environment.

=== 1. Select the project
Perform the link:wf_gcp_cloud_md_get_projects.html#get-projects-for-high-availability-pair[Get projects] workflow and choose the `projectId`` value of the required project for the `projectId` parameter.

=== 2. Select the region
Perform the link:wf_gcp_cloud_md_get_regions.html#get-regions-for-high-availability-pair[Get regions] workflow and choose the `name` value of the required region for the `location` parameter.

=== 3. Create a bucket

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/gcp/ha/metadata/create-bucket
|===

curl example::
[source,curl]
curl --location --request POST 'https://api.bluexp.netapp.com/occm/api/gcp/ha/metadata/create-bucket' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --header 'Content-Type: application/json' --d JSONinput


JSON input example::
[source,json]
{
  "projectId": "occm-dev",
  "bucketName": "zivgcpbucket02ha",
  "location": "us-west1",
  "storageClass": "standard"
}


Output::

None
