---
sidebar: sidebar
permalink: cm/wf_gcp_ontap_get_igroups.html
keywords: cloud, manager, rest, api, igroups, cifs, server, configuration
summary: "You can use this workflow to retrieve all the iGroups."
---

= Get iGroups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to retrieve all the initiator groups (iGroups).

Choose the correct workflow depending on the type of Cloud Volumes ONTAP deployment:

* <<Create working environment for single node, Single Node>>
* <<Create working environment for high availability pair, HA pair>>

== Create working environment for single node
You can use this workflow to create single node working environment with BYOL licensing.

=== 1. Create the working environment

Perform the workflow link:wf_gcp_cloud_create_we_paygo.html[Create GCP single node working environment] and choose the `publicId` and `svmName` values for the working environment `workingEnvironmentId` and `svmName` path parameters.

=== 2. Get the CIFS configurations

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/gcp/vsa/volumes/igroups/{workingEnvironmentId}/{svmName}
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/gcp/vsa/volumes/igroups/<WORKING_ENV_ID>/<SVM_NAME>' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>' --header 'Content-Type: application/json'

Input::

* Path parameter <WORKING_ENV_ID> `workingEnvironmentId` string
* Path parameter <SVM_NAME> `svmName` string

Output::

The JSON output example includes a list of iGroups.

JSON output example::
[source,json]
[
    {
        "igroupName": "zivIgroup1",
        "osType": "linux",
        "portsetName": "",
        "igroupType": "iscsi",
        "initiators": [
            "iqn.1994-05.com.redhat:1d9ac633937c"
        ]
    },
    {
        "igroupName": "zivIgroup2",
        "osType": "linux",
        "portsetName": "",
        "igroupType": "iscsi",
        "initiators": [
            "iqn.1994-05.com.redhat:96de86825216"
        ]
    }
]
