---
sidebar: sidebar
permalink: cm/wf_gcp_ontap_modify_volume.html
keywords: cloud, manager, rest, api, modify, volume,
summary: "You can modify the configuration of an existing volume."
---

= Modify volume
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can modify the configuration of an existing volume.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Modify volume for single node, Single Node>>
* <<Modify volume for high availability pair, HA pair>>

== Modify volume for single node
You can use this workflow to modify the configuration of an existing volume for a single node working environment.

=== Step 1. Select the working environment

Perform the workflow link:wf_gcp_cloud_get_wes.html#get-working-environment-for-single-node[Get working environment] and choose the `publicId`  and `svmName` values of the working environment for used as the `workingEnvironmentId` and `svmName` path parameters.

=== Step 2. Select the volume

Perform the workflow link:wf_gcp_ontap_get_volumes.html#get-volumes-for-single-node[Get volumes] and choose the `name` for the `volumeName` path parameter.

=== Step 3. Modify the volume

You can issue a REST API call to modify an existing volume.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|PUT
|/occm/api/gcp/vsa/volumes/{workingEnvironmentId}/{svmName}/{volumeName}
|===

.Curl example
[source,curl]
curl --request PUT \
--location 'https://api.bluexp.netapp.com/occm/api/gcp/vsa/volumes/<WORKING_ENV_ID>/<SVM_NAME>/<VOLUME_NAME>' \
--header 'Content-Type: application/json' \
--header 'x-agent-id: <AGENT_ID>' \
--header 'Authorization: Bearer <ACCESS_TOKEN>' \
--d @JSONinput


.Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl example.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
| <WORKING_ENV_ID> `(workingEnvironmentId)` |Path |Yes |Identifies the working environment.
| <SVM_NAME> `(svmName)` |Path |Yes |Identifies the storage VM.
| <VOLUME_NAME> `(volumeName)` |Path |Yes |Identifies the volume.
|===


.JSON input example

The JSON input example includes the minimum list of input parameters.

[NOTE]

====
The `exportpolicyInfo -> policyType` parameter can have two values `none` and `custom`.

** When `policyType:none`, the rules parameter must be empty.
** When `policyType:custom`, the rules parameter must have at least one rule.
====


[source,json]
{
 "exportPolicyInfo": {
  "policyType": "custom",
  "ips": [
    "10.XXX.XXX.XXX/24","10.yyy.yyy.yyy/21","10.zzz.zzz.zzz/21"
  ],
  "nfsVersion": [
    "any"
  ],
  "rules": [
   {
    "index": 1,
    "ruleAccessControl": "readwrite",
    "ips": ["10.XXX.XXX.XXX/24","10.yyy.yyy.yyy/21","10.zzz.zzz.zzz/21"],
    "nfsVersion": [
      "any"
     ],
    "superUser": "True"
    }
  ]
 }
}


.Output

None

== Modify volume for high availability pair
You can use this workflow to modify the configuration of an existing volume for an HA working environment.

=== Step 1. Select the working environment

Perform the workflow link:wf_gcp_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environment] and choose the `publicId`  and `svmName` values of the working environment for used as the `workingEnvironmentId` and `svmName` path parameters.

=== Step 2. Select the volume

Perform the workflow link:wf_gcp_ontap_get_volumes.html#get-volumes-for-high-availability-pair[Get volumes] and choose the `name` for the `volumeName` path parameter.

=== Step 3. Modify the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|PUT
|/occm/api/gcp/ha/volumes/{workingEnvironmentId}/{svmName}/{volumeName}
|===

.Curl example
[source,curl]
curl --request PUT
--location "https://api.bluexp.netapp.com/occm/api/gcp/ha/volumes/<WORKING_ENV_ID>/<SVM_NAME>/<VOLUME_NAME>" 
--header "Content-Type: application/json" 
--header "x-agent-id: <AGENT_ID>" 
--header "Authorization: Bearer <ACCESS_TOKEN>" 
--d @JSONinput

.Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl example.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
| <WORKING_ENV_ID> `(workingEnvironmentId)` |Path |Yes |Identifies the working environment.
| <SVM_NAME> `(svmName)` |Path |Yes |Identifies the storage VM.
| <VOLUME_NAME> `(volumeName)` |Path |Yes |Identifies the volume.
|===

.JSON input example

The JSON input example includes the minimum list of input parameters.

[NOTE]

====
The `exportpolicyInfo -> policyType` parameter can have two values `none` and `custom`.

** When `policyType:none`, the rules parameter must be empty.
** When `policyType:custom`, the rules parameter must have at least one rule.
====


[source,json]
{
 "exportPolicyInfo": {
  "policyType": "custom",
  "ips": [
    "10.XXX.XXX.XXX/24","10.yyy.yyy.yyy/21","10.zzz.zzz.zzz/21"
  ],
  "nfsVersion": [
    "any"
  ],
  "rules": [
   {
    "index": 1,
    "ruleAccessControl": "readwrite",
    "ips": ["10.XXX.XXX.XXX/24","10.yyy.yyy.yyy/21","10.zzz.zzz.zzz/21"],
    "nfsVersion": [
      "any"
     ],
    "superUser": "True"
    }
  ]
 }
}

.Output

None