---
sidebar: sidebar
permalink: cm/wf_gcp_ontap_delete_aggr.html
keywords: aggregate, delete, working, environment, aws, workflows
summary: 'You can delete an existing disk aggregate.'
---

= Delete aggregate
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can delete an existing disk aggregate in a Cloud Volumes ONTAP working environment.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Delete aggregate for single node, Single Node>>
* <<Delete aggregate for high availability pair, HA pair>>

== Delete aggregate for single node
You can use this workflow to delete an aggregate for a single node working environment.

=== 1. Select the working environment

Perform the workflow link:wf_gcp_cloud_get_wes.html#get-working-environment-for-single-node[Get working environment] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

=== 2. Select the aggregate

Perform the workflow link:wf_gcp_ontap_get_aggrs.html#get-aggregates-for-single-node[Get aggregates] and choose the `name` value of the required aggregate for the `aggregateName` path parameter.

=== 3. Delete the aggregate

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/gcp/vsa/aggregates/{workingEnvironmentId}/{aggregateName}
|===

curl example::
[source,curl]
curl --location --request DELETE 'https://api.bluexp.netapp.com/occm/api/gcp/vsa/aggregates/<WORKING_ENV_ID>/<AGGR_NAME>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameters:
* <WORKING_ENV_ID> (`workingEnvironmentId`) string
* <AGGR_NAME> (`aggregateName`) string

Output::

None

== Delete aggregate for high availability pair
You can use this workflow to delete an aggregate for an HA working environment.

=== 1. Select the working environment

Perform the workflow link:wf_gcp_cloud_get_wes.html#get-working-environment-for-high-availability-pair[Get working environment] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

=== 2. Select the aggregate

Perform the workflow link:wf_gcp_ontap_get_aggrs.html#get-aggregates-for-high-availability-pair[Get aggregates] and choose the `name` value of the required aggregate for the `aggregateName` path parameter.

=== 3. Delete the aggregate

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/gcp/ha/aggregates/{workingEnvironmentId}/{aggregateName}
|===

curl example::
[source,curl]
curl --location --request DELETE 'https://api.bluexp.netapp.com/occm/api/gcp/ha/aggregates/<WORKING_ENV_ID>/<AGGR_NAME>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameters:
* <WORKING_ENV_ID> (`workingEnvironmentId`) string
* <AGGR_NAME> (`aggregateName`) string

Output::

None
