---
sidebar: sidebar
permalink: cm/wf_gcp_before.html
keywords: gcp, workflows, cloud, manager, rest, api
summary: There are several workflows you can use with the Google public cloud.
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

There are several workflows that you can use to deploy and manage Cloud Volumes ONTAP in Google Cloud.

[NOTE]
Review the link:getting_started.html[Get started] section before using any of the Cloud Manager REST API workflows.

== Workflow categories
The GCP workflows are organized into the following categories:

* Working environments
* Aggregates
* Volumes
* Metadata


See link:workflow_processes.html[Understanding the workflow processes] for more information on these categories.

[NOTE]
Cloud Volumes ONTAP requires a Google Cloud service account to run several background automation tasks such as data tiering and backup service. link:https://docs.netapp.com/us-en/occm/task_creating_gcp_service_account.html[Learn more about GCP service accounts].

== Connector setup

You must have a *Connector* for the cloud environment before creating a working environment and performing other activities using the workflows. You can create a Connector using the Cloud Manager web UI. When you create a Connector, Cloud Manager adds the GCP cloud provider account that you deployed the Connector in to your list of available accounts. Your GCP account needs to have the right permissions in order to create a Connector.

Review https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html[Learn about GCP Connectors] to know how to create and deploy a GCP Connector.
