---
sidebar: sidebar
permalink: cm/wf_gcp_cloud_md_get_service_accounts.html
keywords: cloud, volumes, ontap, cvo, regions, aws, workflows
summary: This workflow retrieves the AWS regions in which an Cloud Volumes ONTAP working environment may be created.
---

= Get service accounts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This workflow retrieves a list of service accounts from the specified project.


=== 1. Get the list of service accounts

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/gcp/vsa/metadata/service-accounts
|===

curl example::
[source,curl]
curl --location --request GET 'https://cloudmanager.cloud.netapp.com/occm/api/gcp/vsa/metadata/service-accounts' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

None


Output::

The JSON output retrieves a list of service accounts from the project.

JSON output example::
[source,json]
{
"accounts": [
    {
        "name": "projects/occm-dev/serviceAccounts/00000-compute@serviceaccount.com",
        "projectId": "occm-dev",
        "email": "00000-compute@serviceaccount.com",
        "displayName": "Compute Engine default service account",
        "isEnabled": false
    },
    {
        "name": "projects/occm-dev/serviceAccounts/xxx-000@occmaccount.com",
        "projectId": "occm-dev",
        "email": "xxxx-000@occmaccount.com",
        "displayName": "admin",
        "isEnabled": false
    }
]
}
