---
sidebar: sidebar
permalink: cm/wf_gcp_cloud_create_we_byol.html
keywords: byol, license, cloud, manager, rest, api
summary: 'You can use this workflow to create a new Cloud Volumes ONTAP working environment using BYOL licensing.'
---

= Create a working environment with BYOL licensing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to create a new Cloud Volumes ONTAP working environment using bring your own license (BYOL) licensing.

=====
*Note the following when using BYOL licensing*:

* A marketplace subscription is not required.
* A NetApp Support Site (NSS) key is required to register the system for support.
* You can add more volumes after creating the working environment. You can choose to create a volume using either link:wf_gcp_ontap_create_vol_nfs.html[NFS], link:wf_gcp_ontap_create_vol_cifs.html[CIFS], or link:wf_gcp_ontap_create_vol_iscsi.html[iSCSI] protocol.
=====

=== 1. Select the region

Perform the workflow link:wf_gcp_cloud_md_get_regions.html[Get regions] and do the following:

* Choose the `name` value of the required region for the `region` parameter in step 8.
* Choose one of the VPCs. Choose `name` for `vpcId` parameter and `subnets: path` for `subnetId` and `subnetPath` parameters in step 8.

=== 2. Select the workspace
Perform the workflow link:wf_common_identity_get_tenants.html[Get tenants] and choose the `workspacePublicId` value for the `tenantId` parameter in step 8.

=== 3. Select the projects
Perform the workflow link:wf_gcp_cloud_md_get_projects.html[Get projects] and choose the `projectId` value of the required project for `project` parameter in step 8.

=== 4. Select the permutations
Perform the workflow link:wf_gcp_cloud_md_get_permutations.html[Get permutations] and choose the `ontapVersion`, `license: type`, and `instanceType` values of the required `vsaMetadata` parameter in step 8.

=== 5. Select the packages configuration
Perform the workflow link:wf_gcp_cloud_md_get_packages.html[Get packages] and search the `licenseType` from permutations:

* Choose the `name` for `packageName` parameter.
*	Choose the `diskSize` for `gcpVolumeSize`.
*	Choose the `diskType` and `writingSpeedState` for the `gcpVolumeType` and `writingSpeedState` parameters.

=== 6. Select the service account
Perform the workflow link:wf_gcp_cloud_md_get_service_accounts.html[Get service accounts] workflow and choose the `email` value of the required service accounts for the `gcpServiceAccount` parameter in step 8.

=== 6. Obtain the required NSS key

An NSS key is *required* when using BYOL licensing. You can create a key or select an existing key, and include the NSS key in the `nssAccount` parameter in step 10.

* To create a new NSS key, perform the link:wf_common_identity_create_nss_key.html[Create NSS key] workflow and choose the `id` value from the response.

* To select an existing NSS key, perform the workflow link:wf_common_identity_get_nss_keys.html[Get NSS keys] and choose the `id` of the required NSS user.

=== 7. Select Azure cloud provider accounts

Perform the link:wf_azure_cloud_md_create_account.html[Get Azure Cloud Provider Accounts] workflow and choose the `publicId` of the desired cloud provider account item from the `azureAccounts` for the `cloudProviderAccount` parameter.

=== 8. Select the Azure permutations

Perform the link:wf_azure_cloud_md_get_permutations.html[Get Azure Permutations] workflow and pick the desired permutation:

*	Choose the `ontapVersion` of the desired permutation for the `ontapVersion` field inside the `vsaMetadata` parameter  in step 10.
*	Choose the `type` of the desired license item from the  `license` parameter for the `licenseType` field inside the `vsaMetadata` parameter in step 10.
*	Choose the `instanceType` of the desired permutation for the `instanceType` field inside the `vsaMetadata` parameter in step 10.

=== 9. Select the Azure storage account types

Perform the link:wf_azure_cloud_md_get_storage_account_types.html[Get Azure Storage Account Types] workflow and pick the desired storage type.

*	Choose the `diskType` of the desired storage type item for the `storageType` parameter in step 10.
*	Choose the `size` of the desired disk size from the `sizes` -> `size` field for the `size` field inside the `diskSize` parameter in step 10.
*	Choose the `unit` of the desired disk size from the `sizes` -> `size` field for the `unit` field inside the `diskSize` parameter in step 10.


=== 10. Create the working environment

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/occm/api/azure/vsa/working-environments
|===

curl example::
[source,curl]
----
curl --location --request POST 'https://cloudmanager.cloud.netapp.com/occm/api/gcp/vsa/working-environments' --header 'x-agent-id: <AGENT_ID>' //1 --header 'Authorization: Bearer <ACCESS_TOKEN>' //2 --header 'Content-Type: application/json' --d @JSONinput
----
(1) Replace <AGENT_ID> with your agent ID.
(2) Replace <ACCESS_TOKEN> with your obtained bearer access token.

Input::

The JSON input example includes the minimum list of parameters. This request uses BYOL licensing as indicated in the `licenseType` parameter. The `serialNumber` is required.

JSON input example::
[source,json]
{
name: "gcpwe123"
backupVolumesToCbs: true
capacityTier: "cloudStorage"
dataEncryptionType: "GCP"
enableCompliance: true
gcpLabels: []
gcpServiceAccount: "fabric-pool@occm-dev.iam.gserviceaccount.com"
gcpVolumeSize: {size: 500, unit: "GB", _identifier: "500 GB"}
gcpVolumeType: "pd-ssd"
name: "gcpwe123"
nssAccount: "6a4d7f6e-6580-4c70-9cee-304f36b74db6"
packageName: "gcp_poc"
project: "occm-dev"
region: "europe-west3-c"
serialNumber: "90820138071000000005"
subnetId: "projects/occm-dev/regions/europe-west3/subnetworks/vpc4qa-2-europe-west3"
subnetPath: "projects/occm-dev/regions/europe-west3/subnetworks/vpc4qa-2-europe-west3"
svmPassword: "Netapp123"
tenantId: "workspaceNqaJyVMz"
tierLevel: "standard"
volume: {
  exportPolicyInfo: {
    policyType: "custom",
    ips: ["172.22.13.0/24"],
    nfsVersion: ["nfs3", "nfs4"]
  }
}
vpcId: "vpc4qa-2"
vsaMetadata: {
  ontapVersion: "ONTAP-9.10.1RC1.T1.gcp",
  licenseType: "gcp-cot-premium-byol"
}
instanceType: "n2-standard-4"
licenseType: "gcp-cot-premium-byol"
ontapVersion: "ONTAP-9.10.1RC1.T1.gcp"
writingSpeedState: "NORMAL"
}

Output::

The JSON output example includes an example of the `VsaWorkingEnvironmentRresponse` response.

JSON output example
[source,json]
{

}
