---
sidebar: sidebar
permalink: cm/wf_onprem_ontap_delete_volume.html
keywords: delete, volume, cloud, manager, rest, api, existing, volume, aws, workflows
summary: "You can delete an existing volume."
---

= Delete volume
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to delete volumes.

== 1. Select the working environment

Perform the workflow link:wf_onprem_get_wes.html[Get working environments] and choose the `publicId` and `svmName` values of the working environment  for the `workingEnvironmentId` and `svmName` path parameters.

== 2. Select the volume

Perform the workflow link:wf_onprem_ontap_get_volumes.html[Get volumes] and choose the `name` of the required volume for the `volumeName` path parameter.

== 3. Delete the volume

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/onprem/volumes/{workingEnvironmentId}/{svmName}/{volumeName}
|===


curl example::
[source,curl]
curl --location --request DELETE 'https://cloudmanager.cloud.netapp.com/occm/api/onprem/volumes/<ONPREM_WORKING_ENV_ID>/<SVM_NAME>/<VOLUME_NAME>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

Path parameters:

* <WORKING_ENV_ID> `(workingEnvironmentId)`
* <SVM_NAME> `(svmName)`
* <VOLUME_NAME> `(volumeName)`

Output::

None

