---
sidebar: sidebar
permalink: cm/wf_onprem_ontap_get_cifs.html
keywords: cloud, manager, rest, api
summary: "You can use this workflow to retrieve the CIFS server configurations for an existing Cloud Volumes ONTAP working environment."
---

= Get CIFS server configurations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to retrieve the CIFS server configurations for an existing on-premises working environment.

== Step 1. Select the working environment

Perform the workflow link:wf_onprem_get_wes.html[Get working environments] and choose the `publicId` value of the working environment for the `workingEnvironmentId` path parameter.

== Step 2. Get the CIFS configurations

You can issue a REST API call to retrieve the CIFS configurations.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/onprem/working-environments/{workingEnvironmentId}/cifs
|===

.Curl example
[source,curl]
curl --request GET \
--location "https://api.bluexp.netapp.com/occm/api/onprem/working-environments/<WORKING_ENV_ID>/cifs" \
--header "Content-Type: application/json" \
--header "x-agent-id: <AGENT_ID>" \
--header "Authorization: Bearer <ACCESS_TOKEN>"

.Additional input parameters

The JSON input example includes the minimum list of parameters.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the working environment 
|`svm` |Query |No |Identifies the SVM
|===

.JSON output example

The JSON output example includes the CIFS configurations for an existing ONTAP on-premises working environment.

----
[
    {
        "dnsDomain": "zivh.netapp.com",
        "activeDirectoryDomain": "zivh.netapp.com",
        "ipAddresses": [
            "1xx.00.5.241"
        ],
        "netBIOS": "zivaws02xxx",
        "organizationalUnit": "CN=Computers",
        "authenticationType": "domain"
    }
]
----

