---
sidebar: sidebar
permalink: cm/wf_onprem_ontap_modify_volume.html
keywords: cloud, manager, rest, api, modify, volume, bluexp
summary: "You can modify the configuration of an existing volume."
---

= Modify a volume
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can modify the configuration of an existing volume.


== Step 1. Select the working environment

Perform the workflow link:wf_onprem_get_wes.html[Get working environments] and choose the `publicId` and `svmName` values for the `workingEnvironmentId` and `svmName` path parameters.

== Step 2. Select the volume

Perform the workflow link:wf_onprem_ontap_get_volumes.html[Get volumes] and choose the `name` for the `volumeName` path parameter.

== Step 3. Modify the volume

You can issue a REST API call to modify a volume.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|PUT
|/occm/api/onprem/volumes/<ONPREM_WORKING_ENV_ID>/<SVM_NAME>/<VOLUME_NAME>
|===


.Curl example
[source,curl]
curl --request PUT
--location "https://api.bluexp.netapp.com/occm/api/onprem/volumes/<ONPREM_WORKING_ENV_ID>/<SVM_NAME>/<VOLUME_NAME>" \
--header "Content-Type: application/json" \
--header "x-agent-id: <AGENT_ID>" \
--header "Authorization: Bearer <ACCESS_TOKEN>" \
--d @JSONinput

.Additional input parameters

The JSON input example includes the minimum list of parameters.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> `(svmName)` |Path |Yes |Identifies the SVM name
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the working environment 
| <VOLUME_NAME> `(volumeName)` |Path |Yes |Identifies the volume 
|===


.JSON input example
[source,json]
{
  "exportPolicyInfo": {
    "policyType": "custom",
    "ips": [
      "1xx.00.0.0/16"
    ],
    "nfsVersion": [
      "nfs3"
    ]
  }
}


.Output

None

