---
sidebar: sidebar
permalink: cm/wf_onprem_ontap_delete_volume.html
keywords: delete, volume, bluexp, rest, api, existing, volume, aws, workflows
summary: "You can delete an existing volume."
---

= Delete a volume
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this workflow to delete a volume.

== Step 1. Select the working environment

Perform the workflow link:wf_onprem_get_wes.html[Get working environments] and choose the `publicId` and `svmName` values of the working environment  for the `workingEnvironmentId` and `svmName` path parameters.

== Step 2. Select the volume

Perform the workflow link:wf_onprem_ontap_get_volumes.html[Get volumes] and choose the `name` of the required volume for the `volumeName` path parameter.

== Step 3. Delete the volume

You can issue a REST API call to delete a volume.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/onprem/volumes/{workingEnvironmentId}/{svmName}/{volumeName}
|===


.Curl example
[source,curl]
curl --request DELETE \
--location "https://api.bluexp.netapp.com/occm/api/onprem/volumes/<ONPREM_WORKING_ENV_ID>/<SVM_NAME>/<VOLUME_NAME>" \
--header "x-agent-id: <AGENT_ID>" \
--header "Authorization: Bearer <ACCESS_TOKEN>"

.Additional input parameters

The JSON input example includes the minimum list of parameters.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> `(svmName)` |Path |Yes |Identifies the SVM name
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the working environment ID
| <AGGR_NAME> `(aggregateName)` |Path |Yes |Identifies the aggregate 
|===

.Output

None

