---
sidebar: sidebar
permalink: cm/wf_onprem_discover_wes.html
keywords: bluexp, rest, api, list, working, environment, occm
summary: "You can retrieve the on-premises working environments that are visible to the user currently signed in."
---

= Discover working environments
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can discover the on-premises ONTAP clusters and add them to a working environment using the cluster name as the working environment name.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/onprem/working-environments
|===

.Curl example
[source,curl]
curl --request GET
--location "https://api.bluexp.netapp.com/occm/api/onprem/working-environments" \
--header "Content-Type: application/json" \
--header "x-agent-id: <AGENT_ID>" \
--header "Authorization: Bearer <ACCESS_TOKEN>"

.JSON input example
[source,json]
{
  "clusterPassword": "password",
  "description": "Onprem Working Environment",
  "clusterUserName": "admin",
  "name": "onpremwe",
  "location": "ON_PREM",
  "clusterAddress": "10.xxx.0.40",
  "tenantId": "workspaceUsXAxxxxxx"
}


.JSON output example

The JSON output includes an example of on-prem working environments.

.Example output
----
{
  "publicId": "OnPremWorkingEnvironment-i7by5xxx",
  "tenantId": "Tenant-dfxx5",
  "description": "Onprem Working Environment",
  "name": "onpremwe",
  "discoverUserEmail": "user_Email@domain.com",
  "location": "ON_PREM",
  "reservedSize": null,
  "status": null,
  "interClusterLifs": null,
  "cronJobSchedules": null,
  "svms": null,
  "snapshotPolicies": null,
  "replicationProperties": null,
  "clusterProperties": null,
  "ontapClusterProperties": null,
  "workingEnvironmentType": "ON_PREM",
  "cloudSyncProperties": null,
  "actionsRequired": null,
  "capacityFeatures": null,
  "aff": false,
  "cbsProperties": null,
  "complianceProperties": null,
  "monitoringProperties": null
}
----



