---
sidebar: sidebar
permalink: cm/workflow_processes.html
keywords: workflows, processes, bluexp, api, on-prem ONTAP
summary: "You should be familiar with the high-level organization and format of the BlueXP workflow processes before using them with a live cloud deployment."
---

= Workflow processes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should be familiar with the organization and format of the Cloud Volumes ONTAP and ONTAP on-premises workflow processes before using them with a live deployment.

[NOTE]
Before getting started with the workflows, see link:../platform/workflows_tasks.html[Workflow processes and tasks] for an introduction on how workflows and tasks are generally used with BlueXP.

== High level organization of the workflows

There are two broad categories of workflows associated with the ONTAP management service. They are as follows:

Cloud Volumes ONTAP workflows::
This set of workflows enables you to manage the Cloud Volumes ONTAP instances deployed in a cloud provider (AWS, Azure, or Google Cloud).

ONTAP on-premises workflows::
This set of workflows enable you to discover and manage the ONTAP clusters residing on your premises. 

There's similarity between the functional categories of the Cloud Volumes ONTAP and on-premises ONTAP workflows, however, there are a few key differences presented as follows.

=== Organization of Cloud Volumes ONTAP workflows

At a high level, the Cloud Volumes ONTAP workflows are organized based on three primary attributes. The organization is reflected in the navigation sidebar. 

.Cloud provider
The Cloud Volumes ONTAP workflows can be performed with one cloud provider. The supported cloud platforms include:

* Amazon Web Services (AWS)
* Microsoft Azure
* Google Cloud 

.Functional category

The workflows for each cloud provider (AWS, Azure, Google Cloud) are placed in a specific functional category. The major categories as reflected in the navigation sidebar are presented below.

*Working environments*
A working environment is the context within which a Cloud Volumes ONTAP instance is deployed and run. These workflows allow you to create working environments and perform related administrative tasks. You can perform specific workflows to create a working environment based on your preferred licensing model (PAYGO or BYOL), remove a working environment, and retrieve the details of a working environment. In addition, you can configure the CIFS server when creating a volume that uses the CIFS protocol as part of creating a working environment.

*Aggregates*
An aggregate is the low-level structure for Cloud Volumes ONTAP storage. These workflows allow you to create aggregates and perform related administrative tasks.

*Volumes*
You can expose the storage volumes for use by your applications. You can perform these workflows to create a volume (using NFS, CIFS, or iSCSI protocol) as well as delete, retrieve, and modify an existing volume based on your storage requirements.

*Metadata*
The metadata workflows allow you to view and administer the basic configuration of your cloud environment.

*Miscellaneous*
A workflow that is not assigned to an existing functional category is considered Miscellaneous. For example, there is a workflow to create a cloud provider account. The cloud provider account securely stores and manages your cloud provider credentials and establishes an identity for users (such as InstanceProfile with AWS and ManagedIdentity with Azure). This account provides fine-grained authorization of the services and resources based on multiple critical conditions.


.Single node and High availability workflows

Many of the workflows vary based on the type of the deployment.

*Single node*
The cluster consists of a single Cloud Volumes ONTAP instance or ONTAP node.

*HA pair*
The cluster consists of two linked Cloud Volumes ONTAP instances which together provide the ONTAP high availability (HA) feature.

[NOTE]
If both versions of a workflow exist for an administrative task, they are included on the same page.

=== Organization of the ONTAP on-premises workflows

The ONTAP on-premises workflows are placed in a specific functional category. They resemble the organizational pattern of the Cloud Volumes ONTAP workflows. Following are the major categories that are reflected on the sidebar.

.Working environments
A working environment is the context within which an ONTAP on-premise instance is added after being discovered. These workflows enable you to discover and manage the ONTAP on-prem clusters. In addition, you can configure the CIFS server when creating a volume that uses the CIFS protocol as part of managing an on-premises environment.

.Aggregates
An aggregate is the low-level structure for ONTAP on-premises storage. There's a singular workflow that enables you to retrieve aggregates.

.Volumes
You can expose the storage volumes for use by your applications. You can perform these workflows to create a volume (using NFS, CIFS, or iSCSI protocol) as well as delete, retrieve, and modify an existing volume based on your storage requirements.

[NOTE]
In addition to the workflows used with the specific cloud providers, there is also a set of common workflows that can be used with any cloud provider. See link:wf_common_before.html[Common workflows] for all cloud providers for more information about these workflows and how they are organized.

== Presentation of common tokens and identifiers

Most of the variable tokens, identifiers, and other variables used in the sample REST API calls consist of long strings of letters, numbers, and special characters. They are considered _opaque_ with no easily discernible content or meaning. Therefore, rather than including the actual original strings, smaller reserved keywords are used instead. This has several benefits:

* The curl and JSON samples are simpler and easier to understand.
* Because all keywords use the same format (including capital letters), you can quickly identify the content to insert or extract.
* No value is lost because the original values cannot be copied and used with an actual deployment.

A list of the keywords used in the workflow curl examples is presented in the table below.

[cols="25,75",options="header"]
|===
|Keyword
|Description
|<ACCESS_TOKEN>
|An access token is a temporary string which establishes identity and access based on the OAuth2 standard.
|<ID_TOKEN>
|The ID token contains additional identity information for the user based on OpenID Connect (OIDC).
|<CLIENT_ID>
|This value uniquely identifies the user within a specific authorization domain.
|<AGENT_ID>
|The agent identifier is based on the client ID and is used to identify the user agent.
|<ACCOUNT_ID>
|This value identifies your NetApp account.
|<NSS_KEY_ID>
|This value identifies an entitlement key and is used by NetApp support.
|<WORKING_ENV_ID>
|This value identifies a working environment for the ONTAP runtime and so is synonymous with a Cloud Volumes ONTAP instance.
|<SVM_NAME>
|The name used for an ONTAP storage virtual machine.
|<VOLUME_NAME>
|The name used for an ONTAP storage volume.
|<AGGR_NAME>
|The aggregate name for a disk operation.
|<REQUEST_ID>
|This value is returned to the caller in the HTTP response and uniquely identifies the request.
|<PROVIDER>
|Abbreviation for the cloud provider.
|<CLOUD_ACC_ID>
|Account ID for the cloud provider.
|<REFRESH_TOKEN>
|NetApp refresh token used for federated authentication.
|===

[NOTE] 
Replace the variables with actual values while performing a curl call.

== Working environment status requirements

Many of the workflows require the working environment to have a specific status (such as `ON` or `DEGRADED`) before the REST API call can be performed. Review the link:api_reference.html[API reference content] for details about the requirements for each API call.
