---
sidebar: sidebar
permalink: cm/your_api_call.html
keywords: hello, world, cloud, manager, rest, api, cloud , manager
summary: "You can issue a curl command to get started using the REST API and confirm its availability."
---

= Your first API call
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can issue a curl command to get started using a Cloud Volumes ONTAP REST API and confirm its availability.

[NOTE]
The following workflow example is very simple. The workflow samples later in this documentation use a more robust format. See link:workflow_processes.html[Workflow processes] to get started.

== Step 1. Select the identifier

Determine the identifier to use for the `x-agent-id` request header. See link:../platform/get_identifiers.html[Get required identifiers].

== Step 2. Get the access token

Acquire an access token for the `Authorization` request header. See link:../platform/create_user_token.html[Create user token].

.Curl example
The following curl command retrieves information about the BlueXP server.

[source,curl]
curl --request GET \
--location 'https://api.bluexp.netapp.com/occm/api/occm/system/about' \
--header 'Content-Type: application/json' \
--header 'x-agent-id: <AGENT_ID>' \
--header 'Authorization: Bearer <ACCESS_TOKEN>'

[TIP]
====
* Replace <AGENT_ID> with your agent ID.
* Replace <ACCESS_TOKEN> with the bearer access token.
====

.JSON output example
Information about the system is provided in the following JSON format.

----
{
  "version": "string",
  "build": "string",
  "buildTimestamp": "integer",
  "systemId": "string",
  "environment": "string",
  "siteIdentifier": {
    "company": "string",
    "host": "string",
    "site": "string"
  },
  "serverTimeZone": {
    "timeZoneName": "string",
    "formattedTimeZone": "string"
  },
  "beta": "boolean",
  "releaseNumber": "integer",
  "simplicatorUrl": "string",
  "migrationPerformed": "boolean",
  "demoMode": "boolean",
  "usingDockerInfra": "boolean",
  "privateIp": "string"
}
----