---
sidebar: sidebar
permalink: platform/additional_considerations.html
keywords: bluexp, rest, api, asynchronous, processing, public identifiers
summary: 'There are several additional characteristics of the BlueXP REST API affecting its operation and use. You should be aware of these considerations before issuing an API call.'
---

= Additional considerations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several additional characteristics of the BlueXP REST APIs affecting their operation and use. You should be aware of these considerations before issuing an API call.

== Public identifiers

All resources exposed through the BlueXP APIs (for example, working environments of the Cloud Volumes ONTAP API) are assigned a public ID. Whenever a resource is created or returned, the public ID is displayed in the response. You must specify a resource's public ID when performing operations on the resource. For example, you must specify the public ID for a working environment when you create a volume.

== Asynchronous processing

For most of the BlueXP REST APIs, all HTTP request methods except GET are processed asynchronously. If needed, you can check the status of an active task based on the `request id` returned in the original HTTP response. Each task has a status value as described in the following table.

[cols="20,80",options="header"]
|===
|Status
|Description
|1
|The asynchronous task completed successfully.
|0
|The background task is still running and has not completed.
|-1
|The asynchronous task completed but failed.
|===

See link:../cm/wf_common_occm_get_task.html[Get active task] for more information about how to retrieve the status of a background task for an asynchronous request. 