---
sidebar: sidebar
permalink: platform/concepts.html
keywords: rest, api, cloud, manager, http, endpoints, administrative resources, authentication, auditing
summary: 'Representational State Transfer (REST) is a style for creating distributed web applications.'
---

= Basic concepts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Representational State Transfer (REST) is a style for creating distributed web applications. When applied to the design of a web services API, it establishes a set of technologies and best practices for exposing server-based resources and managing their states. The BlueXP REST APIs use mainstream protocols and standards to provide a flexible foundation for deploying and administering your cloud-based and on-premise resources.

[NOTE]
While REST establishes a common set of technologies and best practices, the details of each API can vary based on the design choices of the development team. See the reference for the API you plan to use.

== Overview of the API resources

The REST style of application development begins by identifying a set of server-based resources. The resources defined with the BlueXP REST APIs can be broadly categorized as follows:

* Storage resources 
  Used to manage and administer cloud storage resources (for example, Cloud Volumes ONTAP, Azure NetApp Files) as well as on-premises and edge storage resources

* Platform resources
  Used to manage users, workspaces, accounts, Connectors, credentials in BlueXP control plane

* Data resources
  Used to protect and create backup of your cloud and on-premises data, manage your licenses and subscriptions to BlueXP 

== REST endpoints

REST resources are accessed through endpoints identified in the URL path. Each endpoint provides access to one of the following:

* Resource instance
* Collection of resource instances


== Types of input parameters

There are several types of parameters available with the BlueXP APIs with each request.

[cols="20,80",options="header"]
|===
|Type
|Description
|Path parameter
|Identifiers or names for resource instances that are included in the URL path.
|Query parameter
|One or more key-value pairs at the end of the URL which qualify and extend the base call.
|Request header
|Key-value pairs in the request which carry additional information available to the server.
|Body parameter
|Data which is optionally included with a request and formatted using JSON.
|===
