---
sidebar: sidebar
permalink: platform/get_nss_key.html
keywords: nss, credentials, key, cloud, manager, rest, api, nss, credential
summary: 'You can sign in to the Cloud Manager web user interface to retrieve the NetApp Support Site credentials key.'
---

= Generate NSS user ID
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can sign in to the Cloud Manager web user interface to create an NetApp Support Site (NSS) user id. This ID can be used when creating a Cloud Manager working environment and enables NetApp support and analytics.

See link:https://docs.netapp.com/us-en/occm/task_adding_nss_accounts.html[Add and manage NetApp Support Site accounts in Cloud Manager^] for more information about managing your NSS accounts.

//[NOTE]
//You need the NSS key when creating a working environment that uses BYOL ("bring your own") licensing.

.Before you begin

You must have a NetApp account (formerly Cloud Central account). You created this account when you first logged in to Cloud Manager and it’s displayed at the top of the Cloud Manager user interface. See link:https://docs.netapp.com/us-en/occm/concept_cloud_central_accounts.html[Learn about NetApp accounts^] for more information.

.Steps

. Navigate to the Cloud Manager web site using a browser:
+
https://cloudmanager.netapp.com

. Sign in using your NetApp account (formerly Cloud Central account) credentials.

. Click on the ? icon at the top right of the page and select *Support*.

. Navigate to the *NSS Management* tab and click *Add NSS Account*.

. When prompted, click *Continue* which will redirect you to a Microsoft login page.
+
NetApp uses Microsoft Azure Active Directory as the identity provider for authentication services specific to support and licensing.

. Provide the NSS email address and password to perform the authentication process. After successful authentication, an NSS User ID will be generated.

.After you finish

You can use the generated NSS User ID when creating a working environment with your preferred choice of licensing for a cloud provider. The NSS User ID is optional for PAYGO subscription but mandatory for BYOL licensing.
