---
sidebar: sidebar
permalink: platform/get_client_id.html
keywords: client, id, account, identifiers, cloud, manager, rest, api, netapp, user interface
summary: 'You can sign in to the Cloud Manager web user interface to retrieve the client and account identifiers to use with the workflows.'
---

= Get the client and account identifiers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can sign into the Cloud Manager web user interface to retrieve the client and account identifiers to use with the workflows. You can use these identifiers to access the metadata, authentication, and security related information.

[NOTE]
This page includes two tasks describing how to use the Cloud Manager web user interface to retrieve the ID values. You can also use the Cloud Manager REST API to get the ID values. See link:../cm/wf_common_identity_get_supported_srv.html[Get supported services] for more information.

== Get the client identifier

You can retrieve the client ID and use it with the x-agent-id HTTP request header.

.About this task

You need to access the client ID which is unique for each Cloud Manager Connector and then use it as the agent identifier.



.Before you begin

You must have a NetApp account (formerly Cloud Central account). You created this account when you first logged in to Cloud Manager and it was displayed at the top of the Cloud Manager user interface. See link:https://docs.netapp.com/us-en/occm/concept_cloud_central_accounts.html[Learn more about NetApp accounts^] for more information.

//You must have a NetApp account (formerly Cloud Central account). You created this account when you first logged in to Cloud Manager and it’s displayed at the top of the Cloud Manager user interface. link:https://docs.netapp.com/us-en/occm/concept_cloud_central_accounts.html[Learn more about NetApp accounts^].

.Steps

. Navigate to the Cloud Manager web site using a browser:
+
link:https://cloudmanager.netapp.com[https://cloudmanager.netapp.com^]

. Sign in using your NetApp account (formerly Cloud Central account) credentials.

. Click *Connector* at the top right of the page and select *Manage Connectors*.

. On the *Manage Connectors* page, click the ellipses (...) icon.

. Select the *Connector ID*. This value is based on the client ID.
+
You can use the Connector ID in the x-agent-id HTTP request header as shown in the workflow curl examples, `uzJbMFKEnuzi2ryLaENbCP52KBTXx0aIclients`.


== Get the account identifier

You can also retrieve the account ID.

.About this task

You can create multiple accounts and access the unique identifier for each account.

.Before you begin

You must have a NetApp account (formerly Cloud Central account). You created this account when you first logged in to Cloud Manager and it’s displayed at the top of the Cloud Manager user interface. link:https://docs.netapp.com/us-en/occm/concept_cloud_central_accounts.html[Learn more about NetApp accounts^].

.Steps

. Navigate to the Cloud Manager web site using a browser:
+
link:https://cloudmanager.netapp.com[https://cloudmanager.netapp.com^]

. Sign in using your NetApp account (formerly Cloud Central account) credentials.

. Click the *Account* drop-down and click *Manage Account* for the selected account.

. In the *Overview* section copy the *Account ID* value.
