---
sidebar: sidebar
permalink: platform/get_nss_key.html
keywords: nss, credentials, key, cloud, manager, rest, api, nss, credential
summary: 'You can sign in to the Cloud Manager web user interface to retrieve the NetApp Support Site credentials key.'
---

= Generate an NSS user ID
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can sign in to the Cloud Manager web user interface to create a NetApp Support Site (NSS) user ID. This ID can be included when creating a Cloud Manager working environment to enable support and analytics.

.About this task

Registering credentials and creating an NSS user id is an important Cloud Manager administrative task. For information about related administrative tasks, see link:https://docs.netapp.com/us-en/occm/task_adding_nss_accounts.html[Add and manage NetApp Support Site accounts in Cloud Manager^].

//[NOTE]
//You need the NSS key when creating a working environment that uses BYOL ("bring your own") licensing.

.Before you begin

You must have a NetApp account (formerly Cloud Central account). You normally create this account when first signing in to Cloud Manager and it's displayed at the top of the web user interface. See link:https://docs.netapp.com/us-en/occm/concept_cloud_central_accounts.html[Learn about NetApp accounts^] for more information.

.Steps

. Navigate to the Cloud Manager web site using a browser:
+
https://cloudmanager.netapp.com

. Sign in using your NetApp account (formerly Cloud Central account) credentials.

. Click on the *?* icon at the top right of the page and select *Support*.

. Navigate to the *NSS Management* tab and click *Add NSS Account*.

. When prompted, click *Continue* which redirects you to a Microsoft login page.
+
NetApp uses Microsoft Azure Active Directory as the identity provider for authentication services specific to support and licensing.

. Provide the NSS email address and password. An NSS user ID is generated after successful authentication.

.After you finish

You can use the generated NSS user ID when creating a working environment with your preferred choice of licensing model and cloud provider. The NSS user ID is optional for the PAYGO subscription but mandatory with BYOL licensing.
