---
sidebar: sidebar
permalink: platform/overview.html
keywords: overview, bluexp
summary: "BlueXP enables you to build, protect, and govern your hybrid multi-cloud data from a single control plane. It is composed of several distinct REST APIs."
---

= Overview of BlueXP APIs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP enables you to build, protect, and govern your hybrid multi-cloud data from a single control plane. It is composed of several distinct services, each of which exposes an associated REST API. Collectively these services and APIs form a flexible and extensible development platform you can use to administer your cloud-based and on-premises resources. There are several benefits to using the BlueXP REST APIs.

.Built on REST technology and design principles
The BlueXP APIs have been designed based on REST technology and current best practices. The core technologies include Hypertext Transfer Protocol (HTTP) and JavaScript Object Notation (JSON).

.Rich set of platform services
The APIs provide access to a rich set of services including storage, cloud, and security. Applications based on the BlueXP platform are robust, resilient, and supportable.

.Access to NetApp cloud token-based security
BlueXP authentication and authorization is based on the OAuth2 standard. NetApp relies on the Auth0 service implementation.

.Alignment with the BlueXP web UI
The BlueXP web user interface uses the same core REST APIs and so there is consistency between the two access paths.

