---
sidebar: sidebar
permalink: platform/register_service.html
keywords: generate, user, token, bluexp, rest, apis, account, create, application
summary: You can register a service with BlueXP and use the associated credentials to create a service token.
---

= Register a service
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can register a service with BlueXP and use the associated credentials to create a service token.

.Before you begin

You must have a BlueXP account. You created this account when you first logged in to BlueXP website and it was displayed at the top of the BlueXP user interface. 

.Steps

. Navigate to the BlueXP website using a browser:
+
link:https://console.bluexp.netapp.com[https://console.bluexp.netapp.com^]

. Sign in using your NetApp Cloud credentials or your NetApp Support Site credentials.

. Select the *Account* tab at the top of the SaaS UI.

. Select *Manage Account* and select the *Members* tab.

. Select *Create Service Account* and provide the details for the service account

. Select *Create* to register the application.

.After you finish

After successfully completing the registration, the associated client ID and client secret are displayed.
