---
sidebar: sidebar
permalink: platform/register_service.html
keywords: generate, user, token
summary:
---

= Register service
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can register a service with Cloud Manager and use the associated credentials to create a service token.

.Before you begin

You must have a NetApp account (formerly Cloud Central account). You created this account when you first logged in to Cloud Manager and it was displayed at the top of the Cloud Manager user interface. See link:https://docs.netapp.com/us-en/occm/concept_cloud_central_accounts.html[Learn more about NetApp accounts^] for more information

.Steps

. Navigate to the Cloud Manager web site using a browser:
+
link:https://cloudmanager.netapp.com[https://cloudmanager.netapp.com^]

. Sign in using your NetApp account (formerly Cloud Central account) credentials.

. Click the *Account* tab at the top of the SaaS UI.

. Click *Manage Account* and select the *Members* tab.

. Click *Create Service Account* and provide the details for the service account

. Click *Create* to register the application.

.After you finish

After successfully completing the registration, the associated client ID and client secret are displayed.
